import { StyleSheet } from 'react-native';
import { borderRadius, spacing, typography } from '../../constants/colors';
import type { Theme } from '../../constants/theme';

export const createAdminContactStyles = (
  theme: Theme,
  isDark: boolean,
  isDesktop: boolean
) => StyleSheet.create({
  container: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
  },
  toolbar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.md,
    zIndex: 20,
  },
  search: {
    flex: 1,
    minWidth: isDesktop ? 240 : 180,
    marginBottom: 0,
  },
  filter: {
    width: isDesktop ? 190 : '46%',
    flexGrow: isDesktop ? 0 : 1,
  },
  split: {
    flex: 1,
    minHeight: 0,
    flexDirection: isDesktop ? 'row' : 'column',
    gap: spacing.md,
  },
  panel: {
    flex: 1,
    minHeight: 0,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: borderRadius.xl,
    backgroundColor: isDark ? theme.bgElevated : theme.bgCard,
    overflow: 'hidden',
  },
  listPanel: { flex: isDesktop ? 0.9 : 1 },
  detailPanel: { flex: 1.2 },
  panelHeader: {
    padding: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  panelTitle: {
    color: theme.textPrimary,
    fontFamily: theme.fontHeading,
    fontSize: typography.fontSizes.xl,
  },
  panelSubtitle: {
    color: theme.textSecondary,
    fontSize: typography.fontSizes.sm,
    marginTop: 4,
  },
  panelScroll: {
    flex: 1,
    minHeight: 0,
  },
  scrollContent: { padding: spacing.md, gap: spacing.sm },
  listItem: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: borderRadius.lg,
    backgroundColor: theme.bg,
    padding: spacing.md,
  },
  listItemSelected: {
    borderColor: theme.primary,
    backgroundColor: theme.primaryAlpha12,
  },
  listItemUnread: { borderLeftWidth: 4, borderLeftColor: theme.primary },
  listTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm,
  },
  reference: {
    color: theme.primary,
    fontSize: typography.fontSizes.xs,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  specialist: {
    color: theme.textPrimary,
    fontSize: typography.fontSizes.md,
    fontWeight: '600',
    marginTop: spacing.sm,
  },
  meta: {
    color: theme.textMuted,
    fontSize: typography.fontSizes.xs,
    marginTop: 5,
  },
  unread: {
    color: theme.primary,
    fontSize: typography.fontSizes.xs,
    fontWeight: '700',
    marginTop: spacing.sm,
  },
  pill: {
    borderRadius: borderRadius.full,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  pillText: { fontSize: 11, fontWeight: '700' },
  detailContent: {
    padding: spacing.lg,
    gap: spacing.md,
    position: 'relative',
  },
  back: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    alignSelf: 'flex-start',
    paddingVertical: spacing.xs,
  },
  backText: { color: theme.primary, fontWeight: '600' },
  detailHeading: {
    color: theme.textPrimary,
    fontFamily: theme.fontHeading,
    fontSize: typography.fontSizes.xl,
  },
  detailMeta: { color: theme.textSecondary, fontSize: typography.fontSizes.sm },
  thread: { gap: spacing.sm },
  message: {
    maxWidth: isDesktop ? '84%' : '96%',
    borderWidth: 1,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
  },
  messageSpecialist: {
    alignSelf: 'flex-start',
    backgroundColor: theme.secondaryMuted,
    borderColor: theme.secondaryLight,
  },
  messageAdmin: {
    alignSelf: 'flex-end',
    backgroundColor: theme.primaryAlpha12,
    borderColor: theme.primaryAlpha20,
  },
  messageAuthor: {
    color: theme.primary,
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 5,
  },
  messageBody: {
    color: theme.textPrimary,
    fontSize: typography.fontSizes.sm,
    lineHeight: 21,
  },
  messageDate: { color: theme.textMuted, fontSize: 10, marginTop: spacing.sm },
  actions: {
    flexDirection: isDesktop ? 'row' : 'column',
    gap: spacing.sm,
    alignItems: isDesktop ? 'center' : 'stretch',
    position: 'relative',
    zIndex: 100,
    elevation: 12,
  },
  actionGrow: { flex: isDesktop ? 1 : undefined },
  textarea: { minHeight: 110, paddingTop: spacing.md },
  notificationCard: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: borderRadius.md,
    padding: spacing.sm,
    backgroundColor: theme.bg,
  },
  notificationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  notificationTitle: {
    color: theme.textPrimary,
    fontSize: typography.fontSizes.sm,
    fontWeight: '600',
  },
  notificationMeta: {
    color: theme.textMuted,
    fontSize: typography.fontSizes.xs,
    marginTop: 3,
  },
  bodyCard: {
    color: theme.textPrimary,
    fontSize: typography.fontSizes.sm,
    lineHeight: 22,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: theme.border,
    padding: spacing.lg,
    backgroundColor: theme.bg,
  },
  contextCard: {
    borderRadius: borderRadius.md,
    backgroundColor: theme.bgMuted,
    padding: spacing.md,
  },
  contextText: { color: theme.textSecondary, fontSize: typography.fontSizes.xs },
  center: {
    minHeight: 280,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
  },
  emptyTitle: {
    color: theme.textPrimary,
    fontSize: typography.fontSizes.md,
    fontWeight: '600',
    marginTop: spacing.sm,
  },
  emptyText: {
    color: theme.textSecondary,
    fontSize: typography.fontSizes.sm,
    textAlign: 'center',
    marginTop: 4,
  },
  error: {
    color: theme.error,
    backgroundColor: theme.errorBg,
    borderRadius: borderRadius.md,
    padding: spacing.sm,
    marginBottom: spacing.md,
  },
  warning: {
    color: theme.status.pending.text,
    backgroundColor: theme.status.pending.bg,
    borderWidth: 1,
    borderColor: theme.status.pending.border,
    borderRadius: borderRadius.md,
    padding: spacing.sm,
    marginBottom: spacing.md,
  },
  loadMore: { marginTop: spacing.sm },
});
