import { StyleSheet } from 'react-native';
import { spacing } from '../../../constants/colors';
import { Theme } from '../../../constants/theme';

export const createWorkspaceStyles = (theme: Theme, isCompact: boolean) =>
  StyleSheet.create({
    workspace: {
      gap: spacing.lg,
    },
    headerActions: {
      flexDirection: 'row',
      gap: spacing.sm,
      alignItems: 'center',
      justifyContent: 'flex-end',
    },
    notice: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      backgroundColor: theme.warningBg,
      padding: spacing.md,
    },
    noticeText: {
      color: theme.textSecondary,
      fontFamily: theme.fontSans,
      fontSize: 13,
      lineHeight: 19,
      flex: 1,
    },
    contentGrid: {
      flexDirection: isCompact ? 'column' : 'row',
      alignItems: 'flex-start',
      gap: spacing.lg,
    },
    listPanel: {
      width: '100%',
      minWidth: 0,
      flex: isCompact ? undefined : 1,
    },
    detailPanel: {
      width: '100%',
      minWidth: 0,
      flexShrink: 0,
      maxWidth: isCompact ? undefined : 460,
    },
    emptyPanel: {
      minHeight: 320,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      backgroundColor: theme.bgCard,
      padding: spacing.xl,
      gap: spacing.md,
    },
    emptyTitle: {
      color: theme.textPrimary,
      fontFamily: theme.fontSansBold,
      fontSize: 20,
      lineHeight: 26,
      textAlign: 'center',
    },
    emptyText: {
      color: theme.textSecondary,
      fontFamily: theme.fontSans,
      fontSize: 14,
      lineHeight: 21,
      textAlign: 'center',
      maxWidth: 560,
    },
    statePanel: {
      minHeight: 220,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      backgroundColor: theme.bgMuted,
      padding: spacing.lg,
      gap: spacing.md,
    },
    stateTitle: {
      color: theme.textPrimary,
      fontFamily: theme.fontSansBold,
      fontSize: 17,
      lineHeight: 23,
      textAlign: 'center',
    },
    stateText: {
      color: theme.textSecondary,
      fontFamily: theme.fontSans,
      fontSize: 14,
      lineHeight: 21,
      textAlign: 'center',
      maxWidth: 420,
    },
  });

export const createListPanelStyles = (theme: Theme) =>
  StyleSheet.create({
    panel: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      backgroundColor: theme.bgCard,
      padding: spacing.lg,
      gap: spacing.md,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: spacing.md,
    },
    title: {
      color: theme.textPrimary,
      fontFamily: theme.fontSansBold,
      fontSize: 20,
      lineHeight: 26,
    },
    text: {
      color: theme.textSecondary,
      fontFamily: theme.fontSans,
      fontSize: 13,
      lineHeight: 19,
      marginTop: spacing.xs,
    },
    list: {
      gap: spacing.sm,
    },
    filtersRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'flex-start',
      gap: spacing.sm,
      position: 'relative',
      zIndex: 20,
    },
    filterField: {
      gap: spacing.xs,
      position: 'relative',
      zIndex: 20,
    },
    filterFieldCompact: {
      minWidth: 150,
      flexGrow: 1,
      flexBasis: 150,
    },
    filterFieldWide: {
      minWidth: 220,
      flexGrow: 2,
      flexBasis: 220,
    },
    filterLabel: {
      color: theme.textSecondary,
      fontFamily: theme.fontSansSemiBold,
      fontSize: 13,
      lineHeight: 18,
    },
    statePanel: {
      minHeight: 220,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      backgroundColor: theme.bgMuted,
      padding: spacing.lg,
      gap: spacing.md,
    },
    stateTitle: {
      color: theme.textPrimary,
      fontFamily: theme.fontSansBold,
      fontSize: 17,
      lineHeight: 23,
      textAlign: 'center',
    },
    stateText: {
      color: theme.textSecondary,
      fontFamily: theme.fontSans,
      fontSize: 14,
      lineHeight: 21,
      textAlign: 'center',
      maxWidth: 420,
    },
    loadMore: {
      alignItems: 'center',
      paddingTop: spacing.xs,
    },
  });

export const createListItemStyles = (theme: Theme) =>
  StyleSheet.create({
    item: {
      minHeight: 92,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      backgroundColor: theme.bgElevated,
      padding: spacing.md,
    },
    itemSelected: {
      borderColor: theme.focus,
      backgroundColor: theme.primaryAlpha12,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.secondaryMuted,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    avatarText: {
      color: theme.textPrimary,
      fontFamily: theme.fontSansBold,
      fontSize: 18,
      lineHeight: 22,
    },
    itemContent: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    itemTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
    },
    itemTitle: {
      flex: 1,
      color: theme.textPrimary,
      fontFamily: theme.fontSansBold,
      fontSize: 15,
      lineHeight: 21,
    },
    itemMeta: {
      color: theme.textSecondary,
      fontFamily: theme.fontSans,
      fontSize: 13,
      lineHeight: 18,
    },
    itemSubMeta: {
      flex: 1,
      color: theme.textMuted,
      fontFamily: theme.fontSans,
      fontSize: 12,
      lineHeight: 17,
    },
    itemFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
  });

export const createBadgeStyles = (theme: Theme) =>
  StyleSheet.create({
    badge: {
      minHeight: 26,
      borderRadius: 999,
      paddingHorizontal: spacing.sm,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
    },
    badgeActive: {
      backgroundColor: theme.successBg,
      borderColor: theme.status.confirmed.border,
    },
    badgeArchived: {
      backgroundColor: theme.bgMuted,
      borderColor: theme.border,
    },
    badgeAssigned: {
      backgroundColor: theme.primaryAlpha12,
      borderColor: theme.focus,
    },
    badgeNeutral: {
      backgroundColor: theme.bgMuted,
      borderColor: theme.border,
    },
    badgeText: {
      fontFamily: theme.fontSansSemiBold,
      fontSize: 12,
      lineHeight: 16,
    },
    badgeTextActive: {
      color: theme.success,
    },
    badgeTextArchived: {
      color: theme.textMuted,
    },
    badgeTextAssigned: {
      color: theme.primary,
    },
    badgeTextNeutral: {
      color: theme.textMuted,
    },
  });

export const createDetailStyles = (theme: Theme) =>
  StyleSheet.create({
    panel: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      backgroundColor: theme.bgCard,
      padding: spacing.lg,
      gap: spacing.lg,
      minWidth: 0,
    },
    hero: {
      minWidth: 0,
      gap: spacing.md,
      borderWidth: 1,
      borderColor: theme.borderLight,
      borderRadius: 10,
      backgroundColor: theme.primaryAlpha12,
      padding: spacing.md,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: spacing.md,
    },
    headerIcon: {
      width: 42,
      height: 42,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primaryAlpha12,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    headerCopy: {
      flex: 1,
      minWidth: 0,
      gap: spacing.xs,
    },
    heroAvatar: {
      width: 48,
      height: 48,
      flexShrink: 0,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 10,
      backgroundColor: theme.bgCard,
    },
    heroAvatarText: {
      color: theme.primary,
      fontFamily: theme.fontSansBold,
      fontSize: 18,
      lineHeight: 23,
    },
    heroFacts: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
    },
    heroFact: {
      minWidth: 0,
      flexGrow: 1,
      flexBasis: 155,
      gap: 3,
      borderWidth: 1,
      borderColor: theme.borderLight,
      borderRadius: 8,
      backgroundColor: theme.bgCard,
      padding: spacing.sm,
    },
    heroFactLabel: {
      color: theme.textMuted,
      fontFamily: theme.fontSansSemiBold,
      fontSize: 11,
      lineHeight: 16,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    heroFactValue: {
      color: theme.textPrimary,
      fontFamily: theme.fontSansSemiBold,
      fontSize: 13,
      lineHeight: 18,
    },
    title: {
      color: theme.textPrimary,
      fontFamily: theme.fontSansBold,
      fontSize: 20,
      lineHeight: 26,
    },
    subtitle: {
      color: theme.textSecondary,
      fontFamily: theme.fontSans,
      fontSize: 13,
      lineHeight: 19,
    },
    rows: {
      gap: spacing.xs,
      minWidth: 0,
    },
    row: {
      minHeight: 42,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
      paddingVertical: spacing.sm,
    },
    rowLabel: {
      color: theme.textMuted,
      fontFamily: theme.fontSansSemiBold,
      fontSize: 12,
      lineHeight: 17,
    },
    rowValue: {
      flex: 1,
      color: theme.textPrimary,
      fontFamily: theme.fontSans,
      fontSize: 13,
      lineHeight: 19,
      textAlign: 'right',
      minWidth: 0,
    },
    alerts: {
      gap: spacing.sm,
    },
    detailError: {
      minWidth: 0,
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: spacing.sm,
      borderWidth: 1,
      borderColor: theme.error,
      borderRadius: 8,
      backgroundColor: theme.errorBg,
      padding: spacing.md,
    },
    detailErrorTitle: {
      color: theme.error,
      fontFamily: theme.fontSansSemiBold,
      fontSize: 13,
      lineHeight: 18,
    },
    alert: {
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: spacing.sm,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      backgroundColor: theme.warningBg,
      padding: spacing.md,
    },
    alertCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    alertTitle: {
      color: theme.textPrimary,
      fontFamily: theme.fontSansSemiBold,
      fontSize: 13,
      lineHeight: 18,
    },
    alertText: {
      color: theme.textSecondary,
      fontFamily: theme.fontSans,
      fontSize: 12,
      lineHeight: 17,
    },
    tabsContent: {
      flexGrow: 1,
      gap: spacing.xs,
      paddingBottom: spacing.xs,
    },
    tab: {
      minHeight: 38,
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 999,
      backgroundColor: theme.bgMuted,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
    },
    tabSelected: {
      borderColor: theme.primary,
      backgroundColor: theme.primary,
    },
    tabText: {
      color: theme.textSecondary,
      fontFamily: theme.fontSansSemiBold,
      fontSize: 12,
      lineHeight: 17,
    },
    tabTextSelected: {
      color: theme.textOnPrimary,
    },
    tabPanel: {
      minWidth: 0,
      gap: spacing.md,
    },
    editor: {
      minWidth: 0,
      gap: spacing.md,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: spacing.md,
    },
    sectionHeaderCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    sectionTitle: {
      color: theme.textPrimary,
      fontFamily: theme.fontSansBold,
      fontSize: 15,
      lineHeight: 21,
    },
    hint: {
      color: theme.textMuted,
      fontFamily: theme.fontSans,
      fontSize: 13,
      lineHeight: 19,
    },
    assignmentBox: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      backgroundColor: theme.bgMuted,
      padding: spacing.md,
      gap: spacing.md,
      position: 'relative',
      zIndex: 10,
    },
    assignmentSummary: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: spacing.md,
    },
    assignmentIcon: {
      width: 34,
      height: 34,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primaryAlpha12,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    assignmentCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    assignmentName: {
      color: theme.textPrimary,
      fontFamily: theme.fontSansBold,
      fontSize: 14,
      lineHeight: 20,
    },
    assignmentMeta: {
      color: theme.textSecondary,
      fontFamily: theme.fontSans,
      fontSize: 12,
      lineHeight: 17,
    },
    assignmentReason: {
      color: theme.textMuted,
      fontFamily: theme.fontSans,
      fontSize: 12,
      lineHeight: 17,
      marginTop: spacing.xs,
    },
    assignmentEmpty: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      borderWidth: 1,
      borderColor: theme.borderLight,
      borderRadius: 8,
      backgroundColor: theme.bgCard,
      padding: spacing.md,
    },
    assignmentForm: {
      gap: spacing.md,
      position: 'relative',
      zIndex: 20,
    },
    assignmentActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
      gap: spacing.sm,
    },
    historyBox: {
      borderTopWidth: 1,
      borderTopColor: theme.borderLight,
      paddingTop: spacing.md,
      gap: spacing.md,
    },
    nextSessionCard: {
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
      borderWidth: 1,
      borderColor: theme.focus,
      borderRadius: 10,
      backgroundColor: theme.primaryAlpha12,
      padding: spacing.md,
    },
    nextSessionCardEmpty: {
      borderColor: theme.borderLight,
      backgroundColor: theme.bgMuted,
    },
    nextSessionIcon: {
      width: 38,
      height: 38,
      flexShrink: 0,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      backgroundColor: theme.bgCard,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    nextSessionCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    nextSessionDate: {
      color: theme.textPrimary,
      fontFamily: theme.fontSansBold,
      fontSize: 15,
      lineHeight: 21,
    },
    historyState: {
      gap: spacing.sm,
      alignItems: 'flex-start',
    },
    historyList: {
      gap: spacing.sm,
    },
    sessionGroup: {
      gap: spacing.sm,
    },
    sessionGroupTitle: {
      color: theme.textSecondary,
      fontFamily: theme.fontSansSemiBold,
      fontSize: 12,
      lineHeight: 17,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    historyItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
      borderWidth: 1,
      borderColor: theme.borderLight,
      borderRadius: 8,
      backgroundColor: theme.bgMuted,
      padding: spacing.md,
    },
    historyMarker: {
      width: 30,
      height: 30,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    historyCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    sessionTitleRow: {
      minWidth: 0,
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
    },
    sessionStatusBadge: {
      flexShrink: 0,
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: spacing.sm,
      paddingVertical: 3,
    },
    sessionStatusText: {
      fontFamily: theme.fontSansSemiBold,
      fontSize: 11,
      lineHeight: 15,
    },
    historyName: {
      color: theme.textPrimary,
      fontFamily: theme.fontSansBold,
      fontSize: 13,
      lineHeight: 19,
    },
    historyMeta: {
      color: theme.textSecondary,
      fontFamily: theme.fontSans,
      fontSize: 12,
      lineHeight: 17,
    },
    historyActor: {
      color: theme.textMuted,
      fontFamily: theme.fontSans,
      fontSize: 11,
      lineHeight: 16,
      marginTop: spacing.xs,
    },
    message: {
      fontFamily: theme.fontSansSemiBold,
      fontSize: 13,
      lineHeight: 19,
    },
    actions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      justifyContent: 'flex-end',
    },
  });

export const createFormStyles = (theme: Theme) =>
  StyleSheet.create({
    panel: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      backgroundColor: theme.bgCard,
      padding: spacing.lg,
      gap: spacing.lg,
    },
    header: {
      gap: spacing.xs,
    },
    title: {
      color: theme.textPrimary,
      fontFamily: theme.fontSansBold,
      fontSize: 20,
      lineHeight: 26,
    },
    subtitle: {
      color: theme.textSecondary,
      fontFamily: theme.fontSans,
      fontSize: 13,
      lineHeight: 19,
    },
    fields: {
      gap: spacing.xs,
    },
    groupTitle: {
      color: theme.textPrimary,
      fontFamily: theme.fontSansBold,
      fontSize: 14,
      lineHeight: 20,
      marginBottom: spacing.xs,
    },
    billingCopyControl: {
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: spacing.sm,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      backgroundColor: theme.bgMuted,
      padding: spacing.md,
      marginBottom: spacing.md,
    },
    billingCopyControlSelected: {
      borderColor: theme.focus,
      backgroundColor: theme.primaryAlpha12,
    },
    billingCopyControlDisabled: {
      opacity: 0.6,
    },
    billingCopyCheckbox: {
      width: 22,
      height: 22,
      flexShrink: 0,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: theme.border,
      borderRadius: 6,
      backgroundColor: theme.bgCard,
    },
    billingCopyCheckboxSelected: {
      borderColor: theme.actionPrimary,
      backgroundColor: theme.actionPrimary,
    },
    billingCopyText: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    billingCopyLabel: {
      color: theme.textPrimary,
      fontFamily: theme.fontSansSemiBold,
      fontSize: 14,
      lineHeight: 20,
    },
    billingCopyDescription: {
      color: theme.textSecondary,
      fontFamily: theme.fontSans,
      fontSize: 12,
      lineHeight: 18,
    },
    message: {
      fontFamily: theme.fontSansSemiBold,
      fontSize: 13,
      lineHeight: 19,
    },
    actions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
      gap: spacing.sm,
    },
  });
