import { StyleSheet } from 'react-native';
import { spacing } from '../../../constants/colors';
import type { Theme } from '../../../constants/theme';

export const professionalHomeSmallStyles = StyleSheet.create({
  statusPill: { borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4 },
  statusText: { fontSize: 9 },
  metric: { flex: 1 },
  metricValue: { fontSize: 22, letterSpacing: -0.4 },
  metricLabel: { fontSize: 10, marginTop: 2 },
  infoLine: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 28 },
  infoLabel: { flex: 1, fontSize: 11 },
  infoValue: { fontSize: 11 },
  textLink: { minHeight: 34, flexDirection: 'row', alignItems: 'center', gap: 4 },
  textLinkLabel: { fontSize: 11 },
  attentionItem: { minHeight: 46, borderRadius: 13, borderWidth: 1, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 8 },
  attentionIcon: { width: 32, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  attentionCount: { minWidth: 28, height: 28, borderRadius: 9, borderWidth: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  attentionValue: { fontSize: 16 },
  attentionTitle: { flex: 1, minWidth: 0, fontSize: 11 },
  attentionAction: { fontSize: 10 },
});

export const createProfessionalHomeStyles = (theme: Theme, mobile: boolean) => StyleSheet.create({
  screen: { flex: 1 },
  scrollContent: { width: '100%', maxWidth: 1360, alignSelf: 'center', padding: mobile ? spacing.md : spacing.xl, paddingBottom: 48 },
  loadingScreen: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  loadingMark: { width: 48, height: 48, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  loadingText: { fontSize: 13 },
  errorTitle: { fontSize: 22 },
  pageHeader: { flexDirection: mobile ? 'column' : 'row', alignItems: mobile ? 'flex-start' : 'flex-end', justifyContent: 'space-between', gap: 12, marginBottom: 22 },
  headerCopy: { flex: 1 },
  kicker: { fontSize: 10, letterSpacing: 1.4, marginBottom: 7 },
  greeting: { fontSize: mobile ? 28 : 36, letterSpacing: -0.8 },
  date: { fontSize: 11, textTransform: 'capitalize', marginBottom: 4 },
  errorBanner: { minHeight: 46, borderRadius: 13, borderWidth: 1, paddingHorizontal: 13, marginBottom: 14, flexDirection: 'row', alignItems: 'center', gap: 9 },
  errorBannerText: { flex: 1, fontSize: 11 },
  retryLink: { paddingVertical: 8 },
  retryText: { fontSize: 11 },
  priorityGrid: { flexDirection: 'row', alignItems: 'stretch', gap: 18, marginBottom: 18 },
  priorityGridStacked: { flexDirection: 'column' },
  priorityColumn: { flex: 1, minWidth: 0 },
  hero: { flex: 1, minHeight: mobile ? 250 : 218, borderRadius: mobile ? 22 : 24, borderWidth: 1, padding: mobile ? 20 : 22, shadowColor: theme.shadowStrong, shadowOffset: { width: 0, height: 14 }, shadowOpacity: 0.16, shadowRadius: 30, elevation: 8 },
  emptyHero: { minHeight: mobile ? 230 : 218, flexDirection: mobile ? 'column' : 'row', alignItems: mobile ? 'flex-start' : 'center', gap: 18 },
  heroIcon: { width: 54, height: 54, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  emptyHeroCopy: { flex: 1 },
  emptyHeroTitle: { fontSize: 24, marginVertical: 5 },
  heroEyebrow: { fontSize: 9, letterSpacing: 1.2 },
  heroMeta: { fontSize: 12, lineHeight: 18, maxWidth: 620 },
  heroTopline: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  livePill: { minHeight: 26, borderRadius: 999, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 6 },
  liveDot: { width: 6, height: 6, borderRadius: 3 },
  liveText: { fontSize: 9, letterSpacing: 0.8 },
  heroOrigin: { fontSize: 10 },
  heroBody: { flex: 1, flexDirection: mobile ? 'column' : 'row', alignItems: mobile ? 'flex-start' : 'center', gap: mobile ? 12 : 18, paddingTop: 18 },
  heroTimeBlock: { minWidth: mobile ? 112 : 96 },
  heroTime: { fontSize: mobile ? 38 : 42, letterSpacing: -1.5 },
  heroDuration: { fontSize: 11, marginTop: 1 },
  heroDivider: { width: mobile ? '100%' : 1, height: mobile ? 1 : 56, backgroundColor: theme.landingCtaMutedText, opacity: 0.3 },
  heroPatientBlock: { flex: 1, minWidth: 0 },
  heroPatient: { fontSize: mobile ? 23 : 24, letterSpacing: -0.5 },
  heroMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 7 },
  heroMetaLight: { fontSize: 11 },
  heroActions: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  lightButton: { backgroundColor: theme.bgElevated, borderColor: theme.bgElevated },
  activationHero: { minHeight: 164, borderRadius: 26, borderWidth: 1, padding: 24, flexDirection: mobile ? 'column' : 'row', alignItems: mobile ? 'flex-start' : 'center', gap: 18 },
  activationOrb: { width: 58, height: 58, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  activationCopy: { flex: 1 },
  activationTitle: { fontSize: 25, marginVertical: 5 },
  activationActions: { flexDirection: mobile ? 'column' : 'row', gap: 7, alignSelf: mobile ? 'stretch' : 'auto' },
  mainGrid: { flexDirection: 'row', alignItems: 'stretch', gap: 18, marginBottom: 18 },
  mainGridStacked: { flexDirection: 'column' },
  mainColumn: { flex: 1, minWidth: 0 },
  stackedColumn: { width: '100%' },
  sectionCard: { flex: 1, minHeight: mobile ? 0 : 360, borderRadius: 21, borderWidth: 1, padding: mobile ? 16 : 20, shadowColor: theme.shadowCard, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 1, shadowRadius: 18, elevation: 2 },
  sectionHeading: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10, marginBottom: 16 },
  sectionHeadingCopy: { flex: 1 },
  sectionTitle: { fontSize: 21, letterSpacing: -0.35 },
  sectionSubtitle: { fontSize: 10, marginTop: 4 },
  sectionEmpty: { flex: 1, minHeight: 220, alignItems: 'center', justifyContent: 'center', gap: 12 },
  emptyLineIcon: { width: 48, height: 48, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  emptyLineCopy: { alignItems: 'center', maxWidth: 360 },
  emptyLineTitle: { fontSize: 13 },
  emptyLineText: { fontSize: 11, lineHeight: 17, marginTop: 4, textAlign: 'center' },
  timelineRow: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: mobile ? 8 : 12 },
  timelineRail: { alignSelf: 'stretch', width: 12, alignItems: 'center' },
  timelineDot: { width: 8, height: 8, borderRadius: 4, marginTop: 28 },
  timelineLine: { width: 1, flex: 1, marginTop: 4 },
  timelineTime: { width: 48, fontSize: 16 },
  timelineCopy: { flex: 1, minWidth: 0 },
  timelineName: { fontSize: 12 },
  timelineMeta: { fontSize: 9, marginTop: 3 },
  pulseStats: { flexDirection: 'row', gap: 10, marginBottom: 18 },
  weekChart: { height: 108, flexDirection: 'row', alignItems: 'flex-end', gap: 7, marginBottom: 15 },
  dayBarColumn: { flex: 1, height: '100%', alignItems: 'center', justifyContent: 'flex-end', gap: 5 },
  dayBarTrack: { width: '100%', maxWidth: 25, flex: 1, borderRadius: 6, overflow: 'hidden', justifyContent: 'flex-end' },
  dayBar: { width: '100%', borderRadius: 6 },
  dayLabel: { fontSize: 9 },
  pulseInfo: { borderTopWidth: 1, paddingTop: 12, gap: 2 },
  linkRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 8 },
  attentionCard: { flex: 1, minHeight: mobile ? 0 : 218, borderRadius: 21, borderWidth: 1, padding: mobile ? 16 : 18 },
  attentionHeading: { flexDirection: mobile ? 'column' : 'row', alignItems: mobile ? 'flex-start' : 'center', justifyContent: 'space-between', gap: 10, marginBottom: 12 },
  clearPill: { borderRadius: 999, paddingHorizontal: 10, minHeight: 30, flexDirection: 'row', alignItems: 'center', gap: 5 },
  clearText: { fontSize: 10 },
  automationSummary: { flex: 1, minHeight: 54, borderRadius: 14, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 10 },
  automationText: { flex: 1, fontSize: 11, lineHeight: 17 },
  attentionGrid: { flexDirection: 'column', gap: 7 },
});

export type ProfessionalHomeStyles = ReturnType<typeof createProfessionalHomeStyles>;
