import { Client, ProfessionalStats, ProfessionalSession } from '../constants/types';

/**
 * Mock statistics for professional dashboard
 */
export const mockProfessionalStats: ProfessionalStats = {
  totalClients: 24,
  sessionsThisWeek: 12,
  averageRating: 4.8,
  pendingAppointments: 3,
};

/**
 * Mock clients/patients data
 */
export const mockClients: Client[] = [
  {
    id: 'client-1',
    name: 'María González',
    initial: 'MG',
    email: 'maria.gonzalez@email.com',
    phone: '+34 600 123 456',
    lastSession: new Date('2025-10-18'),
    nextSession: new Date('2025-10-25'),
    totalSessions: 8,
    status: 'active',
    notes: 'Progreso notable en manejo de ansiedad',
  },
  {
    id: 'client-2',
    name: 'Carlos Ruiz',
    initial: 'CR',
    email: 'carlos.ruiz@email.com',
    phone: '+34 611 234 567',
    lastSession: new Date('2025-10-19'),
    nextSession: new Date('2025-10-26'),
    totalSessions: 5,
    status: 'active',
    notes: 'Trabajando en técnicas de mindfulness',
  },
  {
    id: 'client-3',
    name: 'Ana Martínez',
    initial: 'AM',
    email: 'ana.martinez@email.com',
    phone: '+34 622 345 678',
    lastSession: new Date('2025-10-17'),
    nextSession: new Date('2025-10-24'),
    totalSessions: 12,
    status: 'active',
    notes: 'Sesiones enfocadas en terapia cognitivo-conductual',
  },
  {
    id: 'client-4',
    name: 'Javier López',
    initial: 'JL',
    email: 'javier.lopez@email.com',
    phone: '+34 633 456 789',
    lastSession: new Date('2025-10-20'),
    totalSessions: 3,
    status: 'active',
    notes: 'Cliente nuevo, estableciendo objetivos terapéuticos',
  },
  {
    id: 'client-5',
    name: 'Laura Sánchez',
    initial: 'LS',
    email: 'laura.sanchez@email.com',
    lastSession: new Date('2025-09-15'),
    totalSessions: 15,
    status: 'inactive',
    notes: 'Completó ciclo terapéutico, alta voluntaria',
  },
  {
    id: 'client-6',
    name: 'Pedro Fernández',
    initial: 'PF',
    email: 'pedro.fernandez@email.com',
    phone: '+34 644 567 890',
    totalSessions: 0,
    status: 'pending',
    notes: 'Solicitud recibida, pendiente de primera sesión',
  },
  {
    id: 'client-7',
    name: 'Isabel Torres',
    initial: 'IT',
    email: 'isabel.torres@email.com',
    phone: '+34 655 678 901',
    lastSession: new Date('2025-10-16'),
    nextSession: new Date('2025-10-23'),
    totalSessions: 6,
    status: 'active',
    notes: 'Terapia de pareja en progreso',
  },
  {
    id: 'client-8',
    name: 'Roberto García',
    initial: 'RG',
    email: 'roberto.garcia@email.com',
    phone: '+34 666 789 012',
    lastSession: new Date('2025-10-21'),
    nextSession: new Date('2025-10-28'),
    totalSessions: 10,
    status: 'active',
    notes: 'Manejo de estrés laboral',
  },
];

/**
 * Mock sessions from professional's perspective
 */
export const mockProfessionalSessions: ProfessionalSession[] = [
  // Upcoming sessions
  {
    id: 'session-1',
    clientId: 'client-1',
    clientName: 'María González',
    clientInitial: 'MG',
    date: new Date('2025-10-23T10:00:00'),
    duration: 60,
    status: 'scheduled',
    type: 'video',
    meetingLink: 'https://meet.mindconnect.com/session-1',
  },
  {
    id: 'session-2',
    clientId: 'client-3',
    clientName: 'Ana Martínez',
    clientInitial: 'AM',
    date: new Date('2025-10-23T15:00:00'),
    duration: 60,
    status: 'scheduled',
    type: 'video',
    meetingLink: 'https://meet.mindconnect.com/session-2',
  },
  {
    id: 'session-3',
    clientId: 'client-7',
    clientName: 'Isabel Torres',
    clientInitial: 'IT',
    date: new Date('2025-10-23T17:00:00'),
    duration: 90,
    status: 'scheduled',
    type: 'video',
    meetingLink: 'https://meet.mindconnect.com/session-3',
    notes: 'Sesión de pareja',
  },
  {
    id: 'session-4',
    clientId: 'client-2',
    clientName: 'Carlos Ruiz',
    clientInitial: 'CR',
    date: new Date('2025-10-24T11:00:00'),
    duration: 60,
    status: 'scheduled',
    type: 'video',
    meetingLink: 'https://meet.mindconnect.com/session-4',
  },
  {
    id: 'session-5',
    clientId: 'client-1',
    clientName: 'María González',
    clientInitial: 'MG',
    date: new Date('2025-10-25T10:00:00'),
    duration: 60,
    status: 'scheduled',
    type: 'video',
    meetingLink: 'https://meet.mindconnect.com/session-5',
  },
  {
    id: 'session-6',
    clientId: 'client-2',
    clientName: 'Carlos Ruiz',
    clientInitial: 'CR',
    date: new Date('2025-10-26T11:00:00'),
    duration: 60,
    status: 'scheduled',
    type: 'video',
    meetingLink: 'https://meet.mindconnect.com/session-6',
  },
  {
    id: 'session-7',
    clientId: 'client-8',
    clientName: 'Roberto García',
    clientInitial: 'RG',
    date: new Date('2025-10-28T09:00:00'),
    duration: 60,
    status: 'scheduled',
    type: 'video',
    meetingLink: 'https://meet.mindconnect.com/session-7',
  },

  // Pending sessions (awaiting confirmation)
  {
    id: 'session-pending-1',
    clientId: 'client-6',
    clientName: 'Pedro Fernández',
    clientInitial: 'PF',
    date: new Date('2025-10-29T10:00:00'),
    duration: 60,
    status: 'pending',
    type: 'video',
    notes: 'Primera sesión - evaluación inicial',
  },
  {
    id: 'session-pending-2',
    clientId: 'client-4',
    clientName: 'Javier López',
    clientInitial: 'JL',
    date: new Date('2025-10-30T16:00:00'),
    duration: 60,
    status: 'pending',
    type: 'video',
    notes: 'Solicita cambio de horario',
  },
  {
    id: 'session-pending-3',
    clientId: 'client-7',
    clientName: 'Isabel Torres',
    clientInitial: 'IT',
    date: new Date('2025-10-31T15:00:00'),
    duration: 90,
    status: 'pending',
    type: 'video',
    notes: 'Sesión adicional solicitada',
  },

  // History (completed sessions)
  {
    id: 'session-hist-1',
    clientId: 'client-8',
    clientName: 'Roberto García',
    clientInitial: 'RG',
    date: new Date('2025-10-21T09:00:00'),
    duration: 60,
    status: 'completed',
    type: 'video',
    notes: 'Revisión de técnicas de respiración',
  },
  {
    id: 'session-hist-2',
    clientId: 'client-4',
    clientName: 'Javier López',
    clientInitial: 'JL',
    date: new Date('2025-10-20T16:00:00'),
    duration: 60,
    status: 'completed',
    type: 'video',
    notes: 'Tercera sesión - establecimiento de objetivos',
  },
  {
    id: 'session-hist-3',
    clientId: 'client-2',
    clientName: 'Carlos Ruiz',
    clientInitial: 'CR',
    date: new Date('2025-10-19T11:00:00'),
    duration: 60,
    status: 'completed',
    type: 'video',
    notes: 'Práctica de mindfulness',
  },
  {
    id: 'session-hist-4',
    clientId: 'client-1',
    clientName: 'María González',
    clientInitial: 'MG',
    date: new Date('2025-10-18T10:00:00'),
    duration: 60,
    status: 'completed',
    type: 'video',
    notes: 'Manejo de ansiedad - ejercicios cognitivos',
  },
  {
    id: 'session-hist-5',
    clientId: 'client-3',
    clientName: 'Ana Martínez',
    clientInitial: 'AM',
    date: new Date('2025-10-17T15:00:00'),
    duration: 60,
    status: 'completed',
    type: 'video',
    notes: 'TCC - reestructuración cognitiva',
  },
  {
    id: 'session-hist-6',
    clientId: 'client-7',
    clientName: 'Isabel Torres',
    clientInitial: 'IT',
    date: new Date('2025-10-16T17:00:00'),
    duration: 90,
    status: 'completed',
    type: 'video',
    notes: 'Sesión de pareja - comunicación asertiva',
  },
];
