import { useCollaborationClock } from './useCollaborationClock';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text as NativeText, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { SimpleDropdown } from '../../components/common/SimpleDropdown';
import { ReferralLoadError, ReferralPagination, controlStyles } from '../referrals/ReferralControls';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import * as Crypto from 'expo-crypto';
import { WorkflowButton as Button, WorkflowHeader, WorkflowHeading, WorkflowColumns, WorkflowEmpty, WorkflowBadge, WorkflowHint, workflow } from '../referrals/WorkflowUI';
import { useAuth } from '../../contexts/AuthContext';
import { useTheme } from '../../contexts/ThemeContext';
import { getErrorMessage } from '../../constants/errors';
import type { AppNavigationProp, RootStackParamList } from '../../constants/types';
import * as service from '../../services/collaborationService';
import { ReferralPatientSelector } from '../referrals/ReferralPatientSelector';
import { rememberCollaborationIntent, clearPendingCollaborationIntent } from '../../services/pendingReferralIntent';
import { ReferralCard as Card, ReferralText as Text, ReferralField as Field, dateTime, styles } from '../referrals/ReferralElements';
import { CollaborationAgreement, CollaborationTermsForm, type CollaborationRun } from './CollaborationAgreement';
import { CollaborationSessions } from './CollaborationSessions';
import { CollaborationPeriods } from './CollaborationPeriods';

function CollaborationPatients({ collaboration }: { collaboration: service.Collaboration }) {
  const navigation = useNavigation<AppNavigationProp>(); const [page, setPage] = useState(0); const [data, setData] = useState<service.Page<service.CollaborationPatient>>({ items: [], hasMore: false });
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const generation = useRef(0);
  const version = collaboration.versions.find(v => v.status === 'ACCEPTED' && new Date(v.validFrom) <= new Date() && new Date(v.validUntil) > new Date());
  const load = useCallback(async () => { const current = ++generation.current; setLoading(true); setError(''); try { const rows = await service.listPatients(collaboration.id, page); if (current === generation.current) setData(rows); } catch (err) { if (current === generation.current) setError(getErrorMessage(err, 'No se pudieron cargar las incorporaciones.')); } finally { if (current === generation.current) setLoading(false); } }, [collaboration.id, page]);
  useEffect(() => { void load(); return () => { generation.current++; }; }, [load]);
  return <><WorkflowHeader title="Pacientes incorporados" subtitle="El acuerdo se aplica a incorporaciones autorizadas y aceptadas. Los pacientes que B ya atendía quedan fuera del reparto." />
    {collaboration.role === 'ORIGIN' && version && !collaboration.terminatedAt ? <Card style={{ zIndex: 1 }}><Text title>Proponer una incorporación</Text><ReferralPatientSelector onSelect={clientId => navigation.navigate('Referrals', { clientId, agreementVersionId: version.id })} /></Card> : null}
    {loading ? <ActivityIndicator accessibilityLabel="Cargando incorporaciones" /> : null}{error ? <><Text error>{error}</Text><Button onPress={() => void load()}>Reintentar</Button></> : null}{!loading && !error && !data.items.length ? <WorkflowEmpty icon="people-outline" title="Aún no hay incorporaciones" description="Los pacientes aparecerán cuando hayan autorizado la propuesta y el receptor haya aceptado el caso." /> : null}
    {data.items.map(patient => <Card key={patient.id}><Text>Referencia {patient.referralId.slice(-8)} · Incorporación aceptada el {dateTime(patient.activatedAt)}</Text><Button variant="outline" onPress={() => navigation.navigate('Referrals', { id: patient.referralId })}>Abrir incorporación autorizada</Button>{collaboration.role === 'RECIPIENT' ? <Button variant="ghost" onPress={() => navigation.navigate('ClientProfile', { clientId: patient.clientId })}>Abrir mi ficha del paciente</Button> : null}</Card>)}
    {!error && (data.items.length > 0 || page > 0) ? <ReferralPagination page={page} hasMore={data.hasMore} loading={loading} onChange={setPage} /> : null}</>;
}

function CollaborationDetail({ id, onBack, onOpen, run, busy }: { id: string; onBack: () => void; onOpen: (id: string) => void; run: CollaborationRun; busy: boolean }) {
  const [data, setData] = useState<service.Collaboration | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [tab, setTab] = useState('agreement'); const generation = useRef(0);
  const load = useCallback(async () => { const current = ++generation.current; setLoading(true); setError(''); try { const detail = await service.getCollaboration(id); if (generation.current === current) setData(detail); } catch (err) { if (generation.current === current) setError(getErrorMessage(err, 'No se pudo cargar el acuerdo.')); } finally { if (generation.current === current) setLoading(false); } }, [id]);
  useEffect(() => { void load(); return () => { generation.current++; }; }, [load]);
  const runAndRefresh: CollaborationRun = async (values, action) => { const success = await run(values, action); if (success) await load(); return success; };
  return <><View style={styles.row}><Button variant="ghost" onPress={onBack}>Volver a colaboradores</Button><Button variant="ghost" onPress={() => void load()} disabled={busy}>Actualizar</Button></View>{loading && !data ? <ActivityIndicator accessibilityLabel="Cargando colaboración" /> : null}{error ? <Text error>{error}</Text> : null}
    {data ? <><View style={styles.row}>{[['agreement', 'Acuerdo'], ['patients', 'Pacientes'], ['sessions', 'Sesiones y cobros'], ['periods', 'Liquidaciones']].map(([key, label]) => <Button key={key} accessibilityRole="tab" accessibilityState={{ selected: tab === key }} disabled={busy} variant={tab === key ? 'secondary' : 'ghost'} onPress={() => setTab(key)}>{label}</Button>)}</View>
      {data.deliveries.length ? <Card><Text>{data.deliveries.some(d => d.status === 'FAILED') ? 'Hay avisos por correo fallidos. El acuerdo y sus registros están guardados.' : 'Hay avisos por correo pendientes.'}</Text>{data.deliveries.some(d => d.status === 'FAILED') ? <Button variant="outline" disabled={busy} onPress={() => void runAndRefresh({ action: 'RETRY_NOTIFICATIONS', id }, () => service.retryNotifications(id))}>Reintentar avisos</Button> : null}</Card> : null}
      {tab === 'agreement' ? <CollaborationAgreement onOpen={onOpen} collaboration={data} busy={busy} run={runAndRefresh} /> : tab === 'patients' ? <CollaborationPatients collaboration={data} /> : tab === 'sessions' ? <CollaborationSessions collaboration={data} busy={busy} run={run} /> : <CollaborationPeriods collaboration={data} busy={busy} run={run} />}
    </> : null}</>;
}

export function CollaborationsScreen({ route, navigation }: NativeStackScreenProps<RootStackParamList, 'Collaborations'>) {
  const { isAuthenticated, user } = useAuth(); const { theme } = useTheme(); const id = route.params?.id;
  const [page, setPage] = useState(0); const [status, setStatus] = useState<string>(); const [data, setData] = useState<Awaited<ReturnType<typeof service.listCollaborations>> | null>(null); const [loading, setLoading] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [creating, setCreating] = useState(false); const [email, setEmail] = useState('');
  const now = useCollaborationClock(data?.items.map(item => item.terminatedAt) ?? []);
  const generation = useRef(0); const submitting = useRef(false); const commands = useRef(new Map<string, string>()); const scroll = useRef<ScrollView>(null);
  const load = useCallback(async () => { if (!isAuthenticated || user?.type !== 'professional' || id) return; const current = ++generation.current; setLoading(true); setError(''); try { const rows = await service.listCollaborations(page, status); if (generation.current === current) setData(rows); } catch (err) { if (generation.current === current) setError(getErrorMessage(err, 'No se pudo cargar la bandeja.')); } finally { if (generation.current === current) setLoading(false); } }, [isAuthenticated, user?.type, id, page, status]);
  useFocusEffect(useCallback(() => { void load(); return () => { generation.current++; }; }, [load]));
  const scheduledFilterExpired = status === 'ENDING' && !!data?.items.some(item => item.terminatedAt && Date.parse(item.terminatedAt) <= now);
  useEffect(() => { if (scheduledFilterExpired) void load(); }, [scheduledFilterExpired, load]);
  useEffect(() => { if (isAuthenticated && id) clearPendingCollaborationIntent(); }, [isAuthenticated, id]);
  const run: CollaborationRun = async (values, operation) => {
    if (submitting.current) return false; submitting.current = true; setBusy(true); setError('');
    const fingerprint = JSON.stringify(values); const key = commands.current.get(fingerprint) ?? Crypto.randomUUID(); commands.current.set(fingerprint, key);
    try { await operation(key); commands.current.delete(fingerprint); return true; } catch (err) { setError(getErrorMessage(err, 'No se pudo completar la operación. Puedes reintentar con los mismos datos.')); scroll.current?.scrollTo({ y: 0, animated: false }); return false; } finally { setBusy(false); submitting.current = false; }
  };
  if (!isAuthenticated) return <ScrollView contentContainerStyle={workflow.page}><Card><Text title>Tu colaboración privada</Text><Text>Accede con la cuenta profesional que recibió la invitación. La invitación no comparte datos de pacientes.</Text><Button onPress={async () => { if (id) await rememberCollaborationIntent(id); navigation.navigate('Login', { userType: 'PROFESSIONAL' }); }}>Entrar como profesional</Button></Card></ScrollView>;
  if (user?.type !== 'professional') return <ScrollView contentContainerStyle={workflow.page}><Card><Text>Esta área está disponible para las cuentas de los profesionales que participan en el acuerdo.</Text></Card></ScrollView>;
  return <ScrollView ref={scroll} style={{ backgroundColor: theme.bg }} contentContainerStyle={workflow.page} keyboardShouldPersistTaps="handled"><WorkflowHeader eyebrow="TU RED PROFESIONAL" title={creating ? "Invitar a un colaborador" : id ? "Detalle de la colaboración" : "Colaboradores"} subtitle={creating ? "Prepara los servicios, el reparto y la vigencia que revisaréis ambos." : id ? "Consulta el acuerdo y sigue las incorporaciones, sesiones y liquidaciones." : "Acuerdos entre profesionales independientes para acompañar la continuidad de la atención."} />{error && (id || creating) ? <ReferralLoadError message={error} /> : null}
    {id ? <CollaborationDetail key={id} id={id} onOpen={nextId => navigation.setParams({ id: nextId })} busy={busy} run={run} onBack={() => { setError(''); navigation.setParams({ id: undefined }); }} /> : creating ? <CollaborationTermsForm busy={busy} introduction={<><Field required label="Correo profesional del destinatario" placeholder="nombre@consulta.es" hint="Usa el correo de su cuenta profesional en HERA." value={email} onChangeText={setEmail} editable={!busy} keyboardType="email-address" autoCapitalize="none" /><WorkflowHint>El destinatario necesita una cuenta activa y verificada para aceptar. La invitación no cambia la visibilidad de su perfil.</WorkflowHint></>} onCancel={() => setCreating(false)} onSubmit={async version => { await run({ action: 'CREATE', email, version }, async key => { if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) throw new Error('Revisa el correo profesional del destinatario.'); const result = await service.createCollaboration(email.trim(), version, key); setCreating(false); navigation.setParams({ id: result.id }); }); }} /> : <>
      <View style={listStyles.toolbar}><View style={listStyles.filters}><View style={controlStyles.filter}><NativeText style={[controlStyles.label, { color: theme.textSecondary, fontFamily: theme.fontSansMedium }]}>Estado</NativeText><SimpleDropdown compact presentation="portal" accessibilityLabel="Filtrar colaboraciones por estado" options={[{ value: 'ALL', label: 'Todos los estados' }, { value: 'PENDING', label: 'Pendientes' }, { value: 'ACTIVE', label: 'Vigentes' }, { value: 'ENDING', label: 'Finalización programada' }, { value: 'TERMINATED', label: 'Finalizados' }]} value={status ?? 'ALL'} highlightSelection={!!status} onSelect={value => { setPage(0); setStatus(value === 'ALL' ? undefined : value); }} /></View>{status ? <Button size="small" variant="ghost" style={controlStyles.action} onPress={() => { setPage(0); setStatus(undefined); }}>Limpiar filtros</Button> : null}</View>{data?.eligibility.length ? <Button size="small" style={listStyles.invite} icon={<Ionicons name="add-outline" size={18} color={theme.actionPrimaryText} />} onPress={() => setCreating(true)}>Invitar a un colaborador</Button> : null}</View>
      <WorkflowHint>Cada incorporación cuenta con la autorización del paciente y la aceptación del profesional que lo atenderá.</WorkflowHint>
      {!data?.eligibility.length && data ? <Card><Text>{data.unavailableReason === 'PSYCHIATRY' ? 'En psiquiatría, las derivaciones se realizan sin reparto económico entre profesionales. Puedes proponer alternativas desde Derivaciones.' : data.unavailableReason === 'PROFESSION_REQUIRED' ? 'Indica tu tipo profesional en el perfil para consultar las opciones de colaboración disponibles.' : 'Las nuevas colaboraciones económicas no están disponibles en este momento. Tus acuerdos y liquidaciones anteriores siguen accesibles.'}</Text><Button size="small" style={controlStyles.action} variant="ghost" onPress={() => navigation.navigate('Referrals')}>Abrir derivaciones</Button></Card> : null}
      {error ? <ReferralLoadError message={error} loading={loading} onRetry={() => void load()} /> : null}
      {loading ? <ActivityIndicator accessibilityLabel="Cargando colaboradores" /> : null}{data && !loading && !error && !data.items.length ? <WorkflowColumns><WorkflowEmpty icon="people-outline" title="No hay acuerdos en esta vista" description={status ? "No hay colaboraciones con el estado seleccionado. Prueba con todos los estados." : data.eligibility.length ? "Tu red de colaboración empieza con una invitación. Los acuerdos aparecerán aquí para que puedas seguir su estado." : "Aquí se muestran tus acuerdos anteriores. En este momento no puedes crear nuevas colaboraciones económicas."} action={status ? <Button variant="outline" onPress={() => { setStatus(undefined); setPage(0); }}>Ver todos los acuerdos</Button> : undefined} /><Card><WorkflowHeading icon="git-network-outline" title="Cómo funciona" /><WorkflowHeading number="01" title="Proponéis las condiciones" subtitle="Servicios, modalidades, reparto y vigencia claros para ambas partes." /><WorkflowHeading number="02" title="Cada paciente decide" subtitle="La incorporación requiere su autorización y la aceptación del receptor." /><WorkflowHeading number="03" title="Seguís la colaboración" subtitle="Consultad sesiones, cobros declarados, facturas y liquidaciones." /></Card></WorkflowColumns> : null}
      {!loading && !error ? data?.items.map(item => <Card key={item.id}><WorkflowHeading icon="people-outline" title={item.role === "ORIGIN" ? item.recipientName : item.originName} /><WorkflowBadge label={item.terminatedAt ? Date.parse(item.terminatedAt) > now ? "Finalización programada" : "Finalizada" : item.version.status === "PROPOSED" ? "Pendiente de aceptación" : item.version.status === "ACCEPTED" ? "Versión aceptada" : "Sin versión aceptada"} /><WorkflowHint>{item.role === "ORIGIN" ? "Tú propones las incorporaciones · A" : "Tú atiendes y facturas al paciente · B"}</WorkflowHint><Text>{item.terminatedAt ? `Corte: ${dateTime(item.terminatedAt)}` : item.version.status === 'ACCEPTED' ? 'Versión aceptada por ambos' : item.version.status === 'PROPOSED' ? 'Pendiente del receptor' : 'Sin versión vigente aceptada'} · {item.version.originShareBps / 100}% para A</Text><Button variant="outline" onPress={() => navigation.setParams({ id: item.id })}>Revisar colaboración</Button></Card>) : null}
      {!error && data && (data.items.length > 0 || page > 0) ? <ReferralPagination page={page} hasMore={data.hasMore} loading={loading} onChange={setPage} /> : null}
    </>}
  </ScrollView>;
}

const listStyles = StyleSheet.create({
  toolbar: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-end', justifyContent: 'space-between', gap: 12 },
  filters: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-end', gap: 8, flexGrow: 1, flexBasis: 260 },
  invite: { minHeight: 44, borderRadius: 10, alignSelf: 'flex-end' },
});
