import React, { useEffect, useState } from 'react';
import { View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { SimpleDropdown } from '../../components/common/SimpleDropdown';
import { openPrivateDocument } from '../../utils/openPrivateDocument';
import type { UploadAsset } from '../../utils/multipartUpload';
import * as service from '../../services/heraCommissionService';
import { Card, Text, Field, Check, Button, WorkflowDate, WorkflowHint, money, dateTime, styles, cents, day, getMadridDateKey, Run } from './CommissionElements';

export function ReceiptForm({ data, selectedDocument, run, busy, onClose }: { data: service.AccountDetail; selectedDocument?: string; run: Run; busy: boolean; onClose: () => void }) {
 const [amount, setAmount] = useState(selectedDocument ? String((data.documents.find(d => d.id === selectedDocument)?.claimableCents ?? 0) / 100) : '');
 const [date, setDate] = useState(getMadridDateKey()); const [reference, setReference] = useState(''); const [confirmed, setConfirmed] = useState(false); const [unapplied, setUnapplied] = useState(false);
 const [allocations, setAllocations] = useState<Record<string, string>>(selectedDocument ? { [selectedDocument]: amount } : {});
 const documents = [...data.documents].sort((a, b) => a.dueAt.localeCompare(b.dueAt));
 const propose = () => { void run(async () => { let remaining = cents(amount); const next: Record<string, string> = {}; for (const doc of documents) { const n = Math.min(remaining, doc.claimableCents); if (n > 0) next[doc.id] = (n / 100).toFixed(2); remaining -= n; } setAllocations(next); }); };
 const totalApplied = Object.values(allocations).reduce((n, v) => n + (Number(v.replace(',', '.')) || 0), 0);
 const excess = Number(amount.replace(',', '.')) - totalApplied;
 return <Card><Text title>Registrar transferencia recibida</Text><Text>{data.summary.specialistName} · {data.summary.operatorKey} · EUR</Text><Field label="Importe realmente recibido (€)" value={amount} onChangeText={setAmount} keyboardType="decimal-pad" /><WorkflowDate label="Fecha de recepción (AAAA-MM-DD)" value={date} onChangeText={setDate} /><Field label="Referencia y nota de la transferencia" value={reference} onChangeText={setReference} multiline /><Button variant="outline" disabled={busy} onPress={propose}>Proponer reparto por vencimiento</Button>
 {documents.map(doc => <View key={doc.id} style={{ gap: 8 }}><Text>{doc.invoiceNumber} · Pendiente aplicable {money(doc.claimableCents)} · Vence {dateTime(doc.dueAt)}</Text>{doc.correctionPending ? <Text>Corrección documental pendiente. Puedes guardar dinero sin aplicar.</Text> : null}<Field label={`Aplicar a ${doc.invoiceNumber} (€)`} editable={doc.claimableCents > 0 && !busy} value={allocations[doc.id] ?? ''} onChangeText={v => setAllocations(p => ({ ...p, [doc.id]: v }))} keyboardType="decimal-pad" /></View>)}
 <Text>Reparto: {money(Math.round(totalApplied * 100))} · Sin aplicar: {Number.isFinite(excess) ? money(Math.round(excess * 100)) : 'Revisa el importe'}</Text><Check label="Confirmo que el exceso quedará como saldo sin aplicar del mismo especialista" checked={unapplied} onChange={setUnapplied} disabled={busy} /><Check label="He comprobado la recepción de esta transferencia fuera de HERA" checked={confirmed} onChange={setConfirmed} disabled={busy} />
 <View style={styles.row}><Button disabled={busy || !confirmed} onPress={() => void (async () => { if (await run(() => service.decide(data.summary.id, true, { action: 'RECEIVE', amountCents: cents(amount), occurredAt: day(date), reference, confirmed: true, allowUnapplied: unapplied, revision: data.summary.revision, applications: Object.entries(allocations).filter(([, v]) => v.trim() && cents(v) !== 0).map(([documentId, v]) => ({ documentId, amountCents: cents(v) })) }))) onClose(); })()}>Guardar recepción manual</Button><Button variant="ghost" disabled={busy} onPress={onClose}>Cerrar</Button></View></Card>;
}

export function CashOperations({ data, run, busy }: { data: service.AccountDetail; run: Run; busy: boolean }) {
 const [action, setAction] = useState('APPLY_CREDIT'); const [amount, setAmount] = useState(''); const [document, setDocument] = useState(''); const [date, setDate] = useState(getMadridDateKey()); const [reason, setReason] = useState(''); const [confirmed, setConfirmed] = useState(false);
 return <><Card><Text title>Crédito y correcciones de registro</Text><Text>Saldo disponible: {money(data.summary.creditCents)}</Text><SimpleDropdown accessibilityLabel="Operación sobre el crédito" options={[{ value: 'APPLY_CREDIT', label: 'Aplicar crédito a otro documento' }, { value: 'RETURN_CREDIT', label: 'Registrar devolución externa al especialista' }]} value={action} onSelect={setAction} /><Field label="Importe de crédito (€)" value={amount} onChangeText={setAmount} keyboardType="decimal-pad" />
 {action === 'APPLY_CREDIT' ? <SimpleDropdown accessibilityLabel="Documento de destino" options={data.documents.filter(d => d.claimableCents > 0).map(d => ({ value: d.id, label: `${d.invoiceNumber} · ${money(d.claimableCents)}` }))} value={document} onSelect={setDocument} /> : <><WorkflowDate label="Fecha de devolución externa (AAAA-MM-DD)" value={date} onChangeText={setDate} /><Field label="Referencia de la devolución externa" value={reason} onChangeText={setReason} /><Check label="He comprobado la devolución realizada fuera de HERA" checked={confirmed} onChange={setConfirmed} /></>}
 <Button disabled={busy || (action === 'RETURN_CREDIT' && !confirmed)} onPress={() => void run(() => service.decide(data.summary.id, true, action === 'APPLY_CREDIT' ? { action, documentId: document, amountCents: cents(amount), revision: data.summary.revision } : { action: 'RETURN_CREDIT', amountCents: cents(amount), occurredAt: day(date), reference: reason, confirmed: true, revision: data.summary.revision }))}>Guardar operación de crédito</Button></Card>
 <Field label="Motivo obligatorio para anular un registro o revertir una aplicación" value={reason} onChangeText={setReason} multiline />
 {data.cash.map(c => <Card key={c.id}><Text title>{c.kind === 'RECEIPT' ? 'Transferencia recibida' : c.kind === 'REVERSAL' ? 'Anulación de registro' : 'Devolución externa'}</Text><Text>{money(c.amountCents)} · {dateTime(c.occurredAt)} · {c.reference}</Text><WorkflowHint>Confirmado manualmente por HERA. Anular un registro no declara una devolución bancaria.</WorkflowHint><Text>Sin aplicar de este ingreso: {money(c.availableCents)}</Text>{c.applications.map(a => <View key={a.id} style={{ gap: 8 }}><Text>{money(a.amountCents)} → Documento {a.documentId.slice(-8)} · {a.reason}</Text>{a.amountCents > 0 ? <Button variant="ghost" disabled={busy || reason.trim().length < 3} onPress={() => void run(() => service.decide(data.summary.id, true, { action: 'REVERSE_APPLICATION', applicationId: a.id, reason }))}>Revertir aplicación por error</Button> : null}</View>)}{c.kind === 'RECEIPT' ? <Button variant="outline" disabled={busy || reason.trim().length < 3} onPress={() => void run(() => service.decide(data.summary.id, true, { action: 'VOID_RECEIPT', cashId: c.id, reason }))}>Anular registro erróneo</Button> : null}</Card>)}</>;
}

const fiscalFields: Array<[keyof service.Fiscal, string]> = [['issuerName','Nombre fiscal de HERA'],['issuerTaxId','Identificación fiscal de HERA'],['issuerAddress','Domicilio fiscal de HERA'],['recipientName','Nombre fiscal del especialista'],['recipientTaxId','Identificación fiscal del especialista'],['recipientAddress','Domicilio fiscal del especialista'],['concept','Concepto'],['taxDescription','Tratamiento del impuesto'],['withholdingDescription','Tratamiento de la retención'],['externalReference','Referencia externa del documento']];
export function DocumentForm({ data, entries, original, run, busy, onClose }: { data: service.AccountDetail; entries: service.Entry[]; original?: service.DocumentBalance; run: Run; busy: boolean; onClose: () => void }) {
 const terms = data.acceptances[0]?.terms;
 const [kind, setKind] = useState<service.Document['kind']>(original ? 'DIFFERENCE' : 'ORDINARY'); const [number, setNumber] = useState(''); const [issued, setIssued] = useState(getMadridDateKey()); const [due, setDue] = useState(getMadridDateKey());
 const selectedBase = entries.reduce((sum, e) => sum + e.baseCents, 0);
 const [base, setBase] = useState(String(selectedBase / 100)); const [tax, setTax] = useState(''); const [withholding, setWithholding] = useState(''); const [total, setTotal] = useState(''); const [file, setFile] = useState<UploadAsset>();
 const [fiscal, setFiscal] = useState<service.Fiscal>({ issuerName: terms?.operatorName ?? '', issuerTaxId: terms?.operatorTaxId ?? '', issuerAddress: terms?.operatorAddress ?? '', recipientName: data.specialistFiscal.fiscalName ?? '', recipientTaxId: data.specialistFiscal.fiscalNif ?? '', recipientAddress: data.specialistFiscal.fiscalAddress ?? '', concept: 'Comisiones HERA por pacientes del Directorio', taxDescription: '', withholdingDescription: '', externalReference: '' });
 return <Card><Text title>{original ? 'Importar rectificación externa' : 'Importar factura externa de HERA'}</Text><Text>{entries.length} líneas seleccionadas · Diferencia de base {money(selectedBase)}</Text>{original && !entries.length ? <WorkflowHint>Corrección fiscal: conserva la base de comisión. Puedes corregir impuestos, retenciones y datos del documento sin crear un nuevo devengo. En una sustitutiva, introduce los totales finales de toda la cadena.</WorkflowHint> : null}<WorkflowHint>La liquidación no es una factura. Transcribe el documento fiscal emitido fuera de HERA; los impuestos no se deducen del servicio sanitario.</WorkflowHint>
 {original ? <><Text>Documento original: {original.invoiceNumber}</Text><SimpleDropdown accessibilityLabel="Tipo de rectificación" value={kind} options={[{ value: 'DIFFERENCE', label: 'Por diferencias: importa solo el ajuste' }, { value: 'REPLACEMENT', label: 'Sustitutoria: importa el nuevo total' }]} onSelect={v => { if (v === 'DIFFERENCE' || v === 'REPLACEMENT') setKind(v); }} /></> : null}
 <Field label="Número y serie fiscal" value={number} onChangeText={setNumber} /><WorkflowDate label="Fecha de emisión (AAAA-MM-DD)" value={issued} onChangeText={setIssued} /><WorkflowDate label="Fecha de vencimiento (AAAA-MM-DD)" value={due} onChangeText={setDue} />
 {fiscalFields.map(([key, label]) => <Field key={key} label={label} value={fiscal[key]} onChangeText={v => setFiscal(p => ({ ...p, [key]: v }))} />)}
 <Field label="Base del documento (€)" value={base} onChangeText={setBase} keyboardType="decimal-pad" /><Field label="Impuestos del documento (€)" value={tax} onChangeText={setTax} keyboardType="decimal-pad" /><Field label="Retenciones del documento (€)" value={withholding} onChangeText={setWithholding} keyboardType="decimal-pad" /><Field label="Total del documento (€)" value={total} onChangeText={setTotal} keyboardType="decimal-pad" />
 <Button variant="outline" disabled={busy} onPress={() => void run(async () => { const result = await DocumentPicker.getDocumentAsync({ type: 'application/pdf', copyToCacheDirectory: true }); if (!result.canceled) { const a = result.assets[0]; setFile({ uri: a.uri, name: a.name, mimeType: a.mimeType ?? 'application/pdf', file: a.file }); } })}>{file ? `PDF: ${file.name}` : 'Seleccionar PDF privado'}</Button>
 <View style={styles.row}><Button disabled={busy || !file || (kind === 'ORDINARY' && !entries.length)} onPress={() => void (async () => { if (await run(async () => { if (!file) throw new Error('Selecciona un PDF.'); await service.upload(data.summary.id, { kind, originalId: original?.documents[original.documents.length - 1].id, invoiceNumber: number, issuedAt: day(issued), dueAt: day(due), currency: 'EUR', entryIds: entries.map(e => e.id), baseCents: cents(base), taxCents: cents(tax), withholdingCents: cents(withholding), totalCents: cents(total), fiscal }, file); })) onClose(); })()}>Guardar documento</Button><Button variant="ghost" disabled={busy} onPress={onClose}>Cerrar</Button></View></Card>;
}

export function CommissionPeriods({ data, admin, run, busy, onReceipt }: { data: service.AccountDetail; admin: boolean; run: Run; busy: boolean; onReceipt: (id: string) => void }) {
 const [selectedPeriod, setSelectedPeriod] = useState<string>(); const [page, setPage] = useState(0); const [lines, setLines] = useState<service.Page<service.Entry>>(); const [selected, setSelected] = useState<service.Entry[]>([]); const [uploading, setUploading] = useState(false); const [original, setOriginal] = useState<service.DocumentBalance>();
 const [metadata, setMetadata] = useState<service.Fiscal>();
 const [lineError, setLineError] = useState('');
 useEffect(() => { if (!selectedPeriod) return; let live = true; void service.period(data.summary.id, admin, selectedPeriod, page).then(result => { if (live) { setLines(result); setLineError(''); setSelected(s => s.filter(e => !result.items.some(line => line.id === e.id && line.documentLine))); } }).catch(() => { if (live) setLineError('No se pudieron cargar las líneas. Vuelve a seleccionar el periodo.'); }); return () => { live = false; }; }, [selectedPeriod, page, data.summary.id, data.summary.revision, admin]);
 return <>{lineError ? <Text error>{lineError}</Text> : null}<WorkflowHint>Periodos de calendario Europe/Madrid. Un cierre conserva sus líneas; las correcciones posteriores entran en un periodo abierto.</WorkflowHint>
 {data.periods.map(p => <Card key={p.id}><Text title>{p.month} · {p.status === 'CLOSED' ? 'Cerrado' : p.status === 'PREPARED' ? 'Preparado' : 'Abierto'}</Text><Text>Base de comisión: {money(p.baseCents)} · Revisión {p.revision}</Text><View style={styles.row}><Button variant="outline" disabled={busy} onPress={() => { setPage(0); setSelectedPeriod(p.id); }}>Ver líneas de {p.month}</Button>{admin && p.status !== 'CLOSED' ? <Button disabled={busy} onPress={() => void run(() => service.decide(data.summary.id, true, p.status === 'PREPARED' ? { action: 'CLOSE', periodId: p.id, revision: p.revision, baseCents: p.baseCents } : { action: 'PREPARE', periodId: p.id, revision: p.revision }))}>{p.status === 'PREPARED' ? 'Cerrar esta revisión' : 'Preparar liquidación'}</Button> : null}</View></Card>)}
 {selectedPeriod && lines ? <Card><Text title>Líneas de liquidación</Text>{lines.items.map(e => <View key={e.id} style={{ gap: 6 }}><Text>{money(e.baseCents)} · {e.reason} · {dateTime(e.economicAt)}</Text><WorkflowHint>Sesión {e.snapshot.sessionId.slice(-8)} · {e.snapshot.position ?? 'Estimación'} · {e.snapshot.rateBps === null ? 'Cálculo histórico no disponible' : `${e.snapshot.rateBps / 100}%`} · Registrado {dateTime(e.recognizedAt)}</WorkflowHint>{admin && !e.documentLine && data.periods.find(p => p.id === selectedPeriod)?.status === 'CLOSED' ? <Check label={`Seleccionar línea ${e.id.slice(-8)} (${money(e.baseCents)})`} checked={selected.some(s => s.id === e.id)} onChange={checked => setSelected(s => checked ? [...s.filter(v => v.id !== e.id), e] : s.filter(v => v.id !== e.id))} /> : e.documentLine ? <Text>Documentada</Text> : null}</View>)}<View style={styles.row}><Button variant="ghost" disabled={busy || page === 0} onPress={() => setPage(v => v - 1)}>Líneas anteriores</Button><Button variant="ghost" disabled={busy || !lines.hasMore} onPress={() => setPage(v => v + 1)}>Más líneas</Button></View></Card> : null}
 {admin && selected.length ? <Card><Text>{selected.length} líneas seleccionadas · {money(selected.reduce((n, e) => n + e.baseCents, 0))}</Text><Button disabled={busy} onPress={() => { setOriginal(undefined); setUploading(true); }}>Importar factura de estas líneas</Button><Button variant="ghost" onPress={() => setSelected([])}>Limpiar selección</Button></Card> : null}
 {uploading ? <DocumentForm key={original?.id ?? 'new'} data={data} entries={selected} original={original} run={run} busy={busy} onClose={() => setUploading(false)} /> : null}
 {data.documents.map(d => <Card key={d.id}><Text title>{d.invoiceNumber}</Text><Text>Total fiscal de la cadena {money(d.totalCents)} · Recibido/aplicado {money(d.appliedCents)} · Pendiente {money(d.remainingCents)}</Text><WorkflowHint>{d.correctionPending ? 'Corrección documental pendiente: el importe controvertido no se presenta como cantidad válida a transferir.' : `Pendiente válido para transferir: ${money(d.claimableCents)}. Vencimiento ${dateTime(d.dueAt)}.`}</WorkflowHint>
 {d.documents.map(doc => <View key={doc.id} style={{ gap: 8 }}><Text>{doc.invoiceNumber} · {doc.kind === 'ORDINARY' ? 'Factura' : doc.kind === 'DIFFERENCE' ? 'Rectificación por diferencias' : 'Rectificación sustitutiva'}</Text><Text>Base {money(doc.baseCents)} + impuestos {money(doc.taxCents)} − retenciones {money(doc.withholdingCents)} = {money(doc.totalCents)}</Text><View style={styles.row}><Button variant="ghost" disabled={busy} onPress={() => void run(async () => setMetadata(await service.fiscal(data.summary.id, admin, doc.id)))}>Datos fiscales</Button><Button variant="outline" disabled={busy || doc.storageStatus !== 'READY'} onPress={() => void run(async () => openPrivateDocument(await service.download(data.summary.id, admin, doc.id), doc.id, doc.fileName, 'application/pdf'))}>Descargar PDF privado</Button></View>{doc.storageStatus !== 'READY' ? <><Text>Falta guardar el PDF. El número y los metadatos están conservados.</Text>{admin ? <Button variant="outline" disabled={busy} onPress={() => void run(async () => { const result = await DocumentPicker.getDocumentAsync({ type: 'application/pdf', copyToCacheDirectory: true }); if (!result.canceled) { const a = result.assets[0]; await service.recoverDocument(data.summary.id, doc.id, { uri: a.uri, name: a.name, mimeType: a.mimeType ?? 'application/pdf', file: a.file }); } })}>Reintentar almacenamiento del mismo PDF</Button> : null}</> : null}</View>)}
 {admin ? <View style={styles.row}><Button disabled={busy} onPress={() => onReceipt(d.id)}>Registrar transferencia recibida</Button><Button variant="outline" disabled={busy} onPress={() => { setOriginal(d); setUploading(true); }}>{selected.length ? 'Rectificar con las líneas seleccionadas' : 'Corregir datos fiscales sin cambiar la comisión'}</Button></View> : null}</Card>)}
 {metadata ? <Card><Text title>Metadatos fiscales</Text>{fiscalFields.map(([key, label]) => <Text key={key}>{label}: {metadata[key]}</Text>)}<Button variant="ghost" onPress={() => setMetadata(undefined)}>Cerrar datos fiscales</Button></Card> : null}</>;
}

export function CommissionIssues({ data, admin, busy, run }: { data: service.AccountDetail; admin: boolean; busy: boolean; run: Run }) {
 const [origin, setOrigin] = useState<service.Origin>('UNKNOWN'); const [reason, setReason] = useState(''); const [count, setCount] = useState(''); const [date, setDate] = useState(getMadridDateKey());
 const [fromClient, setFromClient] = useState(''); const [toClient, setToClient] = useState(''); const [verified, setVerified] = useState(false);
 return <><WorkflowHint>Las revisiones usan evidencia administrativa. No incluyas diagnósticos, informes ni notas clínicas.</WorkflowHint>{admin ? <Card><Text title>Resolución y evidencia</Text><SimpleDropdown accessibilityLabel="Procedencia resuelta" value={origin} options={[{ value: 'HERA_DIRECTORY', label: 'Directorio HERA' }, { value: 'SPECIALIST_OWN', label: 'Cartera propia anterior' }, { value: 'SPECIALIST_INVITED', label: 'Invitación de cartera' }, { value: 'PROFESSIONAL_REFERRAL', label: 'Derivación asistencial' }, { value: 'COLLABORATION', label: 'Colaboración económica' }, { value: 'UNKNOWN', label: 'Pendiente de determinar' }]} onSelect={v => { const valid: service.Origin[] = ['HERA_DIRECTORY','SPECIALIST_OWN','SPECIALIST_INVITED','PROFESSIONAL_REFERRAL','COLLABORATION','UNKNOWN']; const selected = valid.find(o => o === v); if (selected) setOrigin(selected); }} /><Field label="Sesiones previas acreditadas (sin cobros ficticios)" value={count} onChangeText={setCount} keyboardType="number-pad" /><WorkflowDate label="Fecha de la evidencia original (AAAA-MM-DD)" value={date} onChangeText={setDate} /><Field label="Evidencia y motivo de resolución o diferimiento" value={reason} onChangeText={setReason} multiline /></Card> : null}
 {data.issues.map(i => <Card key={i.id}><Text title>{i.status === 'OPEN' ? 'Revisión abierta' : i.status === 'DEFERRED' ? 'Partida diferida' : 'Revisión resuelta'}</Text><Text>{i.reason}</Text>{i.resolution ? <Text>Resolución: {i.resolution}</Text> : null}{admin && i.status !== 'RESOLVED' ? <View style={styles.row}><Button disabled={busy} onPress={() => void run(() => { if (!/^\d+$/.test(count)) throw new Error('Acredita el contador inicial; no se asume cero.'); return service.decide(data.summary.id, true, { action: 'RESOLVE', issueId: i.id, origin, initialCount: Number(count), evidenceAt: day(date), reason }); })}>Resolver con esta evidencia</Button><Button variant="outline" disabled={busy} onPress={() => void run(() => service.decide(data.summary.id, true, { action: 'DEFER', issueId: i.id, reason }))}>Diferir partida de forma trazable</Button></View> : null}</Card>)}
 {admin ? <Card><Text title>Incorporación prospectiva e identidad</Text><WorkflowHint>Para incorporar una relación anterior, acredita las sesiones previas y la procedencia en el formulario de resolución. Las reservas existentes no generan deuda nueva.</WorkflowHint><Button disabled={busy || !fromClient} onPress={() => void run(() => { if (!/^\d+$/.test(count)) throw new Error('Acredita el contador inicial.'); return service.decide(data.summary.id, true, { action: 'ENROLL', clientId: fromClient, initialCount: Number(count), evidenceAt: day(date), reason }); })}>Incorporar la ficha anterior desde ahora</Button><WorkflowHint>La vinculación se realiza desde una cuenta real: afecta a identidades compartidas, no es una operación de simulación. Vincula solo si se ha acreditado la identidad de ambas fichas. No se trasladan datos clínicos ni se concede acceso por este vínculo.</WorkflowHint><Field label="Referencia de la ficha anterior" value={fromClient} onChangeText={setFromClient} /><Field label="Referencia de la ficha de destino" value={toClient} onChangeText={setToClient} /><Check label="He verificado ambas identidades con evidencia suficiente, además del correo" checked={verified} onChange={setVerified} /><Button disabled={busy || !verified || data.summary.mode === 'SIMULATION'} onPress={() => void run(() => service.decide(data.summary.id, true, { action: 'LINK_IDENTITY', fromClientId: fromClient, toClientId: toClient, verifiedBothIdentities: true, reason }))}>Vincular identidad comercial</Button></Card> : null}</>;
}
