import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ProfessionalCommissionSessionCard } from './ProfessionalCommissionSessionCard';
import { AdminCommissionSessionCard } from './AdminCommissionSessionCard';
import { ActivityIndicator, View } from 'react-native';
import { CommissionSelect } from './CommissionFields';
import { ReferralPagination } from '../referrals/ReferralControls';
import * as service from '../../services/heraCommissionService';
import { Card, Text, Field, Button, WorkflowDate, WorkflowHint, cents, day, getMadridDateKey, dateTime, money, styles, Run } from './CommissionElements';
import { getErrorMessage } from '../../constants/errors';
import { WorkflowEmpty, WorkflowHeading, workflow } from '../referrals/WorkflowUI';

function SessionForm({ row, run, admin, onDone, busy, initialAction = 'COLLECT' }: { initialAction?: 'COLLECT' | 'REVIEW'; row: service.CommissionSession; run: Run; admin: boolean; onDone: () => void; busy: boolean }) {
 const [action, setAction] = useState<string>(initialAction); const [gross, setGross] = useState('');
 const [serviceBase, setServiceBase] = useState(row.baseCents === null ? '' : String(row.baseCents / 100)); const [tax, setTax] = useState(row.serviceTaxCents === null ? '' : String(row.serviceTaxCents / 100));
 const [reference, setReference] = useState(''); const [date, setDate] = useState(getMadridDateKey()); const [original, setOriginal] = useState(''); const [outcome, setOutcome] = useState<'ATTENDED' | 'PATIENT_NO_SHOW' | 'UNCONFIRMED'>('ATTENDED');
 const save = async () => {
  if (await run(async () => {
   let input: service.Action;
   if (action === 'ATTENDANCE') input = { action, snapshotId: row.id, outcome, reason: reference };
   else if (action === 'REVIEW') input = { action, relationId: row.relationId, snapshotId: row.id, reason: reference };
   else if (action === 'REFUND') input = { action, snapshotId: row.id, originalId: original, grossCents: cents(gross), reference, occurredAt: day(date) };
   else if (action === 'CORRECT_BASE') input = { action, snapshotId: row.id, baseCents: cents(serviceBase), taxCents: cents(tax), reason: reference };
   else input = { action: 'COLLECT', snapshotId: row.id, grossCents: cents(gross), serviceBaseCents: cents(serviceBase), serviceTaxCents: cents(tax), reference, occurredAt: day(date) };
   await service.decide(row.accountId, false, input);
  })) onDone();
 };
 return <Card><Text title>{action === 'REVIEW' ? 'Solicitar revisión' : 'Actualizar sesión'}</Text><CommissionSelect accessibilityLabel="Tipo de actividad" options={admin ? [] : [{ value: 'COLLECT', label: 'Registrar cobro del paciente' }, { value: 'ATTENDANCE', label: 'Confirmar o corregir asistencia' }, { value: 'REFUND', label: 'Registrar devolución al paciente' }, { value: 'CORRECT_BASE', label: 'Corregir base e impuestos' }, { value: 'REVIEW', label: 'Solicitar revisión' }]} value={action} onSelect={setAction} />
 {action === 'ATTENDANCE' ? <CommissionSelect accessibilityLabel="Asistencia" options={[{ value: 'ATTENDED', label: 'Atendida' }, { value: 'PATIENT_NO_SHOW', label: 'El paciente no asistió' }, { value: 'UNCONFIRMED', label: 'Anular confirmación incorrecta' }]} value={outcome} onSelect={v => { if (v === 'ATTENDED' || v === 'PATIENT_NO_SHOW' || v === 'UNCONFIRMED') setOutcome(v); }} /> : null}
 {action === 'COLLECT' || action === 'CORRECT_BASE' ? <><Field label="Precio sin impuestos, después de descuentos (€)" value={serviceBase} onChangeText={setServiceBase} keyboardType="decimal-pad" /><Field label="Impuestos del servicio (€)" value={tax} onChangeText={setTax} keyboardType="decimal-pad" /></> : null}
 {action === 'COLLECT' || action === 'REFUND' ? <><Field label={action === 'COLLECT' ? 'Importe recibido del paciente (€)' : 'Importe devuelto (€)'} value={gross} onChangeText={setGross} keyboardType="decimal-pad" />{action === 'COLLECT' ? <WorkflowHint>Si el paciente ha pagado solo una parte, se genera la parte proporcional de la comisión.</WorkflowHint> : <CommissionSelect accessibilityLabel="Cobro original" options={row.movements.filter(m => m.kind === 'COLLECTION').map(m => ({ value: m.id, label: `${dateTime(m.occurredAt)} · ${money(m.grossCents)}` }))} value={original} onSelect={setOriginal} />}<WorkflowDate label="Fecha del movimiento" value={date} onChangeText={setDate} /></> : null}
 <Field label={action === 'COLLECT' || action === 'REFUND' ? 'Referencia del pago o de la devolución' : 'Explicación (sin información clínica)'} value={reference} onChangeText={setReference} multiline />
 <WorkflowHint>{action === 'REVIEW' ? 'Explica qué necesitas revisar. Podrás consultar la respuesta de HERA en «Revisiones».' : 'Aquí registras lo que has cobrado al paciente. Los pagos de tus comisiones se consultan en «Abonos a HERA».'}</WorkflowHint><View style={styles.row}><Button disabled={busy} onPress={() => void save()}>{action === 'REVIEW' ? 'Enviar solicitud de revisión' : 'Guardar actividad'}</Button><Button variant="ghost" disabled={busy} onPress={onDone}>Cerrar</Button></View></Card>;
}
export function CommissionSessions({ accountId, admin, clientId, run, busy, refresh, account, onPeriods }: { account?: service.AccountDetail; onPeriods?: () => void; accountId: string; admin: boolean; clientId?: string; run: Run; busy: boolean; refresh: number }) {
 const [filtersOpen, setFiltersOpen] = useState(false);
 const [page, setPage] = useState(0); const [month, setMonth] = useState(''); const [patientId, setPatientId] = useState(clientId ?? ''); const [state, setState] = useState('ALL'); const [review, setReview] = useState(false);
 const [data, setData] = useState<service.Page<service.CommissionSession>>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [selected, setSelected] = useState<{ id: string; action: 'COLLECT' | 'REVIEW' }>(); const generation = useRef(0);
 const load = useCallback(async () => { const g = ++generation.current; setLoading(true); setError(''); setData(undefined); try { const result = await service.sessions(accountId, admin, { page, month: month || undefined, clientId: patientId || undefined, state: state === 'ALL' ? undefined : state, review }); if (g === generation.current) setData(result); } catch(e) { if (g === generation.current) setError(getErrorMessage(e, 'No se pudo cargar el desglose.')); } finally { if (g === generation.current) setLoading(false); } }, [accountId, admin, page, month, patientId, state, review, refresh]);
 useEffect(() => { void load(); return () => { generation.current++; }; }, [load]);
 const filterCount = Number(!!month) + Number(!!patientId) + Number(state !== 'ALL') + Number(review);
 return <><Card style={{ padding: 16, gap: 12 }}><WorkflowHeading icon="calendar-outline" title={admin ? "Sesiones y comisiones" : "Tus sesiones y comisiones"} subtitle={admin ? "Consulta el pago y la factura por separado. Registra pagos recibidos desde «Abonos a HERA»." : "Registra los cobros de estas sesiones para calcular la comisión HERA. El pago del paciente se realiza fuera de esta pantalla."} />{<View style={styles.row}><Button variant="outline" size="small" accessibilityLabel="Filtrar sesiones" accessibilityState={{ expanded: filtersOpen }} onPress={() => setFiltersOpen(v => !v)}>{filtersOpen ? 'Ocultar filtros' : 'Filtrar sesiones'}{filterCount ? ` · ${filterCount} ${filterCount === 1 ? 'activo' : 'activos'}` : ''}</Button>{filterCount ? <Button variant="ghost" size="small" onPress={() => { setMonth(''); setPatientId(''); setState('ALL'); setReview(false); setPage(0); }}>Limpiar filtros</Button> : null}</View>}{filtersOpen ? <><View style={workflow.fieldRow}><View style={workflow.field}><WorkflowDate label="Mes de liquidación" granularity="month" value={month} onChangeText={v => { setMonth(v); setPage(0); }} /></View>{admin ? <View style={workflow.field}><Field label="Referencia del paciente (opcional)" value={patientId} onChangeText={v => { setPatientId(v); setPage(0); }} /></View> : null}</View><CommissionSelect accessibilityLabel={admin ? "Elegibilidad de la sesión" : "Estado de comisión"} options={[{ value: 'ALL', label: 'Todas las sesiones' }, { value: 'ELIGIBLE', label: 'Incluidas en el cálculo' }, { value: 'PENDING', label: 'Pendientes o excluidas' }]} value={state} onSelect={v => { setState(v); setPage(0); }} /><Button variant="ghost" size="small" style={{ alignSelf: 'flex-start' }} onPress={() => { setReview(v => !v); setPage(0); }}>{review ? 'Mostrar todas' : 'Solo con revisión abierta'}</Button></> : null}</Card>
 {loading ? <ActivityIndicator accessibilityLabel="Cargando sesiones" /> : null}{error ? <><Text error>{error}</Text><Button onPress={() => void load()}>Reintentar desglose</Button></> : null}
 {data?.items.map(row => admin && account && onPeriods ? <AdminCommissionSessionCard key={row.id} row={row} account={account} run={run} busy={busy} refresh={refresh} onPeriods={onPeriods} /> : <ProfessionalCommissionSessionCard key={row.id} row={row} busy={busy} onActivity={admin ? undefined : () => setSelected({ id: row.id, action: 'COLLECT' })} onReview={admin ? undefined : () => setSelected({ id: row.id, action: 'REVIEW' })}>{!admin && selected?.id === row.id ? <SessionForm key={selected.action} initialAction={selected.action} row={row} run={run} admin={admin} busy={busy} onDone={() => setSelected(undefined)} /> : null}</ProfessionalCommissionSessionCard>)} {data && !data.items.length && !loading && !error ? <WorkflowEmpty icon="calendar-outline" title="No hay sesiones con estos filtros" description="Las sesiones aparecerán aquí cuando se registren. Si has aplicado filtros, prueba a cambiarlos." /> : null}<ReferralPagination page={page} hasMore={data?.hasMore ?? false} loading={loading || busy} onChange={setPage} /></>;
}
