import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, ScrollView, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { RootStackParamList } from '../../constants/types';
import { useTheme } from '../../contexts/ThemeContext';
import { getErrorMessage } from '../../constants/errors';
import { SimpleDropdown } from '../../components/common/SimpleDropdown';
import { ReferralPagination } from '../referrals/ReferralControls';
import { workflow } from '../referrals/WorkflowUI';
import * as service from '../../services/heraCommissionService';
import { Card, Text, Field, Check, Button, WorkflowHeader, WorkflowHint, WorkflowDate, Summary, day, getMadridDateKey, money, dateTime, styles, Run } from './CommissionElements';
import { CommissionSessions } from './CommissionSessions';
import { CashOperations, CommissionIssues, CommissionPeriods, ReceiptForm } from './CommissionOperations';
import { CommissionExplanation } from './CommissionExplanation';
import { ProfessionalCommissionOverview } from './ProfessionalCommissionOverview';

function Agreements({ data, admin, run, busy }: { data: service.AccountDetail; admin: boolean; run: Run; busy: boolean }) {
 const [reason, setReason] = useState(''); const [date, setDate] = useState(getMadridDateKey());
 return <>{data.acceptances.map(a => <Card key={a.id}><Text title>{admin ? `Condiciones ${a.terms.id}` : 'Condiciones aceptadas'}</Text><Text>Aceptadas el {dateTime(a.acceptedAt)} · Efectivas desde {dateTime(a.terms.effectiveAt)}</Text><Text>{a.terms.contractText}</Text><Text>Fiscalidad: {a.terms.fiscalTreatment}</Text>{a.terminatedAt ? <Text>Terminación: {dateTime(a.terminatedAt)}. Se conservan obligaciones e historial.</Text> : <><WorkflowDate label="Fecha de terminación prospectiva (AAAA-MM-DD)" value={date} onChangeText={setDate} /><Field label="Motivo de terminación" value={reason} onChangeText={setReason} /><Button variant="outline" disabled={busy} onPress={() => void run(() => service.decide(data.summary.id, admin, { action: 'TERMINATE', termsId: a.termsId, cutOff: day(date), reason }))}>Terminar nuevas comisiones desde esta fecha</Button></>}</Card>)}</>;
}

function AdminBalances({ specialistId, onOpen, refresh }: { specialistId?: string; onOpen: (id: string) => void; refresh: number }) {
 const [operators, setOperators] = useState<Awaited<ReturnType<typeof service.operators>>>([]); const [operator, setOperator] = useState(''); const [mode, setMode] = useState<service.Mode>('LIVE'); const [search, setSearch] = useState(''); const [status, setStatus] = useState('ALL'); const [page, setPage] = useState(0);
 const [loadError, setLoadError] = useState('');
 const [rows, setRows] = useState<service.Balance[]>([]); const [totals, setTotals] = useState<Awaited<ReturnType<typeof service.balances>>['totals']>(); const [more, setMore] = useState(false); const [loading, setLoading] = useState(false);
 useEffect(() => { let active = true; void service.operators().then(list => { if (active) { setOperators(list); setOperator(list[0]?.operatorKey ?? ''); setMode(list[0]?.mode ?? 'LIVE'); } }).catch(e => { if (active) setLoadError(getErrorMessage(e, 'No se pudieron cargar los titulares.')); }); return () => { active = false; }; }, []);
 useEffect(() => { let active = true; if (!operator && !specialistId) return; setLoading(true); setLoadError(''); void (async () => { if (specialistId) { const result = await service.specialistAccounts(specialistId); if (active) setRows(result); } else { const result = await service.balances({ operatorKey: operator, mode, search, status: status === 'ALL' ? undefined : status, page }); if (active) { setRows(result.items); setTotals(result.totals); setMore(result.hasMore); } } })().catch(e => { if (active) setLoadError(getErrorMessage(e, 'No se pudieron cargar los saldos.')); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [operator, mode, search, status, page, specialistId, refresh]);
 return <>{loadError ? <Text error>{loadError}</Text> : null}{!specialistId ? <Card><Text title>Saldo por especialista</Text><WorkflowHint>Importes históricos del titular y modo seleccionados. Los totales corresponden al filtro completo.</WorkflowHint><SimpleDropdown accessibilityLabel="Titular fiscal" options={[...new Map(operators.map(o => [o.operatorKey, { value: o.operatorKey, label: o.operatorName }])).values()]} value={operator} onSelect={v => { setOperator(v); setPage(0); }} /><SimpleDropdown accessibilityLabel="Modo de comisiones" options={[{ value: 'LIVE', label: 'Real' }, { value: 'SIMULATION', label: 'Simulación sin deuda' }]} value={mode} onSelect={v => { if (v === 'LIVE' || v === 'SIMULATION') { setMode(v); setPage(0); } }} /><Field label="Buscar especialista" value={search} onChangeText={v => { setSearch(v); setPage(0); }} /><SimpleDropdown accessibilityLabel="Filtro de saldo" options={[{ value: 'ALL', label: 'Todos' }, { value: 'PENDING', label: 'Pendiente' }, { value: 'PARTIAL', label: 'Parcial' }, { value: 'CURRENT', label: 'Al día' }, { value: 'OVERDUE', label: 'Vencido' }, { value: 'ISSUES', label: 'Con incidencias' }]} value={status} onSelect={v => { setStatus(v); setPage(0); }} /></Card> : null}
 {totals ? <><Text>{totals.count} especialistas en este filtro</Text><Summary value={totals} /></> : null}{loading ? <ActivityIndicator accessibilityLabel="Cargando saldos" /> : null}
 {rows.map(row => <Card key={row.id}><Text title>{row.specialistName}</Text><Text>{row.mode === 'SIMULATION' ? 'Simulación sin deuda' : 'Real'} · {row.operatorKey}</Text><Text>Pendiente documentado {money(row.pendingCents)} · Devengado {money(row.accruedCents)} · Sin documentar {money(row.undocumentedCents)}</Text><Text>Vencido {money(row.overdueCents)} · Recibido {money(row.receivedCents)} · Saldo a favor {money(row.creditCents)}</Text><Button variant="outline" onPress={() => onOpen(row.id)}>Gestionar comisiones de {row.specialistName}</Button></Card>)}
 {!loading && !rows.length ? <Text>No hay cuentas de comisiones en esta vista.</Text> : null}{!specialistId ? <ReferralPagination page={page} hasMore={more} loading={loading} onChange={setPage} /> : null}</>;
}

export function HeraCommissionsScreen({ route, navigation }: NativeStackScreenProps<RootStackParamList, 'HeraCommissions'>) {
 const { theme } = useTheme(); const accountId = route.params?.accountId; const admin = route.params?.admin === true;
 const [config, setConfig] = useState<service.Configuration>(); const [data, setData] = useState<service.AccountDetail>(); const [loading, setLoading] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [tab, setTab] = useState('sessions'); const [page, setPage] = useState(0); const [refresh, setRefresh] = useState(0); const [accepted, setAccepted] = useState(false); const [showTerms, setShowTerms] = useState(false); const [receipt, setReceipt] = useState<{ documentId?: string }>();
 useEffect(() => { setAccepted(false); setShowTerms(false); }, [config?.terms?.id]);
 const generation = useRef(0); const submitting = useRef(false); const scroll = useRef<ScrollView>(null);
 const load = useCallback(async () => { const g = ++generation.current; setLoading(true); try { if (accountId) { const result = await service.detail(accountId, admin, page); if (g === generation.current) setData(result); } else if (!admin) { const result = await service.configuration(); if (g === generation.current) setConfig(result); } } catch(e) { if (g === generation.current) setError(getErrorMessage(e, 'No se pudieron cargar las comisiones.')); } finally { if (g === generation.current) setLoading(false); } }, [accountId, admin, page]);
 useFocusEffect(useCallback(() => { void load(); return () => { generation.current++; }; }, [load]));
 useEffect(() => { setData(undefined); setReceipt(undefined); setPage(0); setError(''); }, [accountId, admin]);
 const run: Run = async operation => { if (submitting.current) return false; submitting.current = true; setBusy(true); setError(''); try { await operation(); return true; } catch(e) { setError(getErrorMessage(e, 'No se pudo guardar. Tus datos se conservan; puedes reintentar.')); scroll.current?.scrollTo({ y: 0, animated: false }); return false; } finally { submitting.current = false; setBusy(false); } };
 const mutate: Run = async operation => { const ok = await run(operation); if (ok) { await load(); setRefresh(v => v + 1); } return ok; };
 const open = (id: string) => { setPage(0); navigation.setParams({ accountId: id }); };
 return <ScrollView ref={scroll} style={{ flex: 1, backgroundColor: theme.bg }} contentContainerStyle={workflow.page} keyboardShouldPersistTaps="handled"><WorkflowHeader title="Comisiones HERA" subtitle="Consulta tus comisiones y el estado de tus transferencias." action={<View style={styles.row}><Button size="small" variant="outline" onPress={() => accountId ? navigation.setParams({ accountId: undefined }) : navigation.goBack()}>Volver</Button><Button size="small" variant="outline" disabled={busy || loading} onPress={() => { void load(); setRefresh(v => v + 1); }}>Actualizar saldos</Button></View>} />
 {error ? <Card><Text error>{error}</Text><Button variant="outline" disabled={busy} onPress={() => void load()}>Recargar datos</Button></Card> : null}{loading ? <ActivityIndicator accessibilityLabel="Cargando comisiones" /> : null}
 {!accountId ? admin ? <AdminBalances specialistId={route.params?.specialistId} onOpen={open} refresh={refresh} /> : config ? <><ProfessionalCommissionOverview config={config} refresh={refresh} onOpen={open} />
 {config.terms ? <Card><Button variant="outline" onPress={() => setShowTerms(v => !v)}>Ver condiciones exactas</Button>{showTerms ? <><Text>{config.terms.contractText}</Text><Text>Fiscalidad de HERA: {config.terms.fiscalTreatment}</Text><Text>Vigencia: {dateTime(config.terms.effectiveAt)} · Titular: {config.terms.operatorName}</Text><Check label="He leído y acepto esta versión de las condiciones y su tratamiento fiscal" checked={accepted} onChange={setAccepted} disabled={busy} /><Button disabled={busy || !accepted || !config.canAccept} onPress={() => void run(async () => { if (!config.terms) return; const result = await service.accept(config.terms.id); open(result.accountId); })}>Aceptar condiciones</Button></> : null}</Card> : null}
 <CommissionExplanation terms={config.terms} simulation={config.mode === 'SIMULATION'} /></> : null : data && data.summary.id === accountId ? <>
 <Text title>{data.summary.specialistName}</Text>{data.summary.mode === 'SIMULATION' ? <Text>Simulación: estos importes no generan deuda.</Text> : null}<Summary value={data.summary} /><WorkflowHint>Estimado pendiente de devengo: {money(data.summary.estimatedCents)}. No es deuda exigible. Saldo fiscal histórico pendiente: {money(data.summary.documentedCents)}; las correcciones pendientes se excluyen del importe válido para transferir.</WorkflowHint>
 <View style={styles.row}>{[['sessions','Sesiones y cobros'],['periods','Liquidaciones y documentos'],['cash','Transferencias y crédito'],['issues','Revisiones'],['terms','Condiciones']].map(([value,label]) => <Button key={value} accessibilityRole="tab" accessibilityState={{ selected: tab === value }} variant={tab === value ? 'secondary' : 'ghost'} disabled={busy} onPress={() => setTab(value)}>{label}</Button>)}</View>
 {receipt ? <ReceiptForm data={data} selectedDocument={receipt.documentId} run={mutate} busy={busy} onClose={() => setReceipt(undefined)} /> : null}
 {tab === 'sessions' ? <CommissionSessions key={accountId} accountId={accountId} admin={admin} clientId={route.params?.clientId} run={mutate} busy={busy} refresh={refresh} /> : tab === 'periods' ? <CommissionPeriods data={data} admin={admin} run={mutate} busy={busy} onReceipt={id => setReceipt({ documentId: id })} /> : tab === 'issues' ? <CommissionIssues data={data} admin={admin} run={mutate} busy={busy} /> : tab === 'terms' ? <><CommissionExplanation terms={data.acceptances[0]?.terms} simulation={data.summary.mode === 'SIMULATION'} /><Agreements data={data} admin={admin} run={mutate} busy={busy} /></> : <>
 {admin ? <><Button disabled={busy} onPress={() => setReceipt({})}>Registrar transferencia recibida</Button><CashOperations data={data} run={mutate} busy={busy} /></> : <><Card><Text title>Transferencias externas a HERA</Text><Text>Beneficiario: {data.acceptances[0]?.terms.beneficiary}</Text><Text>IBAN: {data.acceptances[0]?.terms.iban}</Text><Text>Referencia: tu identificador {data.summary.specialistId} y número de documento.</Text><WorkflowHint>HERA confirma manualmente la recepción. Una subida de PDF o una factura emitida no confirma dinero recibido.</WorkflowHint></Card>{data.cash.map(c => <Card key={c.id}><Text>{c.kind === 'RECEIPT' ? 'Recepción' : c.kind === 'REFUND' ? 'Devolución externa' : 'Anulación de registro'} · {money(c.amountCents)} · {dateTime(c.occurredAt)}</Text><Text>{c.reference}</Text><WorkflowHint>Confirmado manualmente por HERA.</WorkflowHint>{c.applications.map(a => <Text key={a.id}>Documento {a.documentId.slice(-8)} · {money(a.amountCents)} · {a.reason}</Text>)}</Card>)}</>}
 </>}{tab !== 'sessions' ? <ReferralPagination page={page} hasMore={data.hasMore} loading={loading || busy} onChange={setPage} /> : null}</> : null}</ScrollView>;
}
