import type { Theme } from "../../constants/theme";

// Shared variables supported by Connect on web and native. No iframe CSS overrides.
export const connectAppearance = (theme: Theme, fontFamily = "sans-serif") => ({
  variables: {
    fontFamily,
    fontSizeBase: "16px",
    spacingUnit: "8px",
    borderRadius: "12px",
    colorPrimary: theme.primary,
    colorBackground: theme.bg,
    colorText: theme.textPrimary,
    colorSecondaryText: theme.textSecondary,
    colorDanger: theme.error,
    colorBorder: theme.border,
    buttonPrimaryColorBackground: theme.actionPrimary,
    buttonPrimaryColorBorder: theme.actionPrimary,
    buttonPrimaryColorText: theme.actionPrimaryText,
    buttonSecondaryColorBackground: theme.bg,
    buttonSecondaryColorBorder: theme.borderStrong,
    buttonSecondaryColorText: theme.primary,
    buttonBorderRadius: "12px",
    buttonPaddingX: "18px",
    buttonPaddingY: "12px",
    buttonLabelFontWeight: "700",
    formBackgroundColor: theme.bgCard,
    formBorderRadius: "10px",
    formHighlightColorBorder: theme.focus,
    formAccentColor: theme.primary,
    inputFieldPaddingX: "12px",
    inputFieldPaddingY: "12px",
    headingXlFontSize: "24px",
    headingLgFontSize: "21px",
    headingMdFontSize: "18px",
    headingXlFontWeight: "700",
    headingLgFontWeight: "700",
    headingMdFontWeight: "700",
    bodyMdFontSize: "16px",
    bodySmFontSize: "14px",
  },
});
