import React, { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  TextInput,
  ActivityIndicator,
  Alert,
  Switch,
  Platform,
  Pressable,
  useWindowDimensions,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation, useFocusEffect } from '@react-navigation/native';
import { heraLanding, colors, spacing, borderRadius, typography, shadows, touchTarget } from '../../constants/colors';
import { AppNavigationProp } from '../../constants/types';
import { SimpleDropdown } from '../../components/common/SimpleDropdown';
import { useAuth } from '../../contexts/AuthContext';
import {
  billingService,
  BillingSummary,
  Invoice,
  InvoiceStatus,
  BillingConfig,
  TariffsConfig,
  TariffItem,
} from '../../services/billingService';
import * as analyticsService from '../../services/analyticsService';

// ============================================================================
// CONSTANTS
// ============================================================================

const STRINGS = {
  title: 'Facturación',
  exportMonth: 'Exportar mes',
  newInvoice: ' Nueva factura',
  thisMonth: 'Facturado este mes',
  thisYear: 'Acumulado este año',
  invoicesMonth: 'Facturas emitidas',
  pendingSend: 'Pendientes de envío',
  invoiceHistory: 'Historial de facturas',
  tariffs: 'Tarifas',
  fiscalData: 'Datos fiscales',
  numbering: 'Numeración',
  automation: 'Automatización',
  edit: 'Editar',
  save: 'Guardar',
  cancel: 'Cancelar',
  all: 'Todas',
  sent: 'Enviadas',
  drafts: 'Borradores',
  cancelled: 'Canceladas',
  searchClient: 'Buscar cliente...',
  pricePerSession: 'Precio por sesión',
  sessionDuration: 'Duración de sesión',
  firstSessionFree: 'Primera sesión gratuita',
  firstSessionBadge: 'Primera sesión: Gratis',
  fiscalName: 'Nombre fiscal',
  nif: 'NIF',
  fiscalAddress: 'Dirección fiscal',
  vat: 'IVA',
  logo: 'Logo factura',
  addLogo: '+ Logo',
  bankAccount: 'IBAN',
  paymentConditions: 'Condiciones de pago',
  invoicePrefix: 'Prefijo',
  nextNumber: 'Siguiente número',
  previewFormat: 'Formato: ',
  adjustNote: 'Puedes ajustar el número al migrar desde otro sistema',
  autoGenerate: 'Generar facturas automáticamente',
  autoGenerateDesc: 'Al completar una sesión',
  autoSend: 'Enviar al cliente automáticamente',
  autoSendDesc: 'Tras generar la factura',
  emailCopy: 'Copia de factura por email',
  emailCopyDesc: 'Recibir copia en tu email',
  emptyTitle: 'Aún no has emitido ninguna factura',
  emptyDesc: 'Las facturas se generarán automáticamente al completar sesiones si activas la automatización.',
  generateInvoice: 'Generar factura',
  sendNow: 'Enviar ahora',
  saveDraft: 'Guardar borrador',
  selectClient: 'Seleccionar cliente',
  selectSession: 'Sesión (opcional)',
  concept: 'Concepto',
  amount: 'Importe',
  date: 'Fecha',
  invoiceNumber: 'N.º factura',
  confirmSend: '¿Enviar esta factura al cliente?',
  confirmCancel: '¿Cancelar esta factura?',
  resend: 'Volver a enviar',
  deleteDraft: 'Eliminar borrador',
  deleteInvoice: 'Eliminar',
  deleteConfirmTitle: '¿Eliminar factura?',
  deleteConfirmMsg: 'Esta acción no se puede deshacer. La factura {number} será eliminada permanentemente.',
  deleteConfirm2Title: 'Confirmar eliminación',
  deleteConfirm2Msg: '¿Estás seguro? La factura {number} desaparecerá del historial.',
  deleteConfirm2Btn: 'Eliminar definitivamente',
  continueBtn: 'Continuar',
  resendConfirmMsg: '¿Reenviar factura {number} a {client}?',
  resendBtn: 'Reenviar',
  resendSuccess: 'Factura reenviada correctamente',
};

const VAT_OPTIONS = [
  { value: 0, label: 'Exento (Art. 20)' },
  { value: 10, label: '10%' },
  { value: 21, label: '21%' },
];

const SLOT_OPTIONS = [
  { value: 30, label: '30 min' },
  { value: 45, label: '45 min' },
  { value: 60, label: '60 min' },
  { value: 90, label: '90 min' },
  { value: 120, label: '120 min' },
];

const STATUS_COLORS: Record<InvoiceStatus, { bg: string; text: string; label: string }> = {
  SENT: { bg: heraLanding.successLight, text: heraLanding.success, label: 'Enviada' },
  DRAFT: { bg: heraLanding.warningLight, text: heraLanding.warningAmber, label: 'Borrador' },
  CANCELLED: { bg: heraLanding.mutedLight, text: heraLanding.textMuted, label: 'Cancelada' },
};

type FilterTab = 'all' | InvoiceStatus;

const MONTH_NAMES_ES = [
  'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
];
const MONTH_ABBREV_ES = [
  'Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun',
  'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic',
];

const formatCurrency = (amount: number): string => {
  return `€${amount.toLocaleString('es-ES', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

const formatDateShort = (dateStr: string): string => {
  return new Date(dateStr).toLocaleDateString('es-ES', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  });
};

// ============================================================================
// SUB-COMPONENTS
// ============================================================================

interface StatCardProps {
  value: string;
  label: string;
  sublabel: string;
}

const StatCard: React.FC<StatCardProps> = ({ value, label, sublabel }) => (
  <View style={styles.statCard}>
    <Text style={styles.statValue} numberOfLines={1}>{value}</Text>
    <Text style={styles.statLabel} numberOfLines={1}>{label}</Text>
    <Text style={styles.statSublabel} numberOfLines={1}>{sublabel}</Text>
  </View>
);

interface StatusBadgeProps {
  status: InvoiceStatus;
}

const InvoiceStatusBadge: React.FC<StatusBadgeProps> = ({ status }) => {
  const config = STATUS_COLORS[status];
  return (
    <View style={[styles.badge, { backgroundColor: config.bg }]}>
      <Text style={[styles.badgeText, { color: config.text }]}>{config.label}</Text>
    </View>
  );
};


// ============================================================================
// MAIN COMPONENT
// ============================================================================

export function BillingScreen() {
  const { user } = useAuth();
  const { width } = useWindowDimensions();
  const isDesktop = width >= 768;

  // Data state
  const [summary, setSummary] = useState<BillingSummary | null>(null);
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);

  // Specialist billing config (loaded from API)
  const [billingConfig, setBillingConfig] = useState<BillingConfig>({});
  const [tariffItems, setTariffItems] = useState<TariffItem[]>([]);
  const [firstVisitFree, setFirstVisitFree] = useState(false);

  // Filter state
  const [activeFilter, setActiveFilter] = useState<FilterTab>('all');
  const [searchQuery, setSearchQuery] = useState('');

  // Menu state (portal pattern — window-relative coordinates)
  const [openMenuId, setOpenMenuId] = useState<string | null>(null);
  const [menuPosition, setMenuPosition] = useState<{ top: number; right: number }>({ top: 0, right: 0 });
  const menuButtonRefs = useRef<Record<string, View | null>>({});

  // Edit state
  const [editingTariffs, setEditingTariffs] = useState(false);
  const [editingFiscal, setEditingFiscal] = useState(false);
  const [editingNumbering, setEditingNumbering] = useState(false);
  // Temp edit values
  const [tempTariffItems, setTempTariffItems] = useState<TariffItem[]>([]);
  const [tempFirstVisitFree, setTempFirstVisitFree] = useState(false);
  const [tempFiscal, setTempFiscal] = useState<BillingConfig>({});
  const [tempNumbering, setTempNumbering] = useState({ invoicePrefix: 'F', invoiceNextNumber: 1 });

  const navigation = useNavigation<AppNavigationProp>();

  // Action loading states
  const [sendingId, setSendingId] = useState<string | null>(null);
  const [savingConfig, setSavingConfig] = useState(false);


  // ── Load data ────────────────────────────────────────────────
  const loadData = useCallback(async () => {
    try {
      setLoading(true);
      const [summaryData, invoicesData] = await Promise.all([
        billingService.getSummary(),
        billingService.getInvoices(),
      ]);
      setSummary(summaryData);
      setInvoices(invoicesData);
    } catch (error) {
      Alert.alert('Error', error instanceof Error ? error.message : 'Error al cargar datos');
    } finally {
      setLoading(false);
    }
  }, []);

  useFocusEffect(
    useCallback(() => {
      loadData();
      analyticsService.trackScreen('billing');
    }, [loadData])
  );

  // Load specialist billing config from API
  const loadConfig = useCallback(async () => {
    try {
      const s = await billingService.getConfig();
      const config: BillingConfig = {
        invoicePrefix: s.invoicePrefix || 'F',
        invoiceNextNumber: s.invoiceNextNumber || 1,
        vatRate: s.vatRate ?? 21,
        applyVat: s.applyVat ?? false,
        vatExemptReason: s.vatExemptReason || null,
        invoiceLogoUrl: s.invoiceLogoUrl || null,
        bankIban: s.bankIban || '',
        paymentConditions: s.paymentConditions || '',
        fiscalName: s.fiscalName || '',
        fiscalAddress: s.fiscalAddress || '',
        fiscalNif: s.fiscalNif || '',
        autoGenerateInvoice: s.autoGenerateInvoice || false,
        autoSendToClient: s.autoSendToClient || false,
        sendInvoiceCopyTo: s.sendInvoiceCopyTo || null,
      };
      setBillingConfig(config);
      setTempFiscal(config);
      setTempNumbering({
        invoicePrefix: config.invoicePrefix || 'F',
        invoiceNextNumber: config.invoiceNextNumber || 1,
      });

      // Parse tariffs: use JSON array if available, otherwise build from scalar fields
      const parsedTariffs: TariffItem[] = (s.tariffs && Array.isArray(s.tariffs) && s.tariffs.length > 0)
        ? (s.tariffs as TariffItem[])
        : [{
            id: '1',
            name: 'Sesión individual',
            price: s.pricePerSession || 0,
            durationMinutes: s.slotDuration || 60,
            isDefault: true,
            isActive: true,
          }];
      setTariffItems(parsedTariffs);
      setTempTariffItems(parsedTariffs);
      setFirstVisitFree(s.firstVisitFree || false);
      setTempFirstVisitFree(s.firstVisitFree || false);

      // Default tariff is now used in CreateInvoiceScreen
    } catch {
      // Config loading failed — defaults are already set
    }
  }, []);

  useEffect(() => {
    loadConfig();
  }, [loadConfig]);

  // ── Filtered invoices ────────────────────────────────────────
  const filteredInvoices = useMemo(() => {
    let result = invoices;
    if (activeFilter !== 'all') {
      result = result.filter((inv) => inv.status === activeFilter);
    }
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      result = result.filter((inv) =>
        inv.client.user.name.toLowerCase().includes(q) ||
        inv.invoiceNumber.toLowerCase().includes(q)
      );
    }
    return result;
  }, [invoices, activeFilter, searchQuery]);

  // ── Actions ──────────────────────────────────────────────────
  const handleSendInvoice = (invoiceId: string) => {
    const invoice = invoices.find((inv) => inv.id === invoiceId);
    const clientName = invoice?.client?.user?.name || 'el cliente';
    const invoiceNumber = invoice?.invoiceNumber || '';

    Alert.alert(
      '¿Enviar factura?',
      `Se enviará la factura ${invoiceNumber} a ${clientName}. ¿Continuar?`,
      [
        { text: 'Cancelar', style: 'cancel' },
        {
          text: 'Enviar',
          onPress: async () => {
            try {
              setSendingId(invoiceId);
              await billingService.sendInvoice(invoiceId);
              // Update local state to reflect SENT status
              setInvoices((prev) =>
                prev.map((inv) =>
                  inv.id === invoiceId ? { ...inv, status: 'SENT' as const, sentAt: new Date().toISOString() } : inv
                ),
              );
              Alert.alert('Éxito', 'Factura enviada correctamente');
            } catch (error) {
              Alert.alert('Error', error instanceof Error ? error.message : 'Error al enviar la factura');
            } finally {
              setSendingId(null);
            }
          },
        },
      ],
    );
  };

  const handleDownload = async (invoiceId: string, invoiceNumber: string) => {
    try {
      await billingService.downloadInvoice(invoiceId, invoiceNumber);
    } catch (error) {
      Alert.alert('Error', error instanceof Error ? error.message : 'Error al descargar');
    }
  };

  const handleResendInvoice = (invoice: Invoice) => {
    setOpenMenuId(null);
    const clientName = invoice.client?.user?.name || 'el cliente';
    Alert.alert(
      STRINGS.resend,
      STRINGS.resendConfirmMsg.replace('{number}', invoice.invoiceNumber).replace('{client}', clientName),
      [
        { text: STRINGS.cancel, style: 'cancel' },
        {
          text: STRINGS.resendBtn,
          onPress: async () => {
            try {
              setSendingId(invoice.id);
              await billingService.sendInvoice(invoice.id);
              setInvoices((prev) =>
                prev.map((inv) =>
                  inv.id === invoice.id ? { ...inv, status: 'SENT' as const, sentAt: new Date().toISOString() } : inv
                ),
              );
              Alert.alert('Éxito', STRINGS.resendSuccess);
            } catch (error) {
              Alert.alert('Error', error instanceof Error ? error.message : 'Error al reenviar');
            } finally {
              setSendingId(null);
            }
          },
        },
      ],
    );
  };

  const handleDeleteInvoice = (invoice: Invoice) => {
    setOpenMenuId(null);
    Alert.alert(
      STRINGS.deleteConfirmTitle,
      STRINGS.deleteConfirmMsg.replace('{number}', invoice.invoiceNumber),
      [
        { text: STRINGS.cancel, style: 'cancel' },
        {
          text: STRINGS.continueBtn,
          onPress: () => {
            Alert.alert(
              STRINGS.deleteConfirm2Title,
              STRINGS.deleteConfirm2Msg.replace('{number}', invoice.invoiceNumber),
              [
                { text: STRINGS.cancel, style: 'cancel' },
                {
                  text: STRINGS.deleteConfirm2Btn,
                  style: 'destructive',
                  onPress: async () => {
                    try {
                      await billingService.cancelInvoice(invoice.id);
                      setInvoices((prev) =>
                        prev.map((inv) =>
                          inv.id === invoice.id ? { ...inv, status: 'CANCELLED' as const } : inv
                        ),
                      );
                    } catch (error) {
                      Alert.alert('Error', error instanceof Error ? error.message : 'Error al eliminar');
                    }
                  },
                },
              ],
            );
          },
        },
      ],
    );
  };

  const handleSaveTariffs = async () => {
    const defaults = tempTariffItems.filter((t) => t.isDefault);
    if (defaults.length !== 1) {
      Alert.alert('Error', 'Debe haber exactamente una tarifa por defecto');
      return;
    }
    const actives = tempTariffItems.filter((t) => t.isActive);
    if (actives.length === 0) {
      Alert.alert('Error', 'Debe haber al menos una tarifa activa');
      return;
    }
    try {
      setSavingConfig(true);
      await billingService.updateTariffs({ tariffs: tempTariffItems, firstVisitFree: tempFirstVisitFree });
      setTariffItems(tempTariffItems);
      setFirstVisitFree(tempFirstVisitFree);
      setEditingTariffs(false);
      Alert.alert('Éxito', 'Tarifas actualizadas');
    } catch (error) {
      Alert.alert('Error', error instanceof Error ? error.message : 'Error al guardar');
    } finally {
      setSavingConfig(false);
    }
  };

  const handleSaveFiscal = async () => {
    try {
      setSavingConfig(true);
      await billingService.updateBillingConfig(tempFiscal);
      setBillingConfig((prev) => ({ ...prev, ...tempFiscal }));
      setEditingFiscal(false);
      Alert.alert('Éxito', 'Datos fiscales actualizados');
    } catch (error) {
      Alert.alert('Error', error instanceof Error ? error.message : 'Error al guardar');
    } finally {
      setSavingConfig(false);
    }
  };

  const handleSaveNumbering = async () => {
    try {
      setSavingConfig(true);
      await billingService.updateBillingConfig(tempNumbering);
      setBillingConfig((prev) => ({ ...prev, ...tempNumbering }));
      setEditingNumbering(false);
      Alert.alert('Éxito', 'Numeración actualizada');
    } catch (error) {
      Alert.alert('Error', error instanceof Error ? error.message : 'Error al guardar');
    } finally {
      setSavingConfig(false);
    }
  };

  const handleToggleAutomation = async (field: keyof BillingConfig, value: boolean) => {
    const prev = billingConfig[field];
    setBillingConfig((c) => ({ ...c, [field]: value }));
    try {
      await billingService.updateBillingConfig({ [field]: value });
    } catch (error) {
      // Revert on error
      setBillingConfig((c) => ({ ...c, [field]: prev }));
      Alert.alert('Error', error instanceof Error ? error.message : 'Error al guardar');
    }
  };


  // ── Loading state ────────────────────────────────────────────
  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color={heraLanding.primary} />
      </View>
    );
  }

  // ── Render helpers ───────────────────────────────────────────
  const renderStats = () => {
    const now = new Date();
    const monthIdx = now.getMonth();
    const year = now.getFullYear();
    const monthFull = `${MONTH_NAMES_ES[monthIdx]} ${year}`;
    const monthRange = `Ene — ${MONTH_ABBREV_ES[monthIdx]}`;

    return (
      <View style={styles.statsRow}>
        <StatCard value={formatCurrency(summary?.totalThisMonth ?? 0)} label={STRINGS.thisMonth} sublabel={monthFull} />
        <StatCard value={formatCurrency(summary?.totalThisYear ?? 0)} label={STRINGS.thisYear} sublabel={monthRange} />
        <StatCard value={String(summary?.invoiceCountThisMonth ?? 0)} label={STRINGS.invoicesMonth} sublabel="Este mes" />
        <StatCard value={String(summary?.pendingCount ?? 0)} label={STRINGS.pendingSend} sublabel="Requieren revisión" />
      </View>
    );
  };

  const renderFilterChips = () => {
    const filters: Array<{ key: FilterTab; label: string }> = [
      { key: 'all', label: STRINGS.all },
      { key: 'SENT', label: STRINGS.sent },
      { key: 'DRAFT', label: STRINGS.drafts },
      { key: 'CANCELLED', label: STRINGS.cancelled },
    ];
    return (
      <View style={styles.filterRow}>
        {filters.map((f) => (
          <TouchableOpacity
            key={f.key}
            style={[styles.filterChip, activeFilter === f.key && styles.filterChipActive]}
            onPress={() => setActiveFilter(f.key)}
          >
            <Text style={[styles.filterChipText, activeFilter === f.key && styles.filterChipTextActive]}>
              {f.label}
            </Text>
          </TouchableOpacity>
        ))}
      </View>
    );
  };

  const handleInvoiceRowPress = (invoice: Invoice) => {
    if (invoice.status === 'DRAFT') {
      navigation.navigate('CreateInvoice', { invoiceId: invoice.id });
    } else {
      handleDownload(invoice.id, invoice.invoiceNumber);
    }
  };

  const getMenuOptions = (invoice: Invoice): Array<{ label: string; onPress: () => void; danger?: boolean }> => {
    const options: Array<{ label: string; onPress: () => void; danger?: boolean }> = [];
    if (invoice.status === 'SENT' || (invoice.status === 'DRAFT' && invoice.sentAt)) {
      options.push({ label: STRINGS.resend, onPress: () => handleResendInvoice(invoice) });
    }
    if (invoice.status === 'DRAFT') {
      options.push({ label: STRINGS.deleteDraft, onPress: () => handleDeleteInvoice(invoice), danger: true });
    } else if (invoice.status === 'SENT') {
      options.push({ label: STRINGS.deleteInvoice, onPress: () => handleDeleteInvoice(invoice), danger: true });
    } else if (invoice.status === 'CANCELLED') {
      options.push({ label: STRINGS.deleteInvoice, onPress: () => handleDeleteInvoice(invoice), danger: true });
    }
    return options;
  };

  const handleOpenMenu = (invoiceId: string) => {
    const buttonRef = menuButtonRefs.current[invoiceId];
    if (buttonRef) {
      buttonRef.measure((_x, _y, w, h, pageX, pageY) => {
        setMenuPosition({
          top: pageY + h + 4,
          right: width - (pageX + w),
        });
        setOpenMenuId(invoiceId);
      });
    } else {
      setOpenMenuId(invoiceId);
    }
  };

  const renderInvoiceRow = (invoice: Invoice) => {
    const menuOptions = getMenuOptions(invoice);

    return (
      <TouchableOpacity
        key={invoice.id}
        style={styles.invoiceRow}
        onPress={() => handleInvoiceRowPress(invoice)}
        activeOpacity={0.7}
      >
        <View style={styles.invoiceInfo}>
          <Text style={styles.invoiceNumber}>{invoice.invoiceNumber}</Text>
          <Text style={styles.invoiceClient} numberOfLines={1}>{invoice.client.user.name}</Text>
          <Text style={styles.invoiceDate}>{formatDateShort(invoice.createdAt)}</Text>
        </View>
        <View style={styles.invoiceRight}>
          <Text style={styles.invoiceAmount}>{formatCurrency(invoice.total)}</Text>
          <InvoiceStatusBadge status={invoice.status} />
          <View style={styles.invoiceActions}>
            <TouchableOpacity
              style={styles.iconBtn}
              onPress={(e) => { e.stopPropagation(); handleDownload(invoice.id, invoice.invoiceNumber); }}
              hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
            >
              <Ionicons name="download-outline" size={18} color={heraLanding.textSecondary} />
            </TouchableOpacity>
            {invoice.status === 'DRAFT' && (
              <TouchableOpacity
                style={styles.iconBtn}
                onPress={(e) => { e.stopPropagation(); handleSendInvoice(invoice.id); }}
                disabled={sendingId === invoice.id}
                hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
              >
                {sendingId === invoice.id ? (
                  <ActivityIndicator size="small" color={heraLanding.primary} />
                ) : (
                  <Ionicons name="send-outline" size={18} color={heraLanding.primary} />
                )}
              </TouchableOpacity>
            )}
            {menuOptions.length > 0 && (
              <View
                ref={(ref) => { menuButtonRefs.current[invoice.id] = ref; }}
                collapsable={false}
              >
                <TouchableOpacity
                  style={styles.iconBtn}
                  onPress={(e) => {
                    e.stopPropagation();
                    if (openMenuId === invoice.id) {
                      setOpenMenuId(null);
                    } else {
                      handleOpenMenu(invoice.id);
                    }
                  }}
                  hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
                >
                  <Ionicons name="ellipsis-vertical" size={18} color={heraLanding.textSecondary} />
                </TouchableOpacity>
              </View>
            )}
          </View>
        </View>
      </TouchableOpacity>
    );
  };

  const renderInvoiceList = () => (
    <View style={styles.card}>
      <Text style={styles.cardTitle}>{STRINGS.invoiceHistory}</Text>
      {renderFilterChips()}
      <TextInput
        style={styles.searchInput}
        placeholder={STRINGS.searchClient}
        placeholderTextColor={heraLanding.textMuted}
        value={searchQuery}
        onChangeText={setSearchQuery}
      />
      {filteredInvoices.length === 0 ? (
        <View style={styles.emptyState}>
          <Ionicons name="document-text-outline" size={48} color={heraLanding.textMuted} />
          <Text style={styles.emptyTitle}>{STRINGS.emptyTitle}</Text>
          <Text style={styles.emptyDesc}>{STRINGS.emptyDesc}</Text>
        </View>
      ) : (
        filteredInvoices.map(renderInvoiceRow)
      )}
    </View>
  );

  const handleAddTariff = () => {
    setTempTariffItems((prev) => [...prev, {
      id: String(Date.now()),
      name: '',
      price: 0,
      durationMinutes: 60,
      isDefault: false,
      isActive: true,
    }]);
  };

  const handleUpdateTempTariff = (id: string, field: keyof TariffItem, value: string | number | boolean) => {
    setTempTariffItems((prev) => prev.map((t) => {
      if (t.id !== id) {
        // If setting this one as default, unset others
        if (field === 'isDefault' && value === true) return { ...t, isDefault: false };
        return t;
      }
      return { ...t, [field]: value };
    }));
  };

  const handleDeleteTempTariff = (id: string) => {
    if (tempTariffItems.length <= 1) {
      Alert.alert('Error', 'Debe haber al menos una tarifa');
      return;
    }
    setTempTariffItems((prev) => prev.filter((t) => t.id !== id));
  };

  const renderTariffsCard = () => (
    <View style={[styles.card, { zIndex: 10, overflow: 'visible' as const }]}>
      <View style={styles.cardHeader}>
        <Text style={styles.cardTitle}>{STRINGS.tariffs}</Text>
        <TouchableOpacity onPress={() => {
          setTempTariffItems(tariffItems);
          setTempFirstVisitFree(firstVisitFree);
          setEditingTariffs(!editingTariffs);
        }}>
          <Text style={styles.editBtn}>{editingTariffs ? STRINGS.cancel : STRINGS.edit}</Text>
        </TouchableOpacity>
      </View>
      {editingTariffs ? (
        <View style={styles.editForm}>
          {tempTariffItems.map((tariff) => (
            <View key={tariff.id} style={styles.tariffEditRow}>
              <View style={styles.tariffEditFields}>
                <TextInput
                  style={[styles.input, { flex: 1 }]}
                  value={tariff.name}
                  onChangeText={(v) => handleUpdateTempTariff(tariff.id, 'name', v)}
                  placeholder="Nombre de la tarifa"
                  placeholderTextColor={heraLanding.textMuted}
                />
                <View style={styles.tariffPriceRow}>
                  <TextInput
                    style={[styles.input, { width: 80 }]}
                    value={String(tariff.price)}
                    onChangeText={(v) => handleUpdateTempTariff(tariff.id, 'price', parseFloat(v) || 0)}
                    keyboardType="numeric"
                    placeholder="€"
                    placeholderTextColor={heraLanding.textMuted}
                  />
                  <Text style={styles.fieldHint}>€</Text>
                </View>
                <View style={styles.formGroup}>
                  <SimpleDropdown
                    options={SLOT_OPTIONS.map((opt) => ({ label: opt.label, value: opt.value }))}
                    value={tariff.durationMinutes}
                    onSelect={(v) => handleUpdateTempTariff(tariff.id, 'durationMinutes', v)}
                    placeholder="Duración..."
                  />
                </View>
                <View style={styles.tariffToggles}>
                  <TouchableOpacity
                    style={[styles.tariffToggle, tariff.isDefault && styles.tariffToggleActive]}
                    onPress={() => handleUpdateTempTariff(tariff.id, 'isDefault', true)}
                  >
                    <Text style={[styles.tariffToggleText, tariff.isDefault && styles.tariffToggleTextActive]}>
                      Por defecto
                    </Text>
                  </TouchableOpacity>
                  <TouchableOpacity
                    style={[styles.tariffToggle, !tariff.isActive && styles.tariffToggleInactive]}
                    onPress={() => handleUpdateTempTariff(tariff.id, 'isActive', !tariff.isActive)}
                  >
                    <Text style={[styles.tariffToggleText, !tariff.isActive && styles.tariffToggleTextInactive]}>
                      {tariff.isActive ? 'Activa' : 'Inactiva'}
                    </Text>
                  </TouchableOpacity>
                  {tempTariffItems.length > 1 && (
                    <TouchableOpacity onPress={() => handleDeleteTempTariff(tariff.id)}>
                      <Ionicons name="trash-outline" size={18} color={heraLanding.warning} />
                    </TouchableOpacity>
                  )}
                </View>
              </View>
            </View>
          ))}
          <TouchableOpacity style={styles.addTariffBtn} onPress={handleAddTariff}>
            <Ionicons name="add" size={16} color={heraLanding.primary} />
            <Text style={styles.addTariffBtnText}>Añadir tarifa</Text>
          </TouchableOpacity>
          <View style={styles.switchRow}>
            <Text style={styles.fieldLabel}>{STRINGS.firstSessionFree}</Text>
            <Switch
              value={tempFirstVisitFree}
              onValueChange={setTempFirstVisitFree}
              trackColor={{ false: colors.neutral.gray300, true: heraLanding.primaryMuted }}
              thumbColor={tempFirstVisitFree ? heraLanding.primary : colors.neutral.gray400}
            />
          </View>
          <TouchableOpacity style={styles.saveBtn} onPress={handleSaveTariffs} disabled={savingConfig}>
            {savingConfig ? <ActivityIndicator size="small" color={colors.neutral.white} /> : (
              <Text style={styles.saveBtnText}>{STRINGS.save}</Text>
            )}
          </TouchableOpacity>
        </View>
      ) : (
        <View style={{ gap: spacing.sm }}>
          {tariffItems.filter((t) => t.isActive).map((tariff) => (
            <View key={tariff.id} style={styles.tariffDisplayRow}>
              <View style={{ flex: 1 }}>
                <Text style={styles.configValue}>
                  {tariff.name || 'Sin nombre'}
                  {tariff.isDefault && (
                    <Text style={styles.defaultBadgeInline}> (por defecto)</Text>
                  )}
                </Text>
                <Text style={styles.configDetail}>
                  {tariff.price === 0 ? 'Gratis' : formatCurrency(tariff.price)} · {tariff.durationMinutes} min
                </Text>
              </View>
            </View>
          ))}
          {tariffItems.some((t) => !t.isActive) && (
            <Text style={styles.configDetail}>
              +{tariffItems.filter((t) => !t.isActive).length} tarifa(s) inactiva(s)
            </Text>
          )}
          {firstVisitFree && (
            <View style={styles.freeBadge}>
              <Text style={styles.freeBadgeText}>{STRINGS.firstSessionBadge}</Text>
            </View>
          )}
        </View>
      )}
    </View>
  );

  const renderFiscalCard = () => (
    <View style={styles.card}>
      <View style={styles.cardHeader}>
        <Text style={styles.cardTitle}>{STRINGS.fiscalData}</Text>
        <TouchableOpacity onPress={() => { setTempFiscal(billingConfig); setEditingFiscal(!editingFiscal); }}>
          <Text style={styles.editBtn}>{editingFiscal ? STRINGS.cancel : STRINGS.edit}</Text>
        </TouchableOpacity>
      </View>
      {editingFiscal ? (
        <View style={styles.editForm}>
          <Text style={styles.fieldLabel}>{STRINGS.fiscalName}</Text>
          <TextInput style={styles.input} value={tempFiscal.fiscalName || ''} onChangeText={(v) => setTempFiscal((f) => ({ ...f, fiscalName: v }))} />
          <Text style={styles.fieldLabel}>{STRINGS.nif}</Text>
          <TextInput style={styles.input} value={tempFiscal.fiscalNif || ''} onChangeText={(v) => setTempFiscal((f) => ({ ...f, fiscalNif: v }))} />
          <Text style={styles.fieldLabel}>{STRINGS.fiscalAddress}</Text>
          <TextInput style={styles.input} value={tempFiscal.fiscalAddress || ''} onChangeText={(v) => setTempFiscal((f) => ({ ...f, fiscalAddress: v }))} />
          <Text style={styles.fieldLabel}>{STRINGS.vat}</Text>
          <SimpleDropdown
            options={VAT_OPTIONS.map((opt) => ({ label: opt.label, value: opt.value }))}
            value={tempFiscal.vatRate ?? 0}
            onSelect={(v) => setTempFiscal((f) => ({ ...f, vatRate: v, applyVat: v > 0 }))}
            placeholder="Seleccionar IVA..."
          />
          <Text style={styles.fieldLabel}>{STRINGS.bankAccount}</Text>
          <TextInput style={styles.input} value={tempFiscal.bankIban || ''} onChangeText={(v) => setTempFiscal((f) => ({ ...f, bankIban: v }))} />
          <Text style={styles.fieldLabel}>{STRINGS.paymentConditions}</Text>
          <TextInput style={styles.input} value={tempFiscal.paymentConditions || ''} onChangeText={(v) => setTempFiscal((f) => ({ ...f, paymentConditions: v }))} placeholder="Transferencia bancaria" placeholderTextColor={heraLanding.textMuted} />
          <TouchableOpacity style={styles.saveBtn} onPress={handleSaveFiscal} disabled={savingConfig}>
            {savingConfig ? <ActivityIndicator size="small" color={colors.neutral.white} /> : (
              <Text style={styles.saveBtnText}>{STRINGS.save}</Text>
            )}
          </TouchableOpacity>
        </View>
      ) : (
        <View>
          {billingConfig.fiscalName ? <Text style={styles.configValue}>{billingConfig.fiscalName}</Text> : null}
          {billingConfig.fiscalNif ? <Text style={styles.configDetail}>NIF: {billingConfig.fiscalNif}</Text> : null}
          {billingConfig.fiscalAddress ? <Text style={styles.configDetail}>{billingConfig.fiscalAddress}</Text> : null}
          <Text style={styles.configDetail}>IVA: {VAT_OPTIONS.find((o) => o.value === (billingConfig.vatRate ?? 0))?.label || 'Exento'}</Text>
          {!billingConfig.fiscalName && !billingConfig.fiscalNif && (
            <Text style={styles.configHint}>Completa tus datos fiscales para las facturas</Text>
          )}
        </View>
      )}
    </View>
  );

  const renderNumberingCard = () => {
    const prefix = billingConfig.invoicePrefix || 'F';
    const nextNum = billingConfig.invoiceNextNumber || 1;
    const year = new Date().getFullYear();
    const preview = `${prefix}-${year}-${String(nextNum).padStart(3, '0')}`;

    return (
      <View style={styles.card}>
        <View style={styles.cardHeader}>
          <Text style={styles.cardTitle}>{STRINGS.numbering}</Text>
          <TouchableOpacity onPress={() => { setTempNumbering({ invoicePrefix: prefix, invoiceNextNumber: nextNum }); setEditingNumbering(!editingNumbering); }}>
            <Text style={styles.editBtn}>{editingNumbering ? STRINGS.cancel : STRINGS.edit}</Text>
          </TouchableOpacity>
        </View>
        {editingNumbering ? (
          <View style={styles.editForm}>
            <Text style={styles.fieldLabel}>{STRINGS.invoicePrefix}</Text>
            <TextInput
              style={[styles.input, { maxWidth: 100 }]}
              value={tempNumbering.invoicePrefix}
              onChangeText={(v) => setTempNumbering((n) => ({ ...n, invoicePrefix: v }))}
              maxLength={10}
            />
            <Text style={styles.fieldLabel}>{STRINGS.nextNumber}</Text>
            <TextInput
              style={[styles.input, { maxWidth: 120 }]}
              value={String(tempNumbering.invoiceNextNumber)}
              onChangeText={(v) => setTempNumbering((n) => ({ ...n, invoiceNextNumber: parseInt(v) || 1 }))}
              keyboardType="numeric"
            />
            <Text style={styles.configHint}>{STRINGS.adjustNote}</Text>
            <TouchableOpacity style={styles.saveBtn} onPress={handleSaveNumbering} disabled={savingConfig}>
              {savingConfig ? <ActivityIndicator size="small" color={colors.neutral.white} /> : (
                <Text style={styles.saveBtnText}>{STRINGS.save}</Text>
              )}
            </TouchableOpacity>
          </View>
        ) : (
          <View>
            <Text style={styles.configValue}>{STRINGS.previewFormat}{preview}</Text>
          </View>
        )}
      </View>
    );
  };

  const renderAutomationCard = () => (
    <View style={styles.card}>
      <Text style={styles.cardTitle}>{STRINGS.automation}</Text>
      <View style={styles.automationItem}>
        <View style={styles.automationText}>
          <Text style={styles.automationLabel}>{STRINGS.autoGenerate}</Text>
          <Text style={styles.automationDesc}>{STRINGS.autoGenerateDesc}</Text>
        </View>
        <Switch
          value={billingConfig.autoGenerateInvoice || false}
          onValueChange={(v) => handleToggleAutomation('autoGenerateInvoice', v)}
          trackColor={{ false: colors.neutral.gray300, true: heraLanding.primaryMuted }}
          thumbColor={billingConfig.autoGenerateInvoice ? heraLanding.primary : colors.neutral.gray400}
        />
      </View>
      <View style={styles.automationItem}>
        <View style={styles.automationText}>
          <Text style={styles.automationLabel}>{STRINGS.autoSend}</Text>
          <Text style={styles.automationDesc}>{STRINGS.autoSendDesc}</Text>
        </View>
        <Switch
          value={billingConfig.autoSendToClient || false}
          onValueChange={(v) => handleToggleAutomation('autoSendToClient', v)}
          trackColor={{ false: colors.neutral.gray300, true: heraLanding.primaryMuted }}
          thumbColor={billingConfig.autoSendToClient ? heraLanding.primary : colors.neutral.gray400}
        />
      </View>
      <View style={styles.automationItem}>
        <View style={styles.automationText}>
          <Text style={styles.automationLabel}>{STRINGS.emailCopy}</Text>
          <Text style={styles.automationDesc}>{STRINGS.emailCopyDesc}</Text>
        </View>
        <Switch
          value={!!billingConfig.sendInvoiceCopyTo}
          onValueChange={(v) => {
            const email = v ? (user?.email || '') : null;
            handleToggleAutomation('sendInvoiceCopyTo', email as unknown as boolean);
          }}
          trackColor={{ false: colors.neutral.gray300, true: heraLanding.primaryMuted }}
          thumbColor={billingConfig.sendInvoiceCopyTo ? heraLanding.primary : colors.neutral.gray400}
        />
      </View>
    </View>
  );


  // ── Portal menu ─────────────────────────────────────────────
  const openMenuInvoice = openMenuId ? invoices.find((inv) => inv.id === openMenuId) : null;
  const portalMenuOptions = openMenuInvoice ? getMenuOptions(openMenuInvoice) : [];

  // ── Main layout ──────────────────────────────────────────────
  return (
    <View style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.headerTitle}>{STRINGS.title}</Text>
        <View style={styles.headerActions}>
          <TouchableOpacity
            style={styles.headerBtn}
            onPress={() => navigation.navigate('CreateInvoice', {})}
          >
            <Ionicons name="add" size={18} color={colors.neutral.white} />
            <Text style={styles.headerBtnText}>{STRINGS.newInvoice}</Text>
          </TouchableOpacity>
        </View>
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={[
          styles.scrollContent,
          isDesktop && styles.scrollContentDesktop,
        ]}
        showsVerticalScrollIndicator={false}
      >
        {/* Stats */}
        {renderStats()}

        {/* Desktop: two columns */}
        {isDesktop ? (
          <View style={styles.desktopColumns}>
            <View style={styles.mainColumn}>
              {renderInvoiceList()}
            </View>
            <View style={styles.sideColumn}>
              {renderTariffsCard()}
              {renderFiscalCard()}
              {renderNumberingCard()}
              {renderAutomationCard()}
            </View>
          </View>
        ) : (
          <>
            {renderInvoiceList()}
            {renderTariffsCard()}
            {renderFiscalCard()}
            {renderNumberingCard()}
            {renderAutomationCard()}
          </>
        )}
      </ScrollView>

      {/* Portal: three-dot menu rendered at root level */}
      {openMenuId && portalMenuOptions.length > 0 && (
        <>
          <Pressable
            style={styles.menuBackdrop}
            onPress={() => setOpenMenuId(null)}
          />
          <View style={[styles.menuDropdown, { top: menuPosition.top, right: menuPosition.right }]}>
            {portalMenuOptions.map((opt) => (
              <TouchableOpacity
                key={opt.label}
                style={styles.menuOption}
                onPress={() => opt.onPress()}
              >
                <Text style={[styles.menuOptionText, opt.danger && styles.menuOptionTextDanger]}>
                  {opt.label}
                </Text>
              </TouchableOpacity>
            ))}
          </View>
        </>
      )}
    </View>
  );
}

// ============================================================================
// STYLES
// ============================================================================
// HERA Design Rules:
// - Never use chip/pill selectors for option lists — use dropdowns
// - Always use spacing constants, never hardcoded values
// - All interactive UI must connect to backend — no decorative-only controls

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: heraLanding.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: heraLanding.background,
  },

  // Header
  header: {
    backgroundColor: colors.neutral.white,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: heraLanding.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: typography.fontSizes.xxxl,
    fontWeight: typography.fontWeights.bold,
    color: heraLanding.textPrimary,
    flex: 1,
    textAlign: 'center',
  },
  headerActions: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  headerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: heraLanding.primary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.lg,
    gap: spacing.xs,
    minHeight: touchTarget.minHeight,
  },
  headerBtnText: {
    color: colors.neutral.white,
    fontSize: typography.fontSizes.sm,
    fontWeight: typography.fontWeights.semibold,
  },

  // Scroll
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: spacing.lg,
    paddingBottom: spacing.xxxl,
    overflow: 'visible' as const,
  },
  scrollContentDesktop: {
    paddingHorizontal: spacing.xxxl,
  },

  // Stats
  statsRow: {
    flexDirection: 'row' as const,
    flexWrap: Platform.OS === 'web' ? 'nowrap' as const : 'wrap' as const,
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  statCard: {
    ...(Platform.OS === 'web'
      ? { flexGrow: 1, flexShrink: 1, flexBasis: 0, minWidth: 0, overflow: 'hidden' as const }
      : { width: '48%' as unknown as number }),
    backgroundColor: heraLanding.backgroundMuted,
    borderRadius: borderRadius.xl,
    padding: spacing.sm,
    gap: spacing.xs,
  },
  statValue: {
    fontSize: typography.fontSizes.xl,
    fontWeight: typography.fontWeights.medium,
    color: heraLanding.textPrimary,
  },
  statLabel: {
    fontSize: typography.fontSizes.sm,
    color: heraLanding.textSecondary,
  },
  statSublabel: {
    fontSize: typography.fontSizes.xs,
    color: heraLanding.textMuted,
  },

  // Desktop layout
  desktopColumns: {
    flexDirection: 'row',
    gap: spacing.lg,
    overflow: 'visible' as const,
  },
  mainColumn: {
    flex: 1,
    minWidth: 0,
  },
  sideColumn: {
    width: 340,
    gap: spacing.md,
    overflow: 'visible' as const,
    zIndex: 10,
  },

  // Card
  card: {
    backgroundColor: colors.neutral.white,
    borderRadius: borderRadius.xl,
    padding: spacing.xl,
    marginBottom: spacing.md,
    ...shadows.sm,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  cardTitle: {
    fontSize: typography.fontSizes.lg,
    fontWeight: typography.fontWeights.bold,
    color: heraLanding.textPrimary,
    marginBottom: spacing.sm,
  },
  editBtn: {
    fontSize: typography.fontSizes.sm,
    color: heraLanding.primary,
    fontWeight: typography.fontWeights.semibold,
  },

  // Config display
  configValue: {
    fontSize: typography.fontSizes.md,
    fontWeight: typography.fontWeights.semibold,
    color: heraLanding.textPrimary,
    marginBottom: spacing.xs,
  },
  configDetail: {
    fontSize: typography.fontSizes.sm,
    color: heraLanding.textSecondary,
    marginBottom: spacing.xs,
  },
  configHint: {
    fontSize: typography.fontSizes.xs,
    color: heraLanding.textMuted,
    fontStyle: 'italic',
    marginTop: spacing.sm,
  },

  // Free badge
  freeBadge: {
    backgroundColor: heraLanding.secondaryMuted,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.md,
    alignSelf: 'flex-start',
    marginTop: spacing.sm,
  },
  freeBadgeText: {
    fontSize: typography.fontSizes.xs,
    fontWeight: typography.fontWeights.semibold,
    color: heraLanding.secondary,
  },

  // Filters
  filterRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.md,
    flexWrap: 'wrap',
  },
  filterChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
    backgroundColor: heraLanding.backgroundMuted,
    justifyContent: 'center',
  },
  filterChipActive: {
    backgroundColor: heraLanding.primary,
  },
  filterChipText: {
    fontSize: typography.fontSizes.sm,
    color: heraLanding.textSecondary,
    fontWeight: typography.fontWeights.medium,
  },
  filterChipTextActive: {
    color: colors.neutral.white,
  },

  // Search
  searchInput: {
    backgroundColor: heraLanding.backgroundMuted,
    borderRadius: borderRadius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: typography.fontSizes.sm,
    color: heraLanding.textPrimary,
    marginBottom: spacing.md,
  },

  // Invoice row
  invoiceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: heraLanding.borderLight,
    minHeight: touchTarget.minHeight,
  },
  invoiceInfo: {
    flex: 1,
    gap: spacing.xs,
  },
  invoiceNumber: {
    fontSize: typography.fontSizes.sm,
    fontWeight: typography.fontWeights.semibold,
    color: heraLanding.textPrimary,
  },
  invoiceClient: {
    fontSize: typography.fontSizes.sm,
    color: heraLanding.textSecondary,
  },
  invoiceDate: {
    fontSize: typography.fontSizes.xs,
    color: heraLanding.textMuted,
  },
  invoiceRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  invoiceAmount: {
    fontSize: typography.fontSizes.sm,
    fontWeight: typography.fontWeights.bold,
    color: heraLanding.textPrimary,
  },
  invoiceActions: {
    flexDirection: 'row',
    gap: spacing.xs,
    alignItems: 'center',
  },
  iconBtn: {
    padding: spacing.xs,
    minWidth: touchTarget.minWidth - 8,
    minHeight: touchTarget.minHeight - 8,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Three-dot menu (portal — rendered at root level)
  menuBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2000,
  },
  menuDropdown: {
    position: 'absolute',
    backgroundColor: colors.neutral.white,
    borderWidth: 1,
    borderColor: heraLanding.border,
    borderRadius: borderRadius.lg,
    zIndex: 2001,
    minWidth: 160,
    ...shadows.md,
    elevation: 20,
    ...(Platform.OS === 'web' ? { boxShadow: '0 4px 12px rgba(0,0,0,0.15)' } as Record<string, string> : {}),
  },
  menuOption: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  menuOptionText: {
    fontSize: typography.fontSizes.sm,
    color: heraLanding.textPrimary,
  },
  menuOptionTextDanger: {
    color: colors.feedback.error,
  },

  // Badge
  badge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
  },
  badgeText: {
    fontSize: typography.fontSizes.xs,
    fontWeight: typography.fontWeights.semibold,
  },

  // Empty state
  emptyState: {
    alignItems: 'center',
    paddingVertical: spacing.xxxl,
    gap: spacing.sm,
  },
  emptyTitle: {
    fontSize: typography.fontSizes.md,
    fontWeight: typography.fontWeights.semibold,
    color: heraLanding.textPrimary,
    textAlign: 'center',
  },
  emptyDesc: {
    fontSize: typography.fontSizes.sm,
    color: heraLanding.textSecondary,
    textAlign: 'center',
    maxWidth: 300,
  },

  // Edit form
  editForm: {
    gap: spacing.sm,
    overflow: 'visible' as const,
  },
  formGroup: {
    marginBottom: spacing.sm,
    zIndex: 100,
    overflow: 'visible' as const,
  },
  fieldLabel: {
    fontSize: typography.fontSizes.sm,
    fontWeight: typography.fontWeights.semibold,
    color: heraLanding.textPrimary,
    marginBottom: spacing.xs,
  },
  input: {
    backgroundColor: heraLanding.backgroundMuted,
    borderWidth: 1,
    borderColor: heraLanding.border,
    borderRadius: borderRadius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: typography.fontSizes.sm,
    color: heraLanding.textPrimary,
  },
  chipRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  selectChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
    backgroundColor: heraLanding.backgroundMuted,
    borderWidth: 1,
    borderColor: heraLanding.border,
  },
  selectChipActive: {
    backgroundColor: heraLanding.primary,
    borderColor: heraLanding.primary,
  },
  selectChipText: {
    fontSize: typography.fontSizes.sm,
    color: heraLanding.textSecondary,
  },
  selectChipTextActive: {
    color: colors.neutral.white,
    fontWeight: typography.fontWeights.semibold,
  },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: touchTarget.minHeight,
  },
  saveBtn: {
    backgroundColor: heraLanding.primary,
    borderRadius: borderRadius.lg,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: touchTarget.minHeight,
    marginTop: spacing.sm,
  },
  saveBtnText: {
    color: colors.neutral.white,
    fontSize: typography.fontSizes.sm,
    fontWeight: typography.fontWeights.bold,
  },

  // Automation
  automationItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: heraLanding.borderLight,
    minHeight: touchTarget.minHeight,
  },
  automationText: {
    flex: 1,
    marginRight: spacing.md,
  },
  automationLabel: {
    fontSize: typography.fontSizes.sm,
    fontWeight: typography.fontWeights.semibold,
    color: heraLanding.textPrimary,
  },
  automationDesc: {
    fontSize: typography.fontSizes.xs,
    color: heraLanding.textMuted,
    marginTop: spacing.xs,
  },

  // Tariff editor
  tariffEditRow: {
    backgroundColor: heraLanding.backgroundMuted,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginBottom: spacing.sm,
    overflow: 'visible' as const,
    zIndex: 100,
  },
  tariffEditFields: {
    gap: spacing.sm,
    overflow: 'visible' as const,
  },
  tariffPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    flexWrap: 'wrap',
  },
  tariffToggles: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  tariffToggle: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    backgroundColor: heraLanding.backgroundMuted,
    borderWidth: 1,
    borderColor: heraLanding.border,
  },
  tariffToggleActive: {
    backgroundColor: heraLanding.primaryMuted,
    borderColor: heraLanding.primary,
  },
  tariffToggleInactive: {
    backgroundColor: heraLanding.warningLight,
    borderColor: heraLanding.warningAmber,
  },
  tariffToggleText: {
    fontSize: typography.fontSizes.xs,
    color: heraLanding.textSecondary,
    fontWeight: typography.fontWeights.medium,
  },
  tariffToggleTextActive: {
    color: heraLanding.primary,
    fontWeight: typography.fontWeights.semibold,
  },
  tariffToggleTextInactive: {
    color: heraLanding.warningAmber,
  },
  tariffDisplayRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  defaultBadgeInline: {
    fontSize: typography.fontSizes.xs,
    color: heraLanding.primary,
    fontWeight: typography.fontWeights.semibold,
  },
  addTariffBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.sm,
    alignSelf: 'flex-start',
  },
  addTariffBtnText: {
    fontSize: typography.fontSizes.sm,
    color: heraLanding.primary,
    fontWeight: typography.fontWeights.semibold,
  },
  selectChipSmall: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    backgroundColor: heraLanding.backgroundMuted,
    borderWidth: 1,
    borderColor: heraLanding.border,
  },
  fieldHint: {
    fontSize: typography.fontSizes.xs,
    color: heraLanding.textMuted,
    fontStyle: 'italic',
  },

});
