import React, { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  TextInput,
  ActivityIndicator,
  Image,
  Switch,
  Platform,
  Pressable,
  useWindowDimensions,
} from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import * as ImagePicker from 'expo-image-picker';
import { useNavigation, useFocusEffect } from '@react-navigation/native';
import { colors, spacing, borderRadius, typography, shadows, touchTarget } from '../../constants/colors';
import { Theme } from '../../constants/theme';
import { AppNavigationProp } from '../../constants/types';
import { AnimatedPressable, Button } from '../../components/common';
import { showAppAlert, useAppAlert } from '../../components/common/alert';
import { SimpleDropdown } from '../../components/common/SimpleDropdown';
import { useAuth } from '../../contexts/AuthContext';
import { useTheme } from '../../contexts/ThemeContext';
import {
  billingService,
  BillingSummary,
  Invoice,
  InvoiceStatus,
  InvoiceFilters,
  BillingConfig,
  TariffsConfig,
  TariffItem,
} from '../../services/billingService';
import * as analyticsService from '../../services/analyticsService';

// ============================================================================
// CONSTANTS
// ============================================================================

const STRINGS = {
  title: 'Facturación',
  exportMonth: 'Exportar mes',
  newInvoice: ' Nueva factura',
  thisMonth: 'Cobrado este mes',
  thisYear: 'Cobrado este año',
  invoicesMonth: 'Facturas emitidas',
  pendingSend: 'Pendientes de envío',
  invoiceHistory: 'Historial de facturas',
  tariffs: 'Tarifas',
  fiscalData: 'Datos fiscales',
  numbering: 'Numeración',
  automation: 'Automatización',
  edit: 'Editar',
  save: 'Guardar',
  cancel: 'Cancelar',
  all: 'Todas',
  sent: 'Enviadas',
  drafts: 'Borradores',
  cancelled: 'Canceladas',
  searchClient: 'Buscar cliente...',
  pricePerSession: 'Precio por sesión',
  sessionDuration: 'Duración de sesión',
  firstSessionFree: 'Primera sesión gratuita',
  firstSessionBadge: 'Primera sesión: Gratis',
  fiscalName: 'Nombre fiscal',
  nif: 'NIF',
  fiscalAddress: 'Dirección fiscal',
  vat: 'IVA',
  logo: 'Logo factura',
  addLogo: '+ Logo',
  bankAccount: 'IBAN',
  paymentConditions: 'Condiciones de pago',
  invoicePrefix: 'Prefijo',
  nextNumber: 'Siguiente número',
  previewFormat: 'Formato: ',
  adjustNote: 'Puedes ajustar el número al migrar desde otro sistema',
  autoGenerate: 'Generar facturas automáticamente',
  autoGenerateDesc: 'Al completar una sesión',
  autoSend: 'Enviar al cliente automáticamente',
  autoSendDesc: 'Tras generar la factura',
  emailCopy: 'Copia de factura por email',
  emailCopyDesc: 'Recibir copia en tu email',
  emptyTitle: 'Aún no has emitido ninguna factura',
  emptyDesc: 'Las facturas se generarán automáticamente al completar sesiones si activas la automatización.',
  generateInvoice: 'Generar factura',
  sendNow: 'Enviar ahora',
  saveDraft: 'Guardar borrador',
  selectClient: 'Seleccionar cliente',
  selectSession: 'Sesión (opcional)',
  concept: 'Concepto',
  amount: 'Importe',
  date: 'Fecha',
  invoiceNumber: 'N.º factura',
  confirmSend: '¿Enviar esta factura al cliente?',
  confirmCancel: '¿Cancelar esta factura?',
  resend: 'Volver a enviar',
  markAsPaid: 'Marcar como pagada',
  markAsPaidConfirm: '¿Marcar esta factura como pagada?',
  markAsPaidSuccess: 'Factura marcada como pagada',
  paid: 'Pagadas',
  deleteDraft: 'Eliminar borrador',
  deleteInvoice: 'Eliminar',
  deleteConfirmTitle: '¿Eliminar factura?',
  deleteConfirmMsg: 'Esta acción no se puede deshacer. La factura {number} será eliminada permanentemente.',
  deleteConfirm2Title: 'Confirmar eliminación',
  deleteConfirm2Msg: '¿Estás seguro? La factura {number} desaparecerá del historial.',
  deleteConfirm2Btn: 'Eliminar definitivamente',
  continueBtn: 'Continuar',
  cancelDraftAction: 'Cancelar borrador',
  cancelInvoiceAction: 'Cancelar factura',
  cancelConfirmTitleSafe: '¿Cancelar factura?',
  cancelConfirmMsgSafe: 'La factura {number} pasará a estado cancelada y seguirá visible en el historial.',
  cancelConfirm2TitleSafe: 'Confirmar cancelación',
  cancelConfirm2MsgSafe: 'Si continúas, la factura {number} ya no podrá enviarse ni marcarse como pagada.',
  cancelConfirm2BtnSafe: 'Cancelar factura',
  resendConfirmMsg: '¿Reenviar factura {number} a {client}?',
  resendBtn: 'Reenviar',
  resendSuccess: 'Factura reenviada correctamente',
  pageOf: 'Página {current} de {total}',
  invoicesTotal: '{total} facturas en total',
};

const VAT_OPTIONS = [
  { value: 0, label: 'Exento (Art. 20)' },
  { value: 10, label: '10%' },
  { value: 21, label: '21%' },
];

const SLOT_OPTIONS = [
  { value: 30, label: '30 min' },
  { value: 45, label: '45 min' },
  { value: 60, label: '60 min' },
  { value: 90, label: '90 min' },
  { value: 120, label: '120 min' },
];

const getStatusColors = (theme: Theme): Record<InvoiceStatus, { bg: string; text: string; label: string }> => ({
  SENT: { bg: theme.successLight, text: theme.success, label: 'Enviada' },
  PAID: { bg: theme.status.confirmed.bg, text: theme.status.confirmed.text, label: 'Pagada' },
  DRAFT: { bg: theme.warningBg, text: theme.warningAmber, label: 'Borrador' },
  CANCELLED: { bg: theme.status.cancelled.bg, text: theme.status.cancelled.text, label: 'Cancelada' },
});

const INVOICES_PER_PAGE = 10;
const SEARCH_DEBOUNCE_MS = 300;
const DEFAULT_INVOICE_ACCENT_COLOR = '#8B9D83';
const INVOICE_ACCENT_COLOR_REGEX = /^#[0-9A-Fa-f]{6}$/;
const INVOICE_ACCENT_OPTIONS = ['#8B9D83', '#4F7C8A', '#8A6F4F', '#7B6EA8', '#A56565'];

type FilterTab = 'all' | InvoiceStatus;

const MONTH_NAMES_ES = [
  'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
];
const MONTH_ABBREV_ES = [
  'Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun',
  'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic',
];

const formatCurrency = (amount: number): string => {
  return `€${amount.toLocaleString('es-ES', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

const formatDateShort = (dateStr: string): string => {
  return new Date(dateStr).toLocaleDateString('es-ES', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  });
};

const normalizeInvoicePrefixInput = (value: string): string =>
  value.toUpperCase().replace(/\s+/g, '').replace(/[^A-Z0-9._/-]/g, '').slice(0, 10);

const normalizeInvoiceAccentInput = (value: string): string =>
  value.trim().toUpperCase();

// ============================================================================
// SUB-COMPONENTS
// ============================================================================

interface StatCardProps {
  value: string;
  label: string;
  sublabel: string;
  styles: ReturnType<typeof createStyles>;
}

const StatCard: React.FC<StatCardProps> = ({ value, label, sublabel, styles }) => (
  <View style={styles.statCard}>
    <Text style={styles.statValue} numberOfLines={1}>{value}</Text>
    <Text style={styles.statLabel} numberOfLines={1}>{label}</Text>
    <Text style={styles.statSublabel} numberOfLines={1}>{sublabel}</Text>
  </View>
);

interface StatusBadgeProps {
  status: InvoiceStatus;
  styles: ReturnType<typeof createStyles>;
  theme: Theme;
}

const InvoiceStatusBadge: React.FC<StatusBadgeProps> = ({ status, styles, theme }) => {
  const config = getStatusColors(theme)[status];
  return (
    <View style={[styles.badge, { backgroundColor: config.bg }]}>
      <Text style={[styles.badgeText, { color: config.text }]}>{config.label}</Text>
    </View>
  );
};


// ============================================================================
// MAIN COMPONENT
// ============================================================================

export function BillingScreen() {
  const { user } = useAuth();
  const appAlert = useAppAlert();
  const { width } = useWindowDimensions();
  const { theme, isDark } = useTheme();
  const styles = useMemo(() => createStyles(theme, isDark), [theme, isDark]);
  const isDesktop = width >= 768;

  // Data state
  const [summary, setSummary] = useState<BillingSummary | null>(null);
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);
  const [invoicesLoading, setInvoicesLoading] = useState(false);

  // Pagination state
  const [currentPage, setCurrentPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [totalInvoices, setTotalInvoices] = useState(0);

  // Specialist billing config (loaded from API)
  const [billingConfig, setBillingConfig] = useState<BillingConfig>({});
  const [tariffItems, setTariffItems] = useState<TariffItem[]>([]);
  const [firstVisitFree, setFirstVisitFree] = useState(false);

  // Filter state
  const [activeFilter, setActiveFilter] = useState<FilterTab>('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [debouncedSearch, setDebouncedSearch] = useState('');
  const searchTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const invoiceListRef = useRef<View>(null);

  // Menu state (portal pattern — window-relative coordinates)
  const [openMenuId, setOpenMenuId] = useState<string | null>(null);
  const [menuPosition, setMenuPosition] = useState<{ top: number; right: number }>({ top: 0, right: 0 });
  const menuButtonRefs = useRef<Record<string, View | null>>({});

  // Edit state
  const [editingTariffs, setEditingTariffs] = useState(false);
  const [editingFiscal, setEditingFiscal] = useState(false);
  const [editingNumbering, setEditingNumbering] = useState(false);
  const [uploadingInvoiceLogo, setUploadingInvoiceLogo] = useState(false);
  const [savingInvoiceDesign, setSavingInvoiceDesign] = useState(false);
  const [numberingError, setNumberingError] = useState<string | null>(null);
  // Temp edit values
  const [tempTariffItems, setTempTariffItems] = useState<TariffItem[]>([]);
  const [tempFirstVisitFree, setTempFirstVisitFree] = useState(false);
  const [tempFiscal, setTempFiscal] = useState<BillingConfig>({});
  const [tempInvoiceAccentColor, setTempInvoiceAccentColor] = useState(DEFAULT_INVOICE_ACCENT_COLOR);
  const [tempNumbering, setTempNumbering] = useState({
    simplifiedInvoicePrefix: 'FS',
    simplifiedInvoiceNextNumber: 1,
    fullInvoicePrefix: 'F',
    fullInvoiceNextNumber: 1,
  });

  const navigation = useNavigation<AppNavigationProp>();

  // Action loading states
  const [sendingId, setSendingId] = useState<string | null>(null);
  const [savingConfig, setSavingConfig] = useState(false);


  // ── Load invoices (paginated) ────────────────────────────────
  const loadInvoices = useCallback(async (page: number, filter: FilterTab, clientName: string) => {
    try {
      setInvoicesLoading(true);
      const filters: InvoiceFilters = {
        page,
        limit: INVOICES_PER_PAGE,
      };
      if (filter !== 'all') {
        filters.status = filter;
      }
      if (clientName.trim()) {
        filters.clientName = clientName.trim();
      }
      const result = await billingService.getInvoices(filters);
      setInvoices(result.invoices);
      setTotalPages(result.totalPages);
      setTotalInvoices(result.total);
      setCurrentPage(result.page);
    } catch (error) {
      showAppAlert(appAlert, 'Error', error instanceof Error ? error.message : 'Error al cargar facturas');
    } finally {
      setInvoicesLoading(false);
    }
  }, []);

  // ── Load data ────────────────────────────────────────────────
  const loadData = useCallback(async () => {
    try {
      setLoading(true);
      const [summaryData] = await Promise.all([
        billingService.getSummary(),
        loadInvoices(1, 'all', ''),
      ]);
      setSummary(summaryData);
    } catch (error) {
      showAppAlert(appAlert, 'Error', error instanceof Error ? error.message : 'Error al cargar datos');
    } finally {
      setLoading(false);
    }
  }, [loadInvoices]);

  useFocusEffect(
    useCallback(() => {
      loadData();
      analyticsService.trackScreen('billing');
    }, [loadData])
  );

  // ── Debounced search ───────────────────────────────────────
  useEffect(() => {
    if (searchTimerRef.current) {
      clearTimeout(searchTimerRef.current);
    }
    searchTimerRef.current = setTimeout(() => {
      setDebouncedSearch(searchQuery);
    }, SEARCH_DEBOUNCE_MS);
    return () => {
      if (searchTimerRef.current) {
        clearTimeout(searchTimerRef.current);
      }
    };
  }, [searchQuery]);

  // ── Fetch when filter/search/page changes ──────────────────
  const initialLoadDone = useRef(false);
  useEffect(() => {
    if (!loading && initialLoadDone.current) {
      loadInvoices(currentPage, activeFilter, debouncedSearch);
    }
    if (!loading) {
      initialLoadDone.current = true;
    }
  }, [currentPage, activeFilter, debouncedSearch, loadInvoices, loading]);

  // Load specialist billing config from API
  const loadConfig = useCallback(async () => {
    try {
      const s = await billingService.getConfig();
      const config: BillingConfig = {
        invoicePrefix: s.invoicePrefix || 'F',
        invoiceNextNumber: s.invoiceNextNumber || 1,
        simplifiedInvoicePrefix: s.simplifiedInvoicePrefix || 'FS',
        simplifiedInvoiceNextNumber: s.simplifiedInvoiceNextNumber || 1,
        fullInvoicePrefix: s.fullInvoicePrefix || 'F',
        fullInvoiceNextNumber: s.fullInvoiceNextNumber || 1,
        vatRate: s.vatRate ?? 21,
        applyVat: s.applyVat ?? false,
        vatExemptReason: s.vatExemptReason || null,
        invoiceLogoUrl: s.invoiceLogoUrl || null,
        invoiceAccentColor: s.invoiceAccentColor || DEFAULT_INVOICE_ACCENT_COLOR,
        bankIban: s.bankIban || '',
        paymentConditions: s.paymentConditions || '',
        fiscalName: s.fiscalName || '',
        fiscalAddress: s.fiscalAddress || '',
        fiscalNif: s.fiscalNif || '',
        autoGenerateInvoice: s.autoGenerateInvoice || false,
        autoSendToClient: s.autoSendToClient || false,
        sendInvoiceCopyTo: s.sendInvoiceCopyTo || null,
      };
      setBillingConfig(config);
      setTempFiscal(config);
      setTempInvoiceAccentColor(config.invoiceAccentColor || DEFAULT_INVOICE_ACCENT_COLOR);
      setTempNumbering({
        simplifiedInvoicePrefix: config.simplifiedInvoicePrefix || 'FS',
        simplifiedInvoiceNextNumber: config.simplifiedInvoiceNextNumber || 1,
        fullInvoicePrefix: config.fullInvoicePrefix || 'F',
        fullInvoiceNextNumber: config.fullInvoiceNextNumber || 1,
      });

      // Parse tariffs: use JSON array if available, otherwise build from scalar fields
      const parsedTariffs: TariffItem[] = (s.tariffs && Array.isArray(s.tariffs) && s.tariffs.length > 0)
        ? (s.tariffs as TariffItem[])
        : [{
            id: '1',
            name: 'Sesión individual',
            price: s.pricePerSession || 0,
            durationMinutes: s.slotDuration || 60,
            isDefault: true,
            isActive: true,
          }];
      setTariffItems(parsedTariffs);
      setTempTariffItems(parsedTariffs);
      setFirstVisitFree(s.firstVisitFree || false);
      setTempFirstVisitFree(s.firstVisitFree || false);

      // Default tariff is now used in CreateInvoiceScreen
    } catch {
      // Config loading failed — defaults are already set
    }
  }, []);

  useEffect(() => {
    loadConfig();
  }, [loadConfig]);

  // ── Filter/search change handlers ───────────────────────────
  const handleFilterChange = useCallback((filter: FilterTab) => {
    setActiveFilter(filter);
    setCurrentPage(1);
  }, []);

  const handleSearchChange = useCallback((text: string) => {
    setSearchQuery(text);
    setCurrentPage(1);
  }, []);

  const handlePageChange = useCallback((page: number) => {
    setCurrentPage(page);
  }, []);

  // ── Actions ──────────────────────────────────────────────────
  const handleSendInvoice = async (invoiceId: string) => {
    const invoice = invoices.find((inv) => inv.id === invoiceId);
    const clientName = invoice?.client?.user?.name || 'el cliente';
    const invoiceNumber = invoice?.invoiceNumber || '';

    const executeSend = async () => {
      try {
        setSendingId(invoiceId);
        await billingService.sendInvoice(invoiceId);
        await loadInvoices(currentPage, activeFilter, debouncedSearch);
        showAppAlert(appAlert, 'Éxito', 'Factura enviada correctamente');
      } catch (error) {
        const msg = error instanceof Error ? error.message : 'Error al enviar la factura';
        showAppAlert(appAlert, 'Error', msg);
      } finally {
        setSendingId(null);
      }
    };

    const confirmed = await appAlert.confirm({
      title: '¿Enviar factura?',
      message: `Se enviará la factura ${invoiceNumber} a ${clientName}. ¿Continuar?`,
      confirmLabel: 'Enviar',
    });
    if (confirmed) {
      void executeSend();
    }
  };

  const handleDownload = async (invoiceId: string, invoiceNumber: string) => {
    try {
      await billingService.downloadInvoice(invoiceId, invoiceNumber);
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Error al descargar';
      showAppAlert(appAlert, 'Error', msg);
    }
  };

  const handleResendInvoice = async (invoice: Invoice) => {
    setOpenMenuId(null);
    const clientName = invoice.client?.user?.name || 'el cliente';
    const confirmMsg = STRINGS.resendConfirmMsg
      .replace('{number}', invoice.invoiceNumber)
      .replace('{client}', clientName);

    const executeResend = async () => {
      try {
        setSendingId(invoice.id);
        await billingService.sendInvoice(invoice.id);
        await loadInvoices(currentPage, activeFilter, debouncedSearch);
        billingService.getSummary().then(setSummary).catch(() => {});
        showAppAlert(appAlert, 'Éxito', STRINGS.resendSuccess);
      } catch (error) {
        const msg = error instanceof Error ? error.message : 'Error al reenviar';
        showAppAlert(appAlert, 'Error', msg);
      } finally {
        setSendingId(null);
      }
    };

    const confirmed = await appAlert.confirm({
      title: STRINGS.resend,
      message: confirmMsg,
      confirmLabel: STRINGS.resendBtn,
    });
    if (confirmed) {
      void executeResend();
    }
  };

  const handleMarkAsPaid = async (invoice: Invoice) => {
    setOpenMenuId(null);

    const executeMark = async () => {
      try {
        setSendingId(invoice.id);
        await billingService.markInvoiceAsPaid(invoice.id);
        await loadInvoices(currentPage, activeFilter, debouncedSearch);
        billingService.getSummary().then(setSummary).catch(() => {});
        showAppAlert(appAlert, 'Éxito', STRINGS.markAsPaidSuccess);
      } catch (error: unknown) {
        const msg = error instanceof Error ? error.message : 'Error al marcar como pagada';
        showAppAlert(appAlert, 'Error', msg);
      } finally {
        setSendingId(null);
      }
    };

    const confirmed = await appAlert.confirm({
      title: STRINGS.markAsPaid,
      message: STRINGS.markAsPaidConfirm,
      confirmLabel: 'Confirmar',
    });
    if (confirmed) {
      void executeMark();
    }
  };

  const handleCancelInvoice = async (invoice: Invoice) => {
    setOpenMenuId(null);
    const msg1 = STRINGS.cancelConfirmMsgSafe.replace('{number}', invoice.invoiceNumber);
    const msg2 = STRINGS.cancelConfirm2MsgSafe.replace('{number}', invoice.invoiceNumber);

    const executeDelete = async () => {
      try {
        await billingService.cancelInvoice(invoice.id);
        await loadInvoices(currentPage, activeFilter, debouncedSearch);
        billingService.getSummary().then(setSummary).catch(() => {});
      } catch (error) {
        const errMsg = error instanceof Error ? error.message : 'Error al cancelar';
        showAppAlert(appAlert, 'Error', errMsg);
      }
    };

    const firstConfirmed = await appAlert.confirm({
      title: STRINGS.cancelConfirmTitleSafe,
      message: msg1,
      confirmLabel: STRINGS.continueBtn,
      tone: 'warning',
    });
    if (!firstConfirmed) return;

    const secondConfirmed = await appAlert.confirm({
      title: STRINGS.cancelConfirm2TitleSafe,
      message: msg2,
      confirmLabel: STRINGS.cancelConfirm2BtnSafe,
      destructive: true,
    });
    if (secondConfirmed) {
      void executeDelete();
    }
  };

  const handleSaveTariffs = async () => {
    const defaults = tempTariffItems.filter((t) => t.isDefault);
    if (defaults.length !== 1) {
      showAppAlert(appAlert, 'Error', 'Debe haber exactamente una tarifa por defecto');
      return;
    }
    const actives = tempTariffItems.filter((t) => t.isActive);
    if (actives.length === 0) {
      showAppAlert(appAlert, 'Error', 'Debe haber al menos una tarifa activa');
      return;
    }
    try {
      setSavingConfig(true);
      await billingService.updateTariffs({ tariffs: tempTariffItems, firstVisitFree: tempFirstVisitFree });
      setTariffItems(tempTariffItems);
      setFirstVisitFree(tempFirstVisitFree);
      setEditingTariffs(false);
      showAppAlert(appAlert, 'Éxito', 'Tarifas actualizadas');
    } catch (error) {
      showAppAlert(appAlert, 'Error', error instanceof Error ? error.message : 'Error al guardar');
    } finally {
      setSavingConfig(false);
    }
  };

  const handleSaveFiscal = async () => {
    try {
      setSavingConfig(true);
      await billingService.updateBillingConfig(tempFiscal);
      setBillingConfig((prev) => ({ ...prev, ...tempFiscal }));
      setEditingFiscal(false);
      showAppAlert(appAlert, 'Éxito', 'Datos fiscales actualizados');
    } catch (error) {
      showAppAlert(appAlert, 'Error', error instanceof Error ? error.message : 'Error al guardar');
    } finally {
      setSavingConfig(false);
    }
  };

  const handlePickInvoiceLogo = async () => {
    try {
      const permission = await ImagePicker.requestMediaLibraryPermissionsAsync();
      if (!permission.granted) {
        showAppAlert(appAlert, 'Permiso necesario', 'Necesitamos acceso a tus imágenes para seleccionar el logo.');
        return;
      }

      const result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        allowsEditing: true,
        quality: 0.9,
      });

      if (result.canceled || result.assets.length === 0) {
        return;
      }

      const asset = result.assets[0];
      setUploadingInvoiceLogo(true);
      const updated = await billingService.uploadInvoiceLogo({
        uri: asset.uri,
        mimeType: asset.mimeType,
        fileName: asset.fileName,
        file: asset.file ?? null,
      });
      setBillingConfig((prev) => ({
        ...prev,
        invoiceLogoUrl: updated.invoiceLogoUrl,
        invoiceAccentColor: updated.invoiceAccentColor || prev.invoiceAccentColor || DEFAULT_INVOICE_ACCENT_COLOR,
      }));
      showAppAlert(appAlert, 'Éxito', 'Logo de factura actualizado');
    } catch (error) {
      showAppAlert(appAlert, 'Error', error instanceof Error ? error.message : 'No se pudo subir el logo');
    } finally {
      setUploadingInvoiceLogo(false);
    }
  };

  const handleSaveInvoiceDesign = async () => {
    const normalizedColor = normalizeInvoiceAccentInput(tempInvoiceAccentColor);
    if (!INVOICE_ACCENT_COLOR_REGEX.test(normalizedColor)) {
      showAppAlert(appAlert, 'Color no válido', 'Introduce un color HEX de 6 dígitos, por ejemplo #8B9D83.');
      return;
    }

    try {
      setSavingInvoiceDesign(true);
      const updated = await billingService.updateBillingConfig({ invoiceAccentColor: normalizedColor });
      setBillingConfig((prev) => ({
        ...prev,
        invoiceAccentColor: updated.invoiceAccentColor || normalizedColor,
      }));
      setTempInvoiceAccentColor(updated.invoiceAccentColor || normalizedColor);
      showAppAlert(appAlert, 'Éxito', 'Diseño de factura actualizado');
    } catch (error) {
      showAppAlert(appAlert, 'Error', error instanceof Error ? error.message : 'Error al guardar');
    } finally {
      setSavingInvoiceDesign(false);
    }
  };

  const handleSaveNumbering = async () => {
    try {
      setSavingConfig(true);
      setNumberingError(null);
      const normalizedNumbering = {
        ...tempNumbering,
        simplifiedInvoicePrefix: normalizeInvoicePrefixInput(tempNumbering.simplifiedInvoicePrefix || 'FS'),
        fullInvoicePrefix: normalizeInvoicePrefixInput(tempNumbering.fullInvoicePrefix || 'F'),
      };
      if (normalizedNumbering.simplifiedInvoicePrefix === normalizedNumbering.fullInvoicePrefix) {
        setNumberingError('Las facturas completas y simplificadas deben usar prefijos distintos.');
        return;
      }
      await billingService.updateBillingConfig(normalizedNumbering);
      setTempNumbering(normalizedNumbering);
      setBillingConfig((prev) => ({ ...prev, ...normalizedNumbering }));
      setEditingNumbering(false);
      showAppAlert(appAlert, 'Éxito', 'Numeración actualizada');
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Error al guardar';
      setNumberingError(message);
      showAppAlert(appAlert, 'Error', message);
    } finally {
      setSavingConfig(false);
    }
  };

  const handleToggleAutomation = async (field: keyof BillingConfig, value: boolean) => {
    const prev = billingConfig[field];
    setBillingConfig((c) => ({ ...c, [field]: value }));
    try {
      await billingService.updateBillingConfig({ [field]: value });
    } catch (error) {
      // Revert on error
      setBillingConfig((c) => ({ ...c, [field]: prev }));
      showAppAlert(appAlert, 'Error', error instanceof Error ? error.message : 'Error al guardar');
    }
  };

  const handleToggleEmailCopy = async (enabled: boolean) => {
    const email = enabled ? (user?.email || null) : null;
    const prev = billingConfig.sendInvoiceCopyTo;
    setBillingConfig((c) => ({ ...c, sendInvoiceCopyTo: email }));
    try {
      await billingService.updateBillingConfig({ sendInvoiceCopyTo: email });
    } catch (error) {
      setBillingConfig((c) => ({ ...c, sendInvoiceCopyTo: prev }));
      showAppAlert(appAlert, 'Error', error instanceof Error ? error.message : 'Error al guardar');
    }
  };


  // ── Loading state ────────────────────────────────────────────
  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color={theme.primary} />
      </View>
    );
  }

  // ── Render helpers ───────────────────────────────────────────
  const renderStats = () => {
    const now = new Date();
    const monthIdx = now.getMonth();
    const year = now.getFullYear();
    const monthFull = `${MONTH_NAMES_ES[monthIdx]} ${year}`;
    const monthRange = `Ene — ${MONTH_ABBREV_ES[monthIdx]}`;

    return (
      <View style={styles.statsRow}>
        <StatCard value={formatCurrency(summary?.totalThisMonth ?? 0)} label={STRINGS.thisMonth} sublabel={monthFull} styles={styles} />
        <StatCard value={formatCurrency(summary?.totalThisYear ?? 0)} label={STRINGS.thisYear} sublabel={monthRange} styles={styles} />
        <StatCard value={String(summary?.invoiceCountThisMonth ?? 0)} label={STRINGS.invoicesMonth} sublabel="Este mes" styles={styles} />
        <StatCard value={String(summary?.pendingCount ?? 0)} label={STRINGS.pendingSend} sublabel="Requieren revisión" styles={styles} />
      </View>
    );
  };

  const renderFilterChips = () => {
    const filters: Array<{ key: FilterTab; label: string }> = [
      { key: 'all', label: STRINGS.all },
      { key: 'SENT', label: STRINGS.sent },
      { key: 'PAID', label: STRINGS.paid },
      { key: 'DRAFT', label: STRINGS.drafts },
      { key: 'CANCELLED', label: STRINGS.cancelled },
    ];
    return (
      <View style={styles.filterRow}>
        {filters.map((f) => (
          <AnimatedPressable
            key={f.key}
            style={activeFilter === f.key ? [styles.filterChip, styles.filterChipActive] : styles.filterChip}
            onPress={() => handleFilterChange(f.key)}
            hoverLift={false}
            pressScale={0.98}
          >
            <Text style={activeFilter === f.key ? [styles.filterChipText, styles.filterChipTextActive] : styles.filterChipText}>
              {f.label}
            </Text>
          </AnimatedPressable>
        ))}
      </View>
    );
  };

  const handleInvoiceRowPress = (invoice: Invoice) => {
    if (invoice.status === 'DRAFT') {
      navigation.navigate('CreateInvoice', { invoiceId: invoice.id });
    } else {
      handleDownload(invoice.id, invoice.invoiceNumber);
    }
  };

  const getMenuOptions = (invoice: Invoice): Array<{ label: string; onPress: () => void; danger?: boolean }> => {
    const options: Array<{ label: string; onPress: () => void; danger?: boolean }> = [];
    if (invoice.status === 'SENT' || (invoice.status === 'DRAFT' && invoice.sentAt)) {
      options.push({ label: STRINGS.resend, onPress: () => handleResendInvoice(invoice) });
    }
    if (invoice.status === 'SENT') {
      options.push({ label: STRINGS.markAsPaid, onPress: () => handleMarkAsPaid(invoice) });
    }
    if (invoice.status === 'DRAFT') {
      options.push({ label: STRINGS.cancelDraftAction, onPress: () => handleCancelInvoice(invoice), danger: true });
    } else if (invoice.status === 'SENT') {
      options.push({ label: STRINGS.cancelInvoiceAction, onPress: () => handleCancelInvoice(invoice), danger: true });
    }
    return options;
  };

  const handleOpenMenu = (invoiceId: string) => {
    const buttonRef = menuButtonRefs.current[invoiceId];
    if (buttonRef) {
      buttonRef.measure((_x, _y, w, h, pageX, pageY) => {
        setMenuPosition({
          top: pageY + h + 4,
          right: width - (pageX + w),
        });
        setOpenMenuId(invoiceId);
      });
    } else {
      setOpenMenuId(invoiceId);
    }
  };

  const renderInvoiceRow = (invoice: Invoice) => {
    const menuOptions = getMenuOptions(invoice);

    return (
      <View key={invoice.id} style={styles.invoiceRow}>
        <Pressable
          style={styles.invoiceInfo}
          onPress={() => handleInvoiceRowPress(invoice)}
        >
          <Text style={styles.invoiceNumber}>{invoice.invoiceNumber}</Text>
          <Text style={styles.invoiceClient} numberOfLines={1}>
            {invoice.recipientFiscalName ||
              invoice.client.user?.name ||
              [invoice.client.firstName, invoice.client.lastName].filter(Boolean).join(' ') ||
              'Paciente'}
          </Text>
          <Text style={styles.invoiceDate}>
            {invoice.invoiceKind === 'FULL' ? 'Factura completa' : 'Factura simplificada'}
          </Text>
          <Text style={styles.invoiceDate}>{formatDateShort(invoice.createdAt)}</Text>
        </Pressable>
        <View style={styles.invoiceRight}>
          <Pressable onPress={() => handleInvoiceRowPress(invoice)}>
            <Text style={styles.invoiceAmount}>{formatCurrency(invoice.total)}</Text>
          </Pressable>
          <InvoiceStatusBadge status={invoice.status} styles={styles} theme={theme} />
          <View style={styles.invoiceActions}>
            <TouchableOpacity
              style={styles.iconBtn}
              onPress={() => handleDownload(invoice.id, invoice.invoiceNumber)}
              hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
            >
              <Ionicons name="download-outline" size={18} color={theme.textSecondary} />
            </TouchableOpacity>
            {invoice.status === 'DRAFT' && (
              <TouchableOpacity
                style={styles.iconBtn}
                onPress={() => handleSendInvoice(invoice.id)}
                disabled={sendingId === invoice.id}
                hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
              >
                {sendingId === invoice.id ? (
                  <ActivityIndicator size="small" color={theme.primary} />
                ) : (
                  <Ionicons name="send-outline" size={18} color={theme.primary} />
                )}
              </TouchableOpacity>
            )}
            {menuOptions.length > 0 && (
              <View
                ref={(ref) => { menuButtonRefs.current[invoice.id] = ref; }}
                collapsable={false}
              >
                <TouchableOpacity
                  style={styles.iconBtn}
                  onPress={() => {
                    if (openMenuId === invoice.id) {
                      setOpenMenuId(null);
                    } else {
                      handleOpenMenu(invoice.id);
                    }
                  }}
                  hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
                >
                  <Ionicons name="ellipsis-vertical" size={18} color={theme.textSecondary} />
                </TouchableOpacity>
              </View>
            )}
          </View>
        </View>
      </View>
    );
  };

  const renderPagination = () => {
    if (totalPages <= 1) return null;

    const isFirstPage = currentPage === 1;
    const isLastPage = currentPage === totalPages;

    return (
      <View style={styles.paginationContainer}>
        <View style={styles.paginationRow}>
          <TouchableOpacity
            style={[styles.paginationBtn, isFirstPage && styles.paginationBtnDisabled]}
            onPress={() => handlePageChange(currentPage - 1)}
            disabled={isFirstPage}
          >
            <Ionicons
              name="chevron-back"
              size={18}
              color={isFirstPage ? theme.textMuted : theme.textPrimary}
            />
          </TouchableOpacity>
          <Text style={styles.paginationLabel}>
            {STRINGS.pageOf
              .replace('{current}', String(currentPage))
              .replace('{total}', String(totalPages))}
          </Text>
          <TouchableOpacity
            style={[styles.paginationBtn, isLastPage && styles.paginationBtnDisabled]}
            onPress={() => handlePageChange(currentPage + 1)}
            disabled={isLastPage}
          >
            <Ionicons
              name="chevron-forward"
              size={18}
              color={isLastPage ? theme.textMuted : theme.textPrimary}
            />
          </TouchableOpacity>
        </View>
        <Text style={styles.paginationTotal}>
          {STRINGS.invoicesTotal.replace('{total}', String(totalInvoices))}
        </Text>
      </View>
    );
  };

  const renderInvoiceList = () => (
    <View style={styles.card}>
      <Text style={styles.cardTitle}>{STRINGS.invoiceHistory}</Text>
      {renderFilterChips()}
      <TextInput
        style={styles.searchInput}
        placeholder={STRINGS.searchClient}
        placeholderTextColor={theme.textMuted}
        value={searchQuery}
        onChangeText={handleSearchChange}
      />
      <View ref={invoiceListRef} style={invoicesLoading ? styles.invoiceListLoading : undefined}>
        {invoicesLoading && (
          <View style={styles.invoiceListOverlay}>
            <ActivityIndicator size="small" color={theme.primary} />
          </View>
        )}
        {invoices.length === 0 && !invoicesLoading ? (
          <View style={styles.emptyState}>
            <Ionicons name="document-text-outline" size={48} color={theme.textMuted} />
            <Text style={styles.emptyTitle}>{STRINGS.emptyTitle}</Text>
            <Text style={styles.emptyDesc}>{STRINGS.emptyDesc}</Text>
          </View>
        ) : (
          invoices.map(renderInvoiceRow)
        )}
      </View>
      {renderPagination()}
    </View>
  );

  const handleAddTariff = () => {
    setTempTariffItems((prev) => [...prev, {
      id: String(Date.now()),
      name: '',
      price: 0,
      durationMinutes: 60,
      isDefault: false,
      isActive: true,
    }]);
  };

  const handleUpdateTempTariff = (id: string, field: keyof TariffItem, value: string | number | boolean) => {
    setTempTariffItems((prev) => prev.map((t) => {
      if (t.id !== id) {
        // If setting this one as default, unset others
        if (field === 'isDefault' && value === true) return { ...t, isDefault: false };
        return t;
      }
      return { ...t, [field]: value };
    }));
  };

  const handleDeleteTempTariff = (id: string) => {
    if (tempTariffItems.length <= 1) {
      showAppAlert(appAlert, 'Error', 'Debe haber al menos una tarifa');
      return;
    }
    setTempTariffItems((prev) => prev.filter((t) => t.id !== id));
  };

  const renderTariffsCard = () => (
    <View style={[styles.card, { zIndex: 10, overflow: 'visible' as const }]}>
      <View style={styles.cardHeader}>
        <Text style={styles.cardTitle}>{STRINGS.tariffs}</Text>
        <TouchableOpacity onPress={() => {
          setTempTariffItems(tariffItems);
          setTempFirstVisitFree(firstVisitFree);
          setEditingTariffs(!editingTariffs);
        }}>
          <Text style={styles.editBtn}>{editingTariffs ? STRINGS.cancel : STRINGS.edit}</Text>
        </TouchableOpacity>
      </View>
      {editingTariffs ? (
        <View style={styles.editForm}>
          {tempTariffItems.map((tariff) => (
            <View key={tariff.id} style={styles.tariffEditRow}>
              <View style={styles.tariffEditFields}>
                <TextInput
                  style={[styles.input, { flex: 1 }]}
                  value={tariff.name}
                  onChangeText={(v) => handleUpdateTempTariff(tariff.id, 'name', v)}
                  placeholder="Nombre de la tarifa"
                  placeholderTextColor={theme.textMuted}
                />
                <View style={styles.tariffPriceRow}>
                  <TextInput
                    style={[styles.input, { width: 80 }]}
                    value={String(tariff.price)}
                    onChangeText={(v) => handleUpdateTempTariff(tariff.id, 'price', parseFloat(v) || 0)}
                    keyboardType="numeric"
                    placeholder="€"
                    placeholderTextColor={theme.textMuted}
                  />
                  <Text style={styles.fieldHint}>€</Text>
                </View>
                <View style={styles.formGroup}>
                  <SimpleDropdown
                    options={SLOT_OPTIONS.map((opt) => ({ label: opt.label, value: opt.value }))}
                    value={tariff.durationMinutes}
                    onSelect={(v) => handleUpdateTempTariff(tariff.id, 'durationMinutes', v)}
                    placeholder="Duración..."
                  />
                </View>
                <View style={styles.tariffToggles}>
                  <TouchableOpacity
                    style={[styles.tariffToggle, tariff.isDefault && styles.tariffToggleActive]}
                    onPress={() => handleUpdateTempTariff(tariff.id, 'isDefault', true)}
                  >
                    <Text style={[styles.tariffToggleText, tariff.isDefault && styles.tariffToggleTextActive]}>
                      Por defecto
                    </Text>
                  </TouchableOpacity>
                  {tempTariffItems.length > 1 && (
                    <TouchableOpacity onPress={() => handleDeleteTempTariff(tariff.id)}>
                      <Ionicons name="trash-outline" size={18} color={theme.warning} />
                    </TouchableOpacity>
                  )}
                </View>
              </View>
            </View>
          ))}
          <TouchableOpacity style={styles.addTariffBtn} onPress={handleAddTariff}>
            <Ionicons name="add" size={16} color={theme.primary} />
            <Text style={styles.addTariffBtnText}>Añadir tarifa</Text>
          </TouchableOpacity>
          <View style={styles.switchRow}>
            <Text style={styles.fieldLabel}>{STRINGS.firstSessionFree}</Text>
            <Switch
              value={tempFirstVisitFree}
              onValueChange={setTempFirstVisitFree}
              trackColor={{ false: colors.neutral.gray300, true: theme.primaryMuted }}
              thumbColor={tempFirstVisitFree ? theme.primary : colors.neutral.gray400}
            />
          </View>
          <TouchableOpacity style={styles.saveBtn} onPress={handleSaveTariffs} disabled={savingConfig}>
            {savingConfig ? <ActivityIndicator size="small" color={colors.neutral.white} /> : (
              <Text style={styles.saveBtnText}>{STRINGS.save}</Text>
            )}
          </TouchableOpacity>
        </View>
      ) : (
        <View style={{ gap: spacing.sm }}>
          {tariffItems.filter((t) => t.isActive).map((tariff) => (
            <View key={tariff.id} style={styles.tariffDisplayRow}>
              <View style={{ flex: 1 }}>
                <Text style={styles.configValue}>
                  {tariff.name || 'Sin nombre'}
                  {tariff.isDefault && (
                    <Text style={styles.defaultBadgeInline}> (por defecto)</Text>
                  )}
                </Text>
                <Text style={styles.configDetail}>
                  {tariff.price === 0 ? 'Gratis' : formatCurrency(tariff.price)} · {tariff.durationMinutes} min
                </Text>
              </View>
            </View>
          ))}
          {tariffItems.some((t) => !t.isActive) && (
            <Text style={styles.configDetail}>
              +{tariffItems.filter((t) => !t.isActive).length} tarifa(s) inactiva(s)
            </Text>
          )}
          {firstVisitFree && (
            <View style={styles.freeBadge}>
              <Text style={styles.freeBadgeText}>{STRINGS.firstSessionBadge}</Text>
            </View>
          )}
        </View>
      )}
    </View>
  );

  const renderInvoiceDesignCard = () => {
    const currentAccent = billingConfig.invoiceAccentColor || DEFAULT_INVOICE_ACCENT_COLOR;

    return (
      <View style={styles.card}>
        <View style={styles.cardHeader}>
          <Text style={styles.cardTitle}>Diseño de factura</Text>
          <View style={[styles.invoiceAccentPreview, { backgroundColor: currentAccent }]} />
        </View>

        <View style={styles.invoiceLogoRow}>
          <View style={styles.invoiceLogoFrame}>
            {billingConfig.invoiceLogoUrl ? (
              <Image
                source={{ uri: billingConfig.invoiceLogoUrl }}
                style={styles.invoiceLogoPreview}
                resizeMode="contain"
              />
            ) : (
              <Ionicons name="image-outline" size={28} color={theme.textMuted} />
            )}
          </View>
          <Button
            variant="outline"
            size="small"
            onPress={handlePickInvoiceLogo}
            loading={uploadingInvoiceLogo}
            icon={<Ionicons name="cloud-upload-outline" size={16} color={theme.primary} />}
          >
            {billingConfig.invoiceLogoUrl ? 'Cambiar logo' : 'Subir logo'}
          </Button>
        </View>

        <Text style={styles.fieldLabel}>Color de detalle</Text>
        <View style={styles.invoiceColorSwatches}>
          {INVOICE_ACCENT_OPTIONS.map((option) => {
            const selected = tempInvoiceAccentColor.toUpperCase() === option;
            return (
              <TouchableOpacity
                key={option}
                style={[
                  styles.invoiceColorSwatch,
                  { backgroundColor: option },
                  selected && styles.invoiceColorSwatchSelected,
                ]}
                onPress={() => setTempInvoiceAccentColor(option)}
                accessibilityRole="button"
                accessibilityLabel={`Color ${option}`}
              />
            );
          })}
        </View>
        <TextInput
          style={styles.input}
          value={tempInvoiceAccentColor}
          onChangeText={setTempInvoiceAccentColor}
          placeholder={DEFAULT_INVOICE_ACCENT_COLOR}
          placeholderTextColor={theme.textMuted}
          autoCapitalize="characters"
          maxLength={7}
        />
        <TouchableOpacity
          style={[styles.saveBtn, savingInvoiceDesign && styles.saveBtnDisabled]}
          onPress={handleSaveInvoiceDesign}
          disabled={savingInvoiceDesign}
        >
          {savingInvoiceDesign ? <ActivityIndicator size="small" color={theme.textOnPrimary} /> : (
            <Text style={styles.saveBtnText}>{STRINGS.save}</Text>
          )}
        </TouchableOpacity>
      </View>
    );
  };

  const renderFiscalCard = () => (
    <View style={styles.card}>
      <View style={styles.cardHeader}>
        <Text style={styles.cardTitle}>{STRINGS.fiscalData}</Text>
        <TouchableOpacity onPress={() => { setTempFiscal(billingConfig); setEditingFiscal(!editingFiscal); }}>
          <Text style={styles.editBtn}>{editingFiscal ? STRINGS.cancel : STRINGS.edit}</Text>
        </TouchableOpacity>
      </View>
      {editingFiscal ? (
        <View style={styles.editForm}>
          <Text style={styles.fieldLabel}>{STRINGS.fiscalName}</Text>
          <TextInput style={styles.input} value={tempFiscal.fiscalName || ''} onChangeText={(v) => setTempFiscal((f) => ({ ...f, fiscalName: v }))} />
          <Text style={styles.fieldLabel}>{STRINGS.nif}</Text>
          <TextInput style={styles.input} value={tempFiscal.fiscalNif || ''} onChangeText={(v) => setTempFiscal((f) => ({ ...f, fiscalNif: v }))} />
          <Text style={styles.fieldLabel}>{STRINGS.fiscalAddress}</Text>
          <TextInput style={styles.input} value={tempFiscal.fiscalAddress || ''} onChangeText={(v) => setTempFiscal((f) => ({ ...f, fiscalAddress: v }))} />
          <Text style={styles.fieldLabel}>{STRINGS.vat}</Text>
          <SimpleDropdown
            options={VAT_OPTIONS.map((opt) => ({ label: opt.label, value: opt.value }))}
            value={tempFiscal.vatRate ?? 0}
            onSelect={(v) => setTempFiscal((f) => ({ ...f, vatRate: v, applyVat: v > 0 }))}
            placeholder="Seleccionar IVA..."
          />
          <Text style={styles.fieldLabel}>{STRINGS.bankAccount}</Text>
          <TextInput style={styles.input} value={tempFiscal.bankIban || ''} onChangeText={(v) => setTempFiscal((f) => ({ ...f, bankIban: v }))} />
          <Text style={styles.fieldLabel}>{STRINGS.paymentConditions}</Text>
          <TextInput style={styles.input} value={tempFiscal.paymentConditions || ''} onChangeText={(v) => setTempFiscal((f) => ({ ...f, paymentConditions: v }))} placeholder="Transferencia bancaria" placeholderTextColor={theme.textMuted} />
          <TouchableOpacity style={styles.saveBtn} onPress={handleSaveFiscal} disabled={savingConfig}>
            {savingConfig ? <ActivityIndicator size="small" color={colors.neutral.white} /> : (
              <Text style={styles.saveBtnText}>{STRINGS.save}</Text>
            )}
          </TouchableOpacity>
        </View>
      ) : (
        <View>
          {billingConfig.fiscalName ? <Text style={styles.configValue}>{billingConfig.fiscalName}</Text> : null}
          {billingConfig.fiscalNif ? <Text style={styles.configDetail}>NIF: {billingConfig.fiscalNif}</Text> : null}
          {billingConfig.fiscalAddress ? <Text style={styles.configDetail}>{billingConfig.fiscalAddress}</Text> : null}
          <Text style={styles.configDetail}>IVA: {VAT_OPTIONS.find((o) => o.value === (billingConfig.vatRate ?? 0))?.label || 'Exento'}</Text>
          {!billingConfig.fiscalName && !billingConfig.fiscalNif && (
            <Text style={styles.configHint}>Completa tus datos fiscales para las facturas</Text>
          )}
        </View>
      )}
    </View>
  );

  const renderNumberingCard = () => {
    const simplifiedPrefix = billingConfig.simplifiedInvoicePrefix || 'FS';
    const simplifiedNext = billingConfig.simplifiedInvoiceNextNumber || 1;
    const fullPrefix = billingConfig.fullInvoicePrefix || billingConfig.invoicePrefix || 'F';
    const fullNext = billingConfig.fullInvoiceNextNumber || billingConfig.invoiceNextNumber || 1;
    const year = new Date().getFullYear();
    const simplifiedPreview = `${simplifiedPrefix}-${year}-${String(simplifiedNext).padStart(3, '0')}`;
    const fullPreview = `${fullPrefix}-${year}-${String(fullNext).padStart(3, '0')}`;
    const editingSimplifiedPrefix = normalizeInvoicePrefixInput(tempNumbering.simplifiedInvoicePrefix || 'FS');
    const editingFullPrefix = normalizeInvoicePrefixInput(tempNumbering.fullInvoicePrefix || 'F');
    const hasDuplicatedSeries = editingNumbering && editingSimplifiedPrefix === editingFullPrefix;
    const visibleNumberingError = hasDuplicatedSeries
      ? 'Las facturas completas y simplificadas deben usar prefijos distintos.'
      : numberingError;
    const isNumberingSaveDisabled = savingConfig || hasDuplicatedSeries;

    return (
      <View style={styles.card}>
        <View style={styles.cardHeader}>
          <Text style={styles.cardTitle}>{STRINGS.numbering}</Text>
          <TouchableOpacity
            onPress={() => {
              setTempNumbering({
                simplifiedInvoicePrefix: simplifiedPrefix,
                simplifiedInvoiceNextNumber: simplifiedNext,
                fullInvoicePrefix: fullPrefix,
                fullInvoiceNextNumber: fullNext,
              });
              setNumberingError(null);
              setEditingNumbering(!editingNumbering);
            }}
          >
            <Text style={styles.editBtn}>{editingNumbering ? STRINGS.cancel : STRINGS.edit}</Text>
          </TouchableOpacity>
        </View>
        {editingNumbering ? (
          <View style={styles.editForm}>
            <Text style={styles.fieldLabel}>Serie simplificada · prefijo</Text>
            <TextInput
              style={[styles.input, hasDuplicatedSeries && styles.inputError, { maxWidth: 100 }]}
              value={tempNumbering.simplifiedInvoicePrefix}
              onChangeText={(v) =>
                setTempNumbering((n) => ({
                  ...n,
                  simplifiedInvoicePrefix: normalizeInvoicePrefixInput(v),
                }))
              }
              maxLength={10}
              autoCapitalize="characters"
            />
            <Text style={styles.fieldLabel}>Serie simplificada · siguiente número</Text>
            <TextInput
              style={[styles.input, { maxWidth: 120 }]}
              value={String(tempNumbering.simplifiedInvoiceNextNumber)}
              onChangeText={(v) =>
                setTempNumbering((n) => ({ ...n, simplifiedInvoiceNextNumber: parseInt(v, 10) || 1 }))
              }
              keyboardType="numeric"
            />
            <Text style={styles.fieldLabel}>Serie completa · prefijo</Text>
            <TextInput
              style={[styles.input, hasDuplicatedSeries && styles.inputError, { maxWidth: 100 }]}
              value={tempNumbering.fullInvoicePrefix}
              onChangeText={(v) =>
                setTempNumbering((n) => ({
                  ...n,
                  fullInvoicePrefix: normalizeInvoicePrefixInput(v),
                }))
              }
              maxLength={10}
              autoCapitalize="characters"
            />
            <Text style={styles.fieldLabel}>Serie completa · siguiente número</Text>
            <TextInput
              style={[styles.input, { maxWidth: 120 }]}
              value={String(tempNumbering.fullInvoiceNextNumber)}
              onChangeText={(v) =>
                setTempNumbering((n) => ({ ...n, fullInvoiceNextNumber: parseInt(v, 10) || 1 }))
              }
              keyboardType="numeric"
            />
            <Text style={styles.configHint}>{STRINGS.adjustNote}</Text>
            {visibleNumberingError ? (
              <Text style={styles.inlineError}>{visibleNumberingError}</Text>
            ) : null}
            <TouchableOpacity
              style={[styles.saveBtn, isNumberingSaveDisabled && styles.saveBtnDisabled]}
              onPress={handleSaveNumbering}
              disabled={isNumberingSaveDisabled}
            >
              {savingConfig ? <ActivityIndicator size="small" color={colors.neutral.white} /> : (
                <Text style={styles.saveBtnText}>{STRINGS.save}</Text>
              )}
            </TouchableOpacity>
          </View>
        ) : (
          <View>
            <Text style={styles.configValue}>Simplificada: {simplifiedPreview}</Text>
            <Text style={styles.configDetail}>Completa: {fullPreview}</Text>
          </View>
        )}
      </View>
    );
  };

  const renderAutomationCard = () => (
    <View style={styles.card}>
      <Text style={styles.cardTitle}>{STRINGS.automation}</Text>
      <View style={styles.automationItem}>
        <View style={styles.automationText}>
          <Text style={styles.automationLabel}>{STRINGS.autoGenerate}</Text>
          <Text style={styles.automationDesc}>{STRINGS.autoGenerateDesc}</Text>
        </View>
        <Switch
          value={billingConfig.autoGenerateInvoice || false}
          onValueChange={(v) => handleToggleAutomation('autoGenerateInvoice', v)}
          trackColor={{ false: colors.neutral.gray300, true: theme.primaryMuted }}
          thumbColor={billingConfig.autoGenerateInvoice ? theme.primary : colors.neutral.gray400}
        />
      </View>
      <View style={styles.automationItem}>
        <View style={styles.automationText}>
          <Text style={styles.automationLabel}>{STRINGS.autoSend}</Text>
          <Text style={styles.automationDesc}>{STRINGS.autoSendDesc}</Text>
        </View>
        <Switch
          value={billingConfig.autoSendToClient || false}
          onValueChange={(v) => handleToggleAutomation('autoSendToClient', v)}
          trackColor={{ false: colors.neutral.gray300, true: theme.primaryMuted }}
          thumbColor={billingConfig.autoSendToClient ? theme.primary : colors.neutral.gray400}
        />
      </View>
      <View style={styles.automationItem}>
        <View style={styles.automationText}>
          <Text style={styles.automationLabel}>{STRINGS.emailCopy}</Text>
          <Text style={styles.automationDesc}>{STRINGS.emailCopyDesc}</Text>
        </View>
        <Switch
          value={!!billingConfig.sendInvoiceCopyTo}
          onValueChange={handleToggleEmailCopy}
          trackColor={{ false: colors.neutral.gray300, true: theme.primaryMuted }}
          thumbColor={billingConfig.sendInvoiceCopyTo ? theme.primary : colors.neutral.gray400}
        />
      </View>
    </View>
  );


  // ── Portal menu ─────────────────────────────────────────────
  const openMenuInvoice = openMenuId ? invoices.find((inv) => inv.id === openMenuId) : null;
  const portalMenuOptions = openMenuInvoice ? getMenuOptions(openMenuInvoice) : [];

  // ── Main layout ──────────────────────────────────────────────
  return (
    <View style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.headerTitle}>{STRINGS.title}</Text>
        <View style={styles.headerActions}>
          <View style={styles.headerBtnWrap}>
            <Button
              variant="primary"
              size="large"
              onPress={() => navigation.navigate('CreateInvoice', {})}
              icon={<Ionicons name="add" size={18} color={theme.textOnPrimary} />}
              fullWidth
            >
              Nueva factura
            </Button>
          </View>
        </View>
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={[
          styles.scrollContent,
          isDesktop && styles.scrollContentDesktop,
        ]}
        showsVerticalScrollIndicator={false}
      >
        {/* Stats */}
        {renderStats()}

        {/* Desktop: two columns */}
        {isDesktop ? (
          <View style={styles.desktopColumns}>
            <View style={styles.mainColumn}>
              {renderInvoiceList()}
            </View>
            <View style={styles.sideColumn}>
              {renderTariffsCard()}
              {renderFiscalCard()}
              {renderInvoiceDesignCard()}
              {renderNumberingCard()}
              {renderAutomationCard()}
            </View>
          </View>
        ) : (
          <>
            {renderInvoiceList()}
            {renderTariffsCard()}
            {renderFiscalCard()}
            {renderInvoiceDesignCard()}
            {renderNumberingCard()}
            {renderAutomationCard()}
          </>
        )}
      </ScrollView>

      {/* Portal: three-dot menu rendered at root level */}
      {openMenuId && portalMenuOptions.length > 0 && (
        <>
          <Pressable
            style={styles.menuBackdrop}
            onPress={() => setOpenMenuId(null)}
          />
          <View style={[styles.menuDropdown, { top: menuPosition.top, right: menuPosition.right }]}>
            {portalMenuOptions.map((opt) => (
              <TouchableOpacity
                key={opt.label}
                style={styles.menuOption}
                onPress={() => opt.onPress()}
              >
                <Text style={[styles.menuOptionText, opt.danger && styles.menuOptionTextDanger]}>
                  {opt.label}
                </Text>
              </TouchableOpacity>
            ))}
          </View>
        </>
      )}
    </View>
  );
}

// ============================================================================
// STYLES
// ============================================================================
// HERA Design Rules:
// - Never use chip/pill selectors for option lists — use dropdowns
// - Always use spacing constants, never hardcoded values
// - All interactive UI must connect to backend — no decorative-only controls

function createStyles(theme: Theme, isDark: boolean) {
  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.bg,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.bg,
  },

  // Header
  header: {
    backgroundColor: theme.bgCard,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: typography.fontSizes.xxxl,
    color: theme.textPrimary,
    fontFamily: theme.fontSansBold,
    flex: 1,
    textAlign: 'center',
  },
  headerActions: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  headerBtnWrap: {
    minWidth: 204,
  },
  headerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.primary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.lg,
    gap: spacing.xs,
    minHeight: touchTarget.minHeight,
    ...shadows.sm,
  },
  headerBtnText: {
    color: theme.textOnPrimary,
    fontSize: typography.fontSizes.sm,
    fontFamily: theme.fontSansSemiBold,
  },

  // Scroll
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: spacing.lg,
    paddingBottom: spacing.xxxl,
    overflow: 'visible' as const,
  },
  scrollContentDesktop: {
    paddingHorizontal: spacing.xxxl,
  },

  // Stats
  statsRow: {
    flexDirection: 'row' as const,
    flexWrap: Platform.OS === 'web' ? 'nowrap' as const : 'wrap' as const,
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  statCard: {
    ...(Platform.OS === 'web'
      ? { flexGrow: 1, flexShrink: 1, flexBasis: 0, minWidth: 0, overflow: 'hidden' as const }
      : { width: '48%' as unknown as number }),
    backgroundColor: isDark ? theme.surfaceMuted : theme.bgCard,
    borderRadius: borderRadius.xl,
    padding: spacing.md,
    gap: spacing.xs,
    borderWidth: 1,
    borderColor: theme.border,
    ...shadows.sm,
  },
  statValue: {
    fontSize: typography.fontSizes.xl,
    color: theme.textPrimary,
    fontFamily: theme.fontSansBold,
  },
  statLabel: {
    fontSize: typography.fontSizes.sm,
    color: theme.textSecondary,
    fontFamily: theme.fontSans,
  },
  statSublabel: {
    fontSize: typography.fontSizes.xs,
    color: theme.textMuted,
    fontFamily: theme.fontSans,
  },

  // Desktop layout
  desktopColumns: {
    flexDirection: 'row',
    gap: spacing.lg,
    overflow: 'visible' as const,
  },
  mainColumn: {
    flex: 1,
    minWidth: 0,
  },
  sideColumn: {
    width: 340,
    gap: spacing.md,
    overflow: 'visible' as const,
    zIndex: 10,
  },

  // Card
  card: {
    backgroundColor: theme.bgCard,
    borderRadius: borderRadius.xl,
    padding: spacing.xl,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: theme.border,
    ...shadows.sm,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  cardTitle: {
    fontSize: typography.fontSizes.lg,
    color: theme.textPrimary,
    fontFamily: theme.fontSansBold,
    marginBottom: spacing.sm,
  },
  editBtn: {
    fontSize: typography.fontSizes.sm,
    color: theme.primary,
    fontFamily: theme.fontSansSemiBold,
  },

  // Config display
  configValue: {
    fontSize: typography.fontSizes.md,
    color: theme.textPrimary,
    fontFamily: theme.fontSansSemiBold,
    marginBottom: spacing.xs,
  },
  configDetail: {
    fontSize: typography.fontSizes.sm,
    color: theme.textSecondary,
    fontFamily: theme.fontSans,
    marginBottom: spacing.xs,
  },
  configHint: {
    fontSize: typography.fontSizes.xs,
    color: theme.textMuted,
    fontStyle: 'italic',
    marginTop: spacing.sm,
  },

  // Free badge
  freeBadge: {
    backgroundColor: theme.secondaryAlpha12,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.md,
    alignSelf: 'flex-start',
    marginTop: spacing.sm,
  },
  freeBadgeText: {
    fontSize: typography.fontSizes.xs,
    color: theme.secondary,
    fontFamily: theme.fontSansSemiBold,
  },

  // Filters
  filterRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.md,
    flexWrap: 'wrap',
  },
  filterChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
    backgroundColor: isDark ? theme.surfaceMuted : theme.bgMuted,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.border,
  },
  filterChipActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  filterChipText: {
    fontSize: typography.fontSizes.sm,
    color: theme.textSecondary,
    fontFamily: theme.fontSansMedium,
  },
  filterChipTextActive: {
    color: theme.textOnPrimary,
  },

  // Search
  searchInput: {
    backgroundColor: isDark ? theme.surfaceMuted : theme.bgMuted,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: theme.border,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: typography.fontSizes.sm,
    color: theme.textPrimary,
    marginBottom: spacing.md,
  },

  // Invoice row
  invoiceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: theme.borderLight,
    minHeight: touchTarget.minHeight,
  },
  invoiceInfo: {
    flex: 1,
    gap: spacing.xs,
  },
  invoiceNumber: {
    fontSize: typography.fontSizes.sm,
    color: theme.textPrimary,
    fontFamily: theme.fontSansSemiBold,
  },
  invoiceClient: {
    fontSize: typography.fontSizes.sm,
    color: theme.textSecondary,
    fontFamily: theme.fontSans,
  },
  invoiceDate: {
    fontSize: typography.fontSizes.xs,
    color: theme.textMuted,
    fontFamily: theme.fontSans,
  },
  invoiceRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  invoiceAmount: {
    fontSize: typography.fontSizes.sm,
    color: theme.textPrimary,
    fontFamily: theme.fontSansBold,
  },
  invoiceActions: {
    flexDirection: 'row',
    gap: spacing.xs,
    alignItems: 'center',
  },
  iconBtn: {
    padding: spacing.xs,
    minWidth: touchTarget.minWidth - 8,
    minHeight: touchTarget.minHeight - 8,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Three-dot menu (portal — rendered at root level)
  menuBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2000,
  },
  menuDropdown: {
    position: 'absolute',
    backgroundColor: theme.bgElevated,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: borderRadius.lg,
    zIndex: 2001,
    minWidth: 160,
    ...shadows.md,
    elevation: 20,
    ...(Platform.OS === 'web' ? { boxShadow: '0 4px 12px rgba(0,0,0,0.15)' } as Record<string, string> : {}),
  },
  menuOption: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  menuOptionText: {
    fontSize: typography.fontSizes.sm,
    color: theme.textPrimary,
    fontFamily: theme.fontSans,
  },
  menuOptionTextDanger: {
    color: colors.feedback.error,
  },

  // Badge
  badge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
  },
  badgeText: {
    fontSize: typography.fontSizes.xs,
    fontFamily: theme.fontSansSemiBold,
  },

  // Empty state
  emptyState: {
    alignItems: 'center',
    paddingVertical: spacing.xxxl,
    gap: spacing.sm,
  },
  emptyTitle: {
    fontSize: typography.fontSizes.md,
    color: theme.textPrimary,
    fontFamily: theme.fontSansSemiBold,
    textAlign: 'center',
  },
  emptyDesc: {
    fontSize: typography.fontSizes.sm,
    color: theme.textSecondary,
    fontFamily: theme.fontSans,
    textAlign: 'center',
    maxWidth: 300,
  },

  // Edit form
  editForm: {
    gap: spacing.sm,
    overflow: 'visible' as const,
  },
  formGroup: {
    marginBottom: spacing.sm,
    zIndex: 100,
    overflow: 'visible' as const,
  },
  fieldLabel: {
    fontSize: typography.fontSizes.sm,
    color: theme.textPrimary,
    fontFamily: theme.fontSansSemiBold,
    marginBottom: spacing.xs,
  },
  input: {
    backgroundColor: isDark ? theme.surfaceMuted : theme.bgMuted,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: borderRadius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: typography.fontSizes.sm,
    color: theme.textPrimary,
  },
  inputError: {
    borderColor: theme.error,
  },
  inlineError: {
    color: theme.error,
    fontSize: typography.fontSizes.xs,
    fontFamily: theme.fontSansMedium,
    marginTop: spacing.sm,
  },
  chipRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  selectChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
    backgroundColor: isDark ? theme.surfaceMuted : theme.bgMuted,
    borderWidth: 1,
    borderColor: theme.border,
  },
  selectChipActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  selectChipText: {
    fontSize: typography.fontSizes.sm,
    color: theme.textSecondary,
    fontFamily: theme.fontSans,
  },
  selectChipTextActive: {
    color: theme.textOnPrimary,
    fontFamily: theme.fontSansSemiBold,
  },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: touchTarget.minHeight,
  },
  saveBtn: {
    backgroundColor: theme.primary,
    borderRadius: borderRadius.lg,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: touchTarget.minHeight,
    marginTop: spacing.sm,
  },
  saveBtnDisabled: {
    opacity: 0.65,
  },
  saveBtnText: {
    color: theme.textOnPrimary,
    fontSize: typography.fontSizes.sm,
    fontFamily: theme.fontSansBold,
  },
  invoiceAccentPreview: {
    width: 24,
    height: 24,
    borderRadius: borderRadius.sm,
    borderWidth: 1,
    borderColor: theme.border,
  },
  invoiceLogoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  invoiceLogoFrame: {
    width: 112,
    height: 64,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: isDark ? theme.surfaceMuted : theme.bgMuted,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden' as const,
  },
  invoiceLogoPreview: {
    width: '100%',
    height: '100%',
  },
  invoiceColorSwatches: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  invoiceColorSwatch: {
    width: 34,
    height: 34,
    borderRadius: borderRadius.md,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  invoiceColorSwatchSelected: {
    borderColor: theme.textPrimary,
  },

  // Automation
  automationItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: theme.borderLight,
    minHeight: touchTarget.minHeight,
  },
  automationText: {
    flex: 1,
    marginRight: spacing.md,
  },
  automationLabel: {
    fontSize: typography.fontSizes.sm,
    color: theme.textPrimary,
    fontFamily: theme.fontSansSemiBold,
  },
  automationDesc: {
    fontSize: typography.fontSizes.xs,
    color: theme.textMuted,
    fontFamily: theme.fontSans,
    marginTop: spacing.xs,
  },

  // Tariff editor
  tariffEditRow: {
    backgroundColor: isDark ? theme.surfaceMuted : theme.bgMuted,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginBottom: spacing.sm,
    overflow: 'visible' as const,
    zIndex: 100,
  },
  tariffEditFields: {
    gap: spacing.sm,
    overflow: 'visible' as const,
  },
  tariffPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    flexWrap: 'wrap',
  },
  tariffToggles: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  tariffToggle: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    backgroundColor: isDark ? theme.surfaceMuted : theme.bgMuted,
    borderWidth: 1,
    borderColor: theme.border,
  },
  tariffToggleActive: {
    backgroundColor: theme.primaryMuted,
    borderColor: theme.primary,
  },
  tariffToggleText: {
    fontSize: typography.fontSizes.xs,
    color: theme.textSecondary,
    fontFamily: theme.fontSansMedium,
  },
  tariffToggleTextActive: {
    color: theme.primary,
    fontFamily: theme.fontSansSemiBold,
  },
  tariffDisplayRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  defaultBadgeInline: {
    fontSize: typography.fontSizes.xs,
    color: theme.primary,
    fontFamily: theme.fontSansSemiBold,
  },
  addTariffBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.sm,
    alignSelf: 'flex-start',
  },
  addTariffBtnText: {
    fontSize: typography.fontSizes.sm,
    color: theme.primary,
    fontFamily: theme.fontSansSemiBold,
  },
  selectChipSmall: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    backgroundColor: isDark ? theme.surfaceMuted : theme.bgMuted,
    borderWidth: 1,
    borderColor: theme.border,
  },
  fieldHint: {
    fontSize: typography.fontSizes.xs,
    color: theme.textMuted,
    fontStyle: 'italic',
  },

  // Pagination
  paginationContainer: {
    alignItems: 'center',
    marginTop: spacing.md,
    gap: spacing.xs,
  },
  paginationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  paginationBtn: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: theme.border,
    minWidth: touchTarget.minWidth - 8,
    minHeight: touchTarget.minHeight - 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  paginationBtnDisabled: {
    borderColor: theme.borderLight,
    opacity: 0.5,
  },
  paginationLabel: {
    fontSize: typography.fontSizes.sm,
    color: theme.textPrimary,
    fontFamily: theme.fontSansMedium,
  },
  paginationTotal: {
    fontSize: typography.fontSizes.xs,
    color: theme.textMuted,
    fontFamily: theme.fontSans,
  },

  // Invoice list loading overlay
  invoiceListLoading: {
    opacity: 0.5,
  },
  invoiceListOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },

  });
}
